/** Manufactured diagnostic snapshots only; no factory/instruction/addon execution. */
import test from 'node:test';
import {gunzipSync} from 'node:zlib';
import {regularBytes} from '../scripts/bochs-cpu3-native-paged-int-iret/driver-auth.mjs';
import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {sha,relativeImports,compiledRevision,ownedBuildBinding,requireReadyBinding,requireReadyBuild,validateBuildBinding} from '../scripts/bochs-cpu3-native-paged-int-iret/driver-auth.mjs';
import {deriveDriverProvider,profileProviderSha256} from '../scripts/bochs-cpu3-native-paged-int-iret/driver-provider.mjs';
import {derivePagedIntIretProvider} from '../scripts/bochs-cpu3-native-paged-int-iret/provider-derivation.mjs';
import {deriveIntIretComparison,comparisonParentSha256} from '../scripts/bochs-cpu3-native-paged-int-iret/cpu-comparison.mjs';
import {compareBoundary,intIretProgress,validateMilestones,wholeNativeWords,validateFinalPages,validateMemoryTape,validateNativeEffects,nativeAdEffects} from '../scripts/bochs-cpu3-native-paged-int-iret/parity.mjs';
import {validateInput,finalizeAuthentication,deriveIntIretLifecycle,verifyHeldLifecycle} from '../scripts/bochs-cpu3-native-paged-int-iret/runner.mjs';
import {namedCuts,layout,bootStores,frameStores,adTransitions,expectedPages,expectedCr0,expectedShadow,expectedAx,gate,codeCache,dataCache} from '../scripts/bochs-cpu3-native-paged-int-iret/profile.mjs';
const copy=x=>structuredClone(x);
import {nativeFrameStores} from '../scripts/bochs-cpu3-native-paged-int-iret/provider-profile.mjs';
const qs=[0,25,26,28,30,32,33,34,36,37,38,39,40,41];
// Entirely manufactured ABI/JS snapshots; no terminal native metadata claimed actual.
function fixture(name='returned-from-IRET-before-HLT',q=41){
 const at=namedCuts.findIndex(c=>c.name===name),cut=namedCuts[at];assert.ok(cut);const protectedCode=cut.cs===0x18,ds=at>=5?0x10:0,ss=at>=6?0x10:0;
 const stores=at===0?[]:[...bootStores,...(at>=11?frameStores:[])].map(s=>({...s,bytes:[...s.bytes]})),updates=adTransitions.slice(0,at<9?0:at===9?3:at===10?4:7).map(s=>({...s})),pages=expectedPages(stores,updates);
 const shadow=expectedShadow(cut.cs,cut.eip);
 const j={eax:protectedCode?expectedAx(cut.cs,cut.eip):at?0x80000001:0,ecx:0,edx:0,ebx:0,esp:at>=7?(at===11||at===12?0xdffa:0xe000):0,ebp:0,esi:0,edi:0,eip:cut.eip,eflags:2,cr0:expectedCr0(cut.cs,cut.eip),cr2:0,cr3:at>=3?0x1000:0,cr4:0,cs:cut.cs,ds,ss,es:0,fs:0,gs:0,pc:((name==='reset'?0xffff0000:protectedCode?0:0xf0000)+cut.eip)>>>0,gdtr:at?{base:0x600,limit:0x1f}:{base:0,limit:0xffff},idtr:at>=2?{base:gate.base,limit:gate.limit}:{base:0,limit:0xffff},ldtr:{selector:0,base:0,limit:0xffff,present:true,type:2},tr:{selector:0,base:0,limit:0xffff,present:true,type:11},segmentCaches:Array.from({length:6},()=>({base:0,limit:0xffff,default32:false,present:true})),debugRegisters:[0,0,0,0,0,0,0xffff1ff0,0x400],halted:false,shutdown:false,interruptShadow:shadow[0],nmiShadow:shadow[1],debugShadow:shadow[2]};
 j.segmentCaches[1]=protectedCode?copy(codeCache):{base:name==='reset'?0xffff0000:0xf0000,limit:0xffff,default32:false,present:true};if(ds)j.segmentCaches[3]=copy(dataCache);if(ss)j.segmentCaches[2]=copy(dataCache);
 const n={state:['eax','ecx','edx','ebx','esp','ebp','esi','edi','eip','eflags','cr0','cr2','cr3','cs','ds','ss'].map(k=>j[k]).concat(j.gdtr.base,j.gdtr.limit,j.idtr.base,j.idtr.limit),extra:Array(20).fill(0),segments:Array(90).fill(0),system:Array(30).fill(0),debug:[0,0,0,0,0xffff1ff0,0x400],nativeTicks:q,successfulQuanta:q,mappingEpoch:0,boardA20:1,activityState:0,chargedNativeTicks:1,chargedQuanta:1,reason:1,execution:{attempts:q,completed:q,repIterations:0,repPartial:0,faults:0,portCommits:0,irqDeliveries:0,haltIdleCuts:0},fallback:{bochsRamReads:0,bochsRamWrites:0,bochsDirectPointers:0,bochsPio:0,bochsTimer:0}};
 for(const [i,key]of ['es','cs','ss','ds','fs','gs'].entries()){const s=j[key],cache=j.segmentCaches[i],valid=i===2&&ss&&at>=11?7:1,type=i===1&&protectedCode?11:3;n.segments.splice(i*15,15,i,s,s>>>3,0,0,valid,1,0,1,type,cache.base>>>0,cache.limit,0,0,0);}
 n.extra[0]=j.debugRegisters[6];n.extra[1]=j.debugRegisters[7];n.extra.splice(2,3,j.es,j.fs,j.gs);n.extra.splice(5,3,...n.segments.slice(17,20));n.extra[9]=1;n.extra[13]=j.segmentCaches[1].base>>>0;n.extra[14]=0xffff;
 for(let i=0;i<2;i++){n.system[i*15]=i+6;n.system[i*15+6]=1;n.system[i*15+9]=i?11:2;n.system[i*15+11]=0xffff;}
 const bytes=v=>[v&255,(v>>>8)&255,(v>>>16)&255,v>>>24];
 const nativeUpdates=nativeAdEffects.filter(e=>updates.some(u=>u.raw===e.raw));
 const writes=[...stores.slice(0,20).map(w=>({kind:'boot',raw:w.raw,bytes:[...w.bytes],generation:1,nativeTicks:0,successfulQuanta:0,cycles:4})),...nativeUpdates.map(w=>({kind:'ad',raw:w.raw,bytes:bytes(w.after),before:w.before,after:w.after,generation:2,nativeTicks:0,successfulQuanta:0,cycles:4})),...(at>=11?nativeFrameStores.map(w=>({kind:'frame',raw:w.raw,bytes:[...w.bytes],generation:1,nativeTicks:0,successfulQuanta:0,cycles:4})):[])];
 const board={board:{cycles:4+6*q,debt:q?6:0,deadline:6000,a20Enabled:true},successfulQuanta:q,mappingEpoch:0,generations:[],ram:{bootStores:Math.min(stores.length,20),storeCount:writes.length,frameWords:at>=11?3:0,admitted:protectedCode&&at>=10,reads:[],writes}};
 return {n,board,js:{q,cpu:j,board:copy(board.board),pages:copy(pages),stores,updates},pages};
}

test('checked held lifecycle, CPU/provider inverse and real multiline closure reject unknown source',()=>{
 verifyHeldLifecycle();const actual=gunzipSync(readFileSync(new URL('../scripts/bochs-cpu3-native-paged-int-iret/actual-first-build-prepare.json.gz',import.meta.url)));assert.equal(actual.length,1052065);assert.equal(sha(actual),'bc37a25c7eae18c5ef9e586de3df8317bd7375e3062e70dfda6e87dd610a28f2');const dir=mkdtempSync(join(tmpdir(),'int-manifest-cap-'));try{const path=join(dir,'prepare.json');writeFileSync(path,actual);assert.throws(()=>regularBytes(path,1<<20),'original1MiBcap refused genuine manifest');assert.deepEqual(regularBytes(path,2<<20),actual);assert.equal(JSON.parse(regularBytes(path,2<<20)).boardRevision,compiledRevision);}finally{rmSync(dir,{recursive:true,force:true});}const old=readFileSync(new URL('../scripts/bochs-cpu3-native-nonidentity-paging/runner.mjs',import.meta.url));assert.ok(deriveIntIretLifecycle(old).includes('returned-from-IRET-before-HLT'));assert.throws(()=>deriveIntIretLifecycle(Buffer.from('unknown')));
 const p=deriveDriverProvider(derivePagedIntIretProvider().bytes);assert.equal(p.parentSha256,profileProviderSha256);for(const x of ['ramPages()','memoryEvents()','Uint8Array.from','driverMemoryEvents.length<1024','direction:"read"','direction:"write"'])assert.ok(p.bytes.includes(x));assert.throws(()=>deriveDriverProvider(Buffer.from('unknown')));
 const c=deriveIntIretComparison(readFileSync(new URL('../scripts/bochs-cpu3-native-cold-bios/parity.mjs',import.meta.url)));assert.equal(c.baseSha256,comparisonParentSha256);assert.ok(c.bytes.includes('expectedCr0(j.cs,j.eip)'));assert.throws(()=>deriveIntIretComparison(Buffer.from('unknown')));assert.ok(relativeImports(readFileSync(new URL('../src/i8086-machine.js',import.meta.url))).includes('./machine-checkpoint.js'));assert.deepEqual(relativeImports(Buffer.from(`const q="import {x} from './foreign.js'";\nexport {\n x\n} from './actual.js';`)),['./actual.js']);
});
test('comparable CPU, strict CS/DS/SS first-frame cache and ten wholepages deny mutations',()=>{
 const f=fixture();assert.equal(compareBoundary(f.n,f.board,f.js,f.pages).status,'COMPARABLE_PARITY_PASS');assert.equal(wholeNativeWords(f.n).length,166);const inspect=copy(f);for(const k of ['activityState','chargedNativeTicks','chargedQuanta','reason'])delete inspect.n[k];assert.equal(compareBoundary(inspect.n,inspect.board,inspect.js,inspect.pages,'final-inspect',0).status,'COMPARABLE_PARITY_PASS');
 for(const change of [x=>x.n.state[0]=0xbeef,x=>x.n.state[10]=0x7ffffff1,x=>x.n.state[12]=0,x=>x.n.state[9]=0x802,x=>x.n.segments[20]=3,x=>x.n.segments[35]=1,x=>x.n.segments[50]=3,x=>x.n.system[11]=0,x=>x.n.debug[0]=1,x=>x.board.board.debt=0,x=>x.js.cpu.cr4=1]){const x=copy(f);change(x);assert.throws(()=>compareBoundary(x.n,x.board,x.js,x.pages));}for(const key of Object.keys(layout)){const x=copy(f);x.pages[key][3000]=1;assert.throws(()=>compareBoundary(x.n,x.board,x.js,x.pages));}
 const early=fixture('SS-loaded',33);compareBoundary(early.n,early.board,early.js,early.pages);assert.deepEqual([early.js.cpu.interruptShadow,early.js.cpu.nmiShadow,early.js.cpu.debugShadow],[1,1,0]);early.n.segments[35]=7;assert.throws(()=>compareBoundary(early.n,early.board,early.js,early.pages));
});
test('PG entry and zero-Q keep unequal raw boards/pages unmatched while CPU and shadows stay strict',()=>{
 for(const name of ['PG-enabled','entered-paged-code']){const f=fixture(name,qs[namedCuts.findIndex(c=>c.name===name)]);f.pages.table[0x1c]^=0x20;f.board.board.ramHash='different';assert.equal(compareBoundary(f.n,f.board,f.js,f.pages).status,'UNMATCHED_PHASE');f.n.state[0]=3;assert.throws(()=>compareBoundary(f.n,f.board,f.js,f.pages));}
 const f=fixture('before-INT',38);f.pages.table[0x34]^=0x20;f.board.board.debt=999;assert.equal(compareBoundary(f.n,f.board,f.js,f.pages,'resume',0).status,'UNMATCHED_PHASE');assert.throws(()=>compareBoundary(f.n,f.board,f.js,f.pages,'resume',1));const shadow=fixture('SS-loaded',33);shadow.js.cpu.debugShadow=1;assert.throws(()=>compareBoundary(shadow.n,shadow.board,shadow.js,shadow.pages));
});
test('bounded independent N/Q refuses missing fallback/counters/fault/IRQ/REP/HLT',()=>{
 const n=fixture('returned-from-IRET-before-HLT',1).n;assert.deepEqual(intIretProgress({n:0,q:0},n),{n:1,q:1,dn:1,dq:1});for(const change of [x=>x.nativeTicks=513,x=>x.successfulQuanta=513,x=>x.chargedQuanta=0,x=>x.activityState=1,x=>x.reason=4,x=>x.fallback={},x=>x.fallback.bochsDirectPointers=1,x=>x.execution.irqDeliveries=1,x=>x.execution.repIterations=1,x=>delete x.execution.portCommits]){const x=copy(n);change(x);assert.throws(()=>intIretProgress({n:0,q:0},x));}const zero={...copy(n),chargedNativeTicks:0,chargedQuanta:0,reason:7};assert.equal(intIretProgress({n:1,q:1},zero).dq,0);
});
function cuts(){return namedCuts.map((c,i)=>{const f=fixture(c.name,qs[i]);return {name:c.name,q:qs[i],native:f.n,board:f.board,javascript:f.js,pages:f.pages,comparison:compareBoundary(f.n,f.board,f.js,f.pages,c.name==='reset'?'reset':'resume',1)};});}
test('manufactured fourteen cuts and independent native frame/AD tape deny chronology and page corruption',()=>{
 const c=cuts();assert.deepEqual(validateMilestones(c),{milestones:14,comparableCuts:12,unmatchedCuts:2,pageBytesPerRecordedBoundary:40960});validateFinalPages(c.at(-1).pages);const f=fixture();assert.deepEqual(validateNativeEffects(f.board,f.js,true),{bootWrites:20,frameWrites:3,nativeAdWrites:6,callbackOrder:'independent native tape; not JS tape equality'});assert.notDeepEqual(f.board.ram.writes.filter(w=>w.kind==='frame').map(w=>w.raw),f.js.stores.slice(20).map(w=>w.raw));
 for(const change of [x=>x.pop(),x=>x.reverse(),x=>x[8].comparison.status='COMPARABLE_PARITY_PASS',x=>x[11].native.segments[35]=1,x=>x[10].native.segments[50]=7,x=>x[13].pages.stack[0xffa]=0,x=>x[13].pages.aliasStack[0]=0,x=>x[13].pages.table[0xc]|=0x40]){const x=copy(c);change(x);assert.throws(()=>validateMilestones(x));}
 const reversed=copy(f);reversed.board.ram.writes.splice(-3,3,...reversed.board.ram.writes.slice(-3).reverse());assert.throws(()=>validateNativeEffects(reversed.board,reversed.js,true));const split=copy(f),ad=split.board.ram.writes.find(w=>w.kind==='ad'&&w.raw===0x2034);ad.after=0xc023;assert.throws(()=>validateNativeEffects(split.board,split.js,true));
 const write=f.board.ram.writes[0],read={raw:0x1000,bytes:[3,0x20,0,0],generation:1,nativeTicks:0,successfulQuanta:0};f.board.ram.reads=[read];const events=[{direction:'write',ordinal:0,...write},{direction:'read',ordinal:1,...read},...f.board.ram.writes.slice(1).map((w,i)=>({direction:'write',ordinal:i+2,...w}))];assert.equal(validateMemoryTape(events,f.board).events,events.length);events[1].ordinal=0;assert.throws(()=>validateMemoryTape(events,f.board));
});
test('owned PENDING compiled208 authority refuses before input/factory, old DSOs and missing source',()=>{
 const b=ownedBuildBinding();assert.equal(b.status,'PENDING_PAGED_INT_IRET_NATIVE_BUILD');assert.equal(Object.keys(b.compiledFiles).length,208);assert.equal(b.compiledRevision,compiledRevision);assert.throws(()=>requireReadyBuild(),/pending/);assert.throws(()=>validateInput({}),/pending/);
 const diagnostic={...copy(b),status:'ROOT_REVIEWED_PAGED_INT_IRET_NATIVE_BUILD',addonSha256:'e'.repeat(64),buildRun:1,artifactId:1,staticAuthority:{artifactZipSha256:'a'.repeat(64),artifactZipBytes:1,independentAuditSha256:'b'.repeat(64),preparedManifestSha256:'c'.repeat(64),buildReceiptSha256:'d'.repeat(64)}};validateBuildBinding(diagnostic);assert.equal(requireReadyBinding(diagnostic),diagnostic);
 for(const h of ['f3e7406b0b8ce88fcb05be4b99cc0c7a6fab27fa12f1dff071d323ad707a37b7','4076aca36f5d7e79eb7cdd829746fd35edd852cd407d5c6eab905f7c1799b439','98c7d11961463ae8a4dfbd108cf94d1e745f09f5d7684afa3bc31792cdac203e'])assert.throws(()=>validateBuildBinding({...diagnostic,addonSha256:h}));for(const mutate of [x=>x.compiledRevision='f'.repeat(40),x=>x.compiledSourceSha256='0'.repeat(64),x=>delete x.compiledFiles['package.json'],x=>x.status='READY',x=>x.generated['bochs/owned-paged-int-iret-ROM.bin']='0'.repeat(64),x=>x.addonSha256='a'.repeat(64)]){const x=copy(b);mutate(x);assert.throws(()=>validateBuildBinding(x));}
});
test('all-outcome input/config/source/tool checks retain primary error and deny final mutation',()=>{
 const pins={input:'a',driver:{revision:'b'},compiled:{revision:'c'},build:{sha:'d'},configuration:{sha:'e'},node:'f'};assert.equal(finalizeAuthentication({status:'PASS'},null,pins,copy(pins)),null);for(const k of Object.keys(pins)){const a=copy(pins);a[k]='changed';const first=Error('manufactured primary divergence'),r={status:'FAIL',error:String(first)};assert.equal(finalizeAuthentication(r,first,pins,a),first);assert.match(r.error,/primary/);assert.match(r.finalAuthenticationError,/final /);}const r={status:'PASS'},failure=Error('manufactured configuration read failure');assert.equal(finalizeAuthentication(r,null,pins,{},failure),failure);assert.equal(r.status,'FAIL');
});
test('driver identity authenticates exact clean imported closure and actual static binding in owned alternate fixture',()=>{
 const root=fileURLToPath(new URL('../',import.meta.url)),revision=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),paths=new Set();
 const seeds=['scripts/bochs-cpu3-native-paged-int-iret/runner.mjs','scripts/bochs-cpu3-native-paged-int-iret/DRIVER-SOURCE.md','scripts/bochs-cpu3-native-paged-int-iret/driver-build-binding.json','scripts/bochs-cpu3-native-cold-bios/board-provider.mjs','test/i80386-paged-int-iret-driver-source.test.mjs','scripts/bochs-cpu3-native-nonidentity-paging/runner.mjs','src/experimental/i80386.js','scripts/bochs-cpu3-native-paged-int-iret/actual-first-build-prepare.json.gz','package.json','roms/free-at-bios/LICENSE','roms/free-at-bios/BIOS-bochs-legacy','roms/free-at-bios/vgabios-lgpl.bin'];
 function visit(p){if(paths.has(p))return;paths.add(p);const b=readFileSync(resolve(root,p)),g=execFileSync('git',['show',revision+':'+p],{cwd:root,maxBuffer:16<<20});assert.equal(sha(b),sha(g));if(/\.(js|mjs)$/.test(p))for(const q of relativeImports(b))visit(resolve(root,dirname(p),q).slice(root.length));}for(const p of seeds)visit(p);
 const d=mkdtempSync(join(tmpdir(),'paging-driver-clean-')),clean=join(d,'source');try{mkdirSync(clean);execFileSync('git',['init','--quiet',clean]);const objects=execFileSync('git',['rev-parse','--path-format=absolute','--git-path','objects'],{cwd:root,encoding:'utf8'}).trim();writeFileSync(join(clean,'.git/objects/info/alternates'),objects+'\n');const shallow=execFileSync('git',['rev-parse','--path-format=absolute','--git-path','shallow'],{cwd:root,encoding:'utf8'}).trim();try{writeFileSync(join(clean,'.git/shallow'),readFileSync(shallow));}catch(e){if(e.code!=='ENOENT')throw e;}execFileSync('git',['update-ref','HEAD',revision],{cwd:clean});execFileSync('git',['sparse-checkout','init','--no-cone'],{cwd:clean});execFileSync('git',['sparse-checkout','set','--no-cone','--stdin'],{cwd:clean,input:[...paths].sort().map(p=>'/'+p).join('\n')+'\n'});execFileSync('git',['checkout','--quiet','--detach',revision],{cwd:clean});const raw=execFileSync(process.execPath,['--max-old-space-size=128','--input-type=module','-e',"import {driverSourceIdentity,ownedBuildBinding} from './scripts/bochs-cpu3-native-paged-int-iret/driver-auth.mjs';console.log(JSON.stringify({source:driverSourceIdentity(),pending:ownedBuildBinding().status}))"],{cwd:clean,encoding:'utf8',timeout:10000,maxBuffer:2<<20});const v=JSON.parse(raw);assert.equal(v.source.revision,revision);assert.deepEqual(Object.keys(v.source.hashes).sort(),[...paths].sort());assert.ok(v.source.hashes['src/machine-checkpoint.js']);assert.ok(v.source.hashes['scripts/bochs-cpu3-native-paged-int-iret/driver-build-binding.json']);assert.equal(v.pending,'PENDING_PAGED_INT_IRET_NATIVE_BUILD');}finally{rmSync(d,{recursive:true,force:true});}
});
