import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from 'node:fs';import {deriveProfile,sha256}from '../scripts/owned-baseline-profile/derive.mjs';
const original=readFileSync(new URL('../scripts/run-i80386-native-owned-in8.mjs',import.meta.url),'utf8');
test('complete profile inverse preserves original native scheduler and every guard',()=>{const d=deriveProfile(original,[],{sourceRevision:'fe1',generatorSha256:'test'});let back=d.source;for(const s of [...d.seams].reverse())back=back.replace(s.after,s.before);assert.equal(back,original);assert.equal(d.originalSha256,sha256(original));assert.equal(d.derivedSha256,sha256(d.source));assert.ok(d.inverseExact);});
test('Inspector starts after create, outside original process CPU window and stops before settlement',()=>{const s=deriveProfile(original,[],{}).source;assert.ok(s.indexOf('const reset=create(')<s.indexOf("await profilerPost('Profiler.start')"));assert.ok(s.indexOf("await profilerPost('Profiler.start')")<s.indexOf('const executionCPUStart='));assert.ok(s.indexOf('executionCPU={')<s.indexOf("await profilerPost('Profiler.stop')"));assert.ok(s.indexOf("await profilerPost('Profiler.stop')")<s.indexOf('const settlementStart='));assert.ok(s.includes('profile.cpuprofile'));assert.ok(s.includes('failed-profile.cpuprofile'));});
test('missing or duplicate source seam fails instead of silently changing scheduler',()=>{assert.throws(()=>deriveProfile(original.replace('const checkpoints=[];','const cuts=[];'),[],{}));assert.throws(()=>deriveProfile(original+"\nimport assert from 'node:assert/strict';",[],{}));});
test('fixed hosted scope has one baseline cell and no candidate gate',()=>{const s=readFileSync(new URL('../scripts/ci-profile-i80386-owned-baseline.py',import.meta.url),'utf8');assert.ok(s.includes("for root,rev in [(C,BASE)]"));assert.ok(s.includes("execute('alignment'"));assert.ok(s.indexOf("execute('alignment'")<s.indexOf("execute('profile-child-parent'"));assert.ok(s.includes("for k in ['reset','final','checkpoints','settled'"));assert.ok(!s.includes("execute('benchmark'"));assert.ok(s.includes('terminateTree(child.pid)'));});

import {execFileSync}from 'node:child_process';
test('actual profile validation rejects malformed sample tape and missing execution samples',()=>{const s=readFileSync(new URL('../scripts/ci-profile-i80386-owned-baseline.py',import.meta.url),'utf8');const begin=s.indexOf("assert type(raw['startTime'])"),end=s.indexOf("summary={'status':",begin);assert.ok(begin>=0&&end>begin);const body=s.slice(begin,end);const code=`import copy\nbody=${JSON.stringify(body)}\nbase={'startTime':100,'endTime':300,'samples':[1,1],'timeDeltas':[50,50],'nodes':[{'id':1}]}\nphases={'executionBeginUs':140,'executionEndUs':220}\ndef check(raw):\n scope={'raw':raw,'phases':phases}\n exec(body,scope)\n return scope['selected']\nassert check(base)==[0,1]\nfor mutate in [lambda r:r['timeDeltas'].pop(),lambda r:r['samples'].__setitem__(0,2),lambda r:r['timeDeltas'].__setitem__(0,-1),lambda r:r.__setitem__('startTime',2**53),lambda r:r['nodes'].append({'id':1}),lambda r:r.__setitem__('timeDeltas',[1,1])]:\n r=copy.deepcopy(base);mutate(r)\n try:check(r)\n except (AssertionError,TypeError):pass\n else:raise AssertionError('malformed profile admitted')\nprint('7 actual-profile validation controls PASS')\n`;assert.match(execFileSync('python3',['-c',code],{encoding:'utf8'}),/7 actual-profile validation controls PASS/);});
