import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync,rmSync}from 'node:fs';import {tmpdir}from 'node:os';import {join}from 'node:path';import {createHash}from 'node:crypto';
import {validateBaseline,validateInput}from '../scripts/bochs-cpu3-native-owned-pic-imr-profile/admission.mjs';
import {sourceIdentity,authenticateBuild,supportAssets}from '../scripts/bochs-cpu3-native-owned-pic-imr-profile/identity.mjs';
import {candidateAssets}from '../scripts/bochs-cpu3-native-owned-pic-imr/identity.mjs';
import {deriveOwnedPicImrRuntime}from '../scripts/bochs-cpu3-native-owned-pic-imr/runtime.mjs';
import {validateResetWitness,canonicalRamSha256}from '../scripts/bochs-cpu3-native-owned-pic-imr-profile/reset-witness.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),BASE='fdca8f8fa92952cd9cd5f4447e66b194a5f691025bcf925f7ddd443290143346',ROM='8a7380f01bbc40985d377fe9764667749c36b05d45ee602b28c7e68556bd509f';
const bytes=readFileSync(new URL('./fixtures/i80386-owned-pic-imr-js-reference.json',import.meta.url)),baseline=JSON.parse(bytes),canonicalProof=JSON.parse(readFileSync(new URL('./fixtures/i80386-owned-pic-imr-canonical-proof.json',import.meta.url)));
test('authentic actual JS reference admits new PIC profile, measured six cuts and source111',()=>{assert.equal(sha(bytes),BASE);assert.equal(Object.keys(baseline.source.hashes).length,111);assert.equal(baseline.source.revision,'a6f605280f778b2bc409ef97ac3b40e15874530c');assert.equal(validateBaseline(baseline).length,6);assert.equal(baseline.attempts,100702);assert.equal(baseline.q,100700);assert.deepEqual(baseline.picReads.map(r=>[r.port,r.value]),[[33,255],[161,255]]);});
for(const [name,mutate]of [['ROM',b=>b.rom.sha256='25c242668fb1e0cbf940a35045a5e1173d992232766a4cbdb6a369ef3929a939'],['PIC witness',b=>b.final.picImrWitness[1]=254],['PIC port',b=>b.picReads[0].port=32],['poll',b=>b.picReads[0].before.pollPending=true],['read ACK effect',b=>b.picReads[0].after.isr^=1]])test('PIC reference rejects '+name+' before addon admission',()=>{const b=structuredClone(baseline);mutate(b);assert.throws(()=>validateBaseline(b));});
test('input refuses historical PIT baseline hash',()=>{const v=Object.fromEntries(['addon','configuration','baseline','output','preparedManifest','buildReceipt'].map(k=>[k,'/not-loaded']));Object.assign(v,{sha256:'a'.repeat(64),preparedManifestSha256:'b'.repeat(64),buildReceiptSha256:'c'.repeat(64),baselineSha256:BASE,hostJournal:false,nativeTrace:false});assert.equal(validateInput(v),v);assert.throws(()=>validateInput({...v,baselineSha256:'bf026d23f0c51d63a9744dc4facb4d58809c50f1d35747ffc6ea5873b518e45e'}));});
test('new canonical anchor is authentic own-reset evidence; wrong raw profile or old anchor denied',()=>{assert.equal(canonicalProof.originalCaptureSha256,BASE);assert.equal(canonicalProof.rawRamSha256,baseline.final.memorySha256);assert.equal(canonicalProof.ramCanonicalSha256,canonicalRamSha256);const e={resetWitness:canonicalProof.resetWitness,ramCanonicalSha256:canonicalRamSha256};validateResetWitness(e,{edx:baseline.reset.cpu.edx,cr0:baseline.reset.cpu.cr0},'javascript');assert.throws(()=>validateResetWitness({...e,ramCanonicalSha256:'588f9bfd1292b8405d0e42552147fb2d8d082a8253b52771291ca0a603eaf18f'},{edx:0x300,cr0:0},'javascript'));assert.throws(()=>validateResetWitness(e,{edx:0,cr0:0x7ffffff0},'javascript'));});
test('full runner inverse keeps original scheduler, caps, chronology and CPU window',()=>{let s=readFileSync(new URL('../scripts/run-i80386-native-owned-pic-imr.mjs',import.meta.url),'utf8');const old=readFileSync(new URL('../scripts/run-i80386-native-owned-in8.mjs',import.meta.url),'utf8');s=s.replaceAll('bochs-cpu3-native-owned-pic-imr-profile/','bochs-cpu3-native-owned-in8/').replaceAll('bochs-cpu3-native-owned-pic-imr/provider.mjs','bochs-cpu3-native-owned-in8/provider.mjs').replace('{createOwnedPicImrProvider as createOwnedIn8Provider}','{createOwnedIn8Provider}').replace(ROM,'25c242668fb1e0cbf940a35045a5e1173d992232766a4cbdb6a369ef3929a939').replace('887b7eb9959044f45868a71c29c5c013d65ec0ad3e0205c738719757e63b0ffb','8bbabd33892728f64bae9b9a558ba106112aef5024196e10aa037e45d0ca7344').replace('assert.deepEqual(settled.picImrWitness,baseline.final.picImrWitness);','').replace('picImrWitness:settled.picImrWitness,','').replace('UNQUALIFIED_ABI4_PIC_IMR_NATIVE_CANDIDATE','UNQUALIFIED_ABI4_IN8_NATIVE_CANDIDATE');assert.equal(s,old);});
let runtime;
function earlyFixture(){runtime??=sourceIdentity();const original=Object.fromEntries(Object.entries(runtime.hashes).filter(([p])=>!supportAssets.includes(p)));assert.equal(Object.keys(original).length,111);const old103=Object.fromEntries(Object.entries(original).filter(([p])=>!candidateAssets.includes(p)));const derive=deriveOwnedPicImrRuntime(),tooling={revision:runtime.revision,hashes:Object.fromEntries(supportAssets.slice(0,3).map(p=>[p,runtime.hashes[p]]))};const profile={kind:'PIC_IMR_FIXED_FREE_ROM',sourceRevision:'a6f605280f778b2bc409ef97ac3b40e15874530c',sourceCount:111,romSha256:ROM,expectedPicWitness:[255,255]};return {manifest:{sourceHashes:original,tooling,profile,ownedClock:{runtimeSha256:sha(derive.bytes)},originalIn8Provenance:{ownedClock:{runtimeSha256:derive.baseSha256},sourceHashes:old103}},receipt:{tooling,profile},old103};}
for(const [name,mutate]of [['old103 manifest',f=>f.manifest.sourceHashes=f.old103],['wrong ROM',f=>f.manifest.profile.romSha256='0'.repeat(64)],['wrong witness',f=>f.manifest.profile.expectedPicWitness[0]=1],['wrong tooling hash',f=>f.manifest.tooling.hashes[supportAssets[0]]='0'.repeat(64)],['wrong tooling revision',f=>f.manifest.tooling.revision='0'.repeat(40)],['old initializer',f=>f.manifest.ownedClock.runtimeSha256=f.manifest.originalIn8Provenance.ownedClock.runtimeSha256]])test('build metadata rejects '+name+' before reading nonexistent prepared tree/addon',()=>{const f=earlyFixture();mutate(f);const d=mkdtempSync(join(tmpdir(),'bw-pic-profile-deny-'));try{const m=JSON.stringify(f.manifest),r=JSON.stringify(f.receipt);writeFileSync(d+'/manifest.json',m);writeFileSync(d+'/receipt.json',r);assert.throws(()=>authenticateBuild({preparedManifest:d+'/manifest.json',preparedManifestSha256:sha(m),buildReceipt:d+'/receipt.json',buildReceiptSha256:sha(r),addon:'/must-not-read-addon',sha256:'a'.repeat(64)},runtime),e=>!String(e).includes('ENOENT')&&!String(e).includes('must-not-read'));}finally{rmSync(d,{recursive:true,force:true});}});
test('known old PIT addon denied before any manifest/prepared/addon read',()=>{runtime??=sourceIdentity();assert.throws(()=>authenticateBuild({sha256:'8d9c83fcc3c42c2c94d17782ae42c152c52fcb2e833c31decc4bfee2af5aa841'},runtime),/known old PIT addon/);});
