import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from 'node:fs';import {checkBootstrap}from '../scripts/bochs-cpu3-native-owned-main/bootstrap.mjs';
const entry=new URL(import.meta.url),argv=['node',entry.pathname];
test('trusted direct bootstrap accepts bounded heap only',()=>checkBootstrap(entry,argv,['--max-old-space-size=512'],{}));
for(const k of ['NODE_OPTIONS','NODE_PATH','LD_PRELOAD','LD_AUDIT'])test('deny '+k,()=>assert.throws(()=>checkBootstrap(entry,argv,[],{[k]:'hostile'})));
for(const x of ['--require=x','--import=x','--loader=x','--inspect','--max-old-space-size=8192'])test('deny executable flag '+x,()=>assert.throws(()=>checkBootstrap(entry,argv,[x],{})));
test('deny imported entry',()=>assert.throws(()=>checkBootstrap(entry,['node',new URL('../package.json',entry).pathname],[],{})));
test('local scheduler source retains all observable stages and snapshots',()=>{const s=readFileSync(new URL('../scripts/run-i80386-native-owned-main.mjs',entry),'utf8');assert.ok(s.indexOf('authenticateBuild(input,source)')<s.indexOf('createRequire(import.meta.url)(addonPath)'));assert.match(s,/provider.stage\(\);if\(staged.changed\)setIRQ\(staged.asserted\);provider.begin\(\)/);assert.match(s,/try\{result=resume\(n,q,d\);\}finally\{provider.end\(\);\}/);assert.match(s,/\[177,183,80183,80187,100667,100681\]/);assert.ok(!s.includes('JSON.parse(await handle.resume'));assert.ok(!s.includes('new Worker'));});

test('actual historical439 request/return ledger scheduler and6cuts with mocks only',()=>{
 const source=readFileSync(new URL('../scripts/run-i80386-native-owned-main.mjs',entry),'utf8'),f=JSON.parse(readFileSync(new URL('./fixtures/i80386-owned-main-scheduler.json',entry),'utf8'));assert.equal(f.entries.length,439);assert.equal(f.returns.length,439);
 const handleSource=source.slice(source.indexOf('const handle={'),source.indexOf('const checkpoints=[];'));
 const loop=source.slice(source.indexOf(' for(let i=0;i<160001;i++){'),source.indexOf(' const executionNs='));
 let ordinal=0,snapshots=0;const events=[],provider={stage(){events.push('stage');return {changed:false};},begin(){events.push('begin');},end(){events.push('end');},checkpoint(){events.push('checkpoint');return {};}};
 function resume(n,q,d){events.push('resume');assert.deepEqual([n,q],f.entries[ordinal]);assert.equal(d,0xffffffffffffffffn);const [N,Q,reason,chargedNativeTicks,chargedQuanta]=f.returns[ordinal++],state=Array(20).fill(0),cut=f.cuts.find(x=>x[0]===Q);if(cut){state[8]=cut[1];state[13]=cut[2];}snapshots++;return {nativeTicks:BigInt(N),successfulQuanta:BigInt(Q),reason,chargedNativeTicks,chargedQuanta,state};}
 const run=new Function('assert','provider','resume','setIRQ','targets',`let closed=false,terminalLocal=false;${handleSource}const checkpoints=[];let target=0,final,resumes=0,terminal=false;${loop}return {checkpoints,target,resumes,terminal};`);
 const result=run(assert,provider,resume,()=>assert.fail('unexpected IRQ inmock'),f.cuts.map(([q,eip,cs],i)=>({q,name:String(i),cpu:{eip,cs}})));assert.equal(result.resumes,439);assert.equal(snapshots,439);assert.equal(result.target,6);assert.equal(result.terminal,true);assert.equal(result.checkpoints.length,6);assert.equal(events.filter(x=>x==='checkpoint').length,6);const nativeEvents=events.filter(x=>x!=='checkpoint');for(let i=0;i<439;i++)assert.deepEqual(nativeEvents.slice(i*4,i*4+4),['stage','begin','resume','end']);
});

function mockedHandle(resume){const source=readFileSync(new URL('../scripts/run-i80386-native-owned-main.mjs',entry),'utf8'),body=source.slice(source.indexOf('const handle={'),source.indexOf('const checkpoints=[];'));const events=[];const provider={stage(){events.push('stage');return {changed:true,asserted:true};},begin(){events.push('begin');},end(){events.push('end');},checkpoint(){return {};},terminal(){return {state:{marker:'RPGH001'}};},close(){events.push('close');}};const handle=new Function('assert','provider','resume','setIRQ','inspect','close','closeSync','fd','digest','rows','bytes',`let closed=false,terminalLocal=false;${body}return handle;`)(assert,provider,resume,()=>events.push('IRQ'),()=>({nativeTicks:100684n,successfulQuanta:100682n}),()=>events.push('native-close'),()=>events.push('fd-close'),0,{digest(){return 'hash';}},0,0);return {handle,events};}
test('native exception executes end then explicit CLI abort; no subsequent resume',()=>{const {handle,events}=mockedHandle(()=>{throw Error('native failed');});assert.throws(()=>handle.resume(600,300,'1'),/native failed/);assert.deepEqual(events,['stage','IRQ','begin','end']);handle.abort();assert.throws(()=>handle.resume(600,300,'1'));});
for(const [n,q,d]of [[0,300,'1'],[601,300,'1'],[600,0,'1'],[600,301,'1'],[600,300,'18446744073709551616'],[600,300,'-1']])test('invalid resume before chip/native effects '+[n,q,d],()=>{const {handle,events}=mockedHandle(()=>assert.fail('native'));assert.throws(()=>handle.resume(n,q,d));assert.deepEqual(events,[]);});
test('terminal gate denies early close, repeat resume and close',()=>{const {handle,events}=mockedHandle(()=>({reason:4,chargedNativeTicks:0,chargedQuanta:0}));assert.throws(()=>handle.close());handle.resume(600,300,'1');assert.throws(()=>handle.resume(600,300,'1'));handle.close();assert.throws(()=>handle.close());assert.deepEqual(events,['stage','IRQ','begin','end','native-close','close','fd-close']);});

const {validateInput,authenticateConfiguration}=await import('../scripts/bochs-cpu3-native-owned-main/admission.mjs');
const valid={addon:'/held.node',sha256:'144f3af7b906e46bfb68c10b991fef15847d81c60e7bb44820ee73653e723818',configuration:'/config',baseline:'/baseline',output:'/output',preparedManifest:'/prepare',preparedManifestSha256:'7092cf5efdb3d68b65e2b4b8a91f726ae07516e8df0de4712eeb8c92c7369c28',buildReceipt:'/receipt',buildReceiptSha256:'acebb536e93e6e74218057f18ae1e5a47d8f436e7aee212c0d82b8658d4e3da8',hostJournal:false,nativeTrace:false};
test('data-only exact input accepts fixed artifact identity without reading addon',()=>assert.equal(validateInput(valid),valid));
for(const [name,mutate]of Object.entries({manifest:x=>x.preparedManifestSha256='a'.repeat(64),receipt:x=>x.buildReceiptSha256='b'.repeat(64),extra:x=>x.profile=true,bool:x=>x.nativeTrace=1,path:x=>x.addon='relative.node',nul:x=>x.configuration='/bad\0',sha:x=>x.sha256='c'.repeat(64),missing:x=>delete x.buildReceiptSha256})){test('input denial '+name,()=>{const x={...valid};mutate(x);assert.throws(()=>validateInput(x));});}
test('configuration corruption rejected without addon read/load',async()=>{const {mkdtempSync,writeFileSync,rmSync}=await import('node:fs'),{tmpdir}=await import('node:os');const dir=mkdtempSync(tmpdir()+'/owned-main-config-');try{writeFileSync(dir+'/config','display_library: arbitrary\n');assert.throws(()=>authenticateConfiguration(dir+'/config'));}finally{rmSync(dir,{recursive:true});}});
