import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {writeFileSync} from 'node:fs';
import {layout,entries,gate,selector,faultEip,terminalEip,handlerEip,ramInstructions,ramProgram,romInstructions,bootStores,frameStores,repairStore,retryStore,ordinaryStores,adTransitions,fixedPageFaultRom,pageFaultProfile,namedCuts,afterSs,afterSp,afterPg,farJumpIp,lgdtIp,lidtIp,spWriteIp,physicalFetch,validateStore,validateAdTransition,expectedPages,wordAt,codeCache,dataCache,validateLedger,validateMilestone} from '../scripts/bochs-cpu3-native-paged-pagefault/profile.mjs';
import {createPagedPageFaultOracle} from '../scripts/bochs-cpu3-native-paged-pagefault/reference.mjs';
test('fixed source ROM and RAM instructions prove vector14 gate, handler CR3 reload and error discard encodings',()=>{
 const rom=fixedPageFaultRom();assert.throws(()=>fixedPageFaultRom({rom}));assert.equal(rom.length,65536);assert.equal(createHash('sha256').update(rom).digest('hex'),pageFaultProfile.romSha256);let ip=0x100;
 for(const i of romInstructions){assert.equal(i.ip,ip);assert.deepEqual([...rom.subarray(ip,ip+i.bytes.length)],i.bytes);ip+=i.bytes.length;}assert.ok(ip<0x400);assert.deepEqual([...rom.subarray(0xfff0,0xfff5)],[0xea,0,1,0,0xf0]);assert.deepEqual([...rom.subarray(0x400,0x40c)],[31,0,0,6,0,0,0x77,0,0,0x30,0,0]);
 assert.deepEqual(romInstructions.find(i=>i.ip===lgdtIp).bytes,[0x2e,0x0f,1,0x16,0,4]);assert.deepEqual(romInstructions.find(i=>i.ip===lidtIp).bytes,[0x2e,0x0f,1,0x1e,6,4]);assert.equal(afterSs,spWriteIp);assert.equal(afterPg,farJumpIp);assert.ok(afterSp<afterPg);
 const p=expectedPages(bootStores);assert.equal(bootStores.length,31);assert.equal(ramProgram.length,52);for(const i of ramInstructions)assert.deepEqual([...p.code.subarray(i.ip-0x7000,i.ip-0x7000+i.bytes.length)],i.bytes);assert.deepEqual([...p.code.subarray(0,ramProgram.length)],ramProgram);assert.equal(p.code[terminalEip-0x7000],0xf4);
 assert.deepEqual(ramInstructions.find(i=>i.ip===faultEip).bytes,[0xa3,0,0x80]);assert.deepEqual(ramInstructions.find(i=>i.ip===handlerEip).bytes,[0x66,0xc7,6,0x20,0x20,3,0xb0,0,0]);assert.deepEqual(ramInstructions.find(i=>i.ip===0x7029).bytes,[0x0f,0x20,0xda]);assert.deepEqual(ramInstructions.find(i=>i.ip===0x702c).bytes,[0x0f,0x22,0xda]);assert.deepEqual(ramInstructions.find(i=>i.ip===0x702f).bytes,[0x83,0xc4,2]);assert.deepEqual(ramInstructions.find(i=>i.ip===0x7032).bytes,[0xcf]);
 assert.equal(gate.raw,0x3000+14*8);assert.equal(gate.limit,14*8+7);assert.deepEqual([...p.idt.subarray(0x70,0x78)],[0x20,0x70,0x18,0,0,0x86,0,0]);for(const e of Object.values(entries))assert.equal(wordAt(e.raw<0x2000?p.directory:p.table,e.raw&4095),e.value);assert.equal(wordAt(p.table,0x20),0);assert.deepEqual([...p.data.subarray(0,4)],[0x78,0x56,0x9a,0xbc]);
});
test('physical fetch accepts only encoded instructions and rejects poison aliases and HLT',()=>{
 assert.equal(physicalFetch(0xf000,0xffff0000,0xfff0),0xfffffff0);assert.equal(physicalFetch(0xf000,0xf0000,farJumpIp),0xf0000+farJumpIp);for(const i of ramInstructions)assert.equal(physicalFetch(selector,0,i.ip),layout.code+i.ip-0x7000);
 for(const args of [[selector,0x7000,0x7000],[0x10,0,0x7000],[selector,0,terminalEip],[selector,0,0x7021],[0xf000,0xffff0000,farJumpIp],[selector,0,-1]])assert.throws(()=>physicalFetch(...args));
});
test('ordered real frame, ordinary PTE repair and once-only retry store owners refuse changed address phase and byte',()=>{
 for(const [i,e]of ordinaryStores.entries()){assert.equal(validateStore(i,e.raw,e.bytes,e.cs,e.ip),i+1);for(const a of [[e.raw+1,e.bytes,e.cs,e.ip],[e.raw,e.bytes,e.cs,e.ip+1],[e.raw,e.bytes,e.cs^1,e.ip],[e.raw,e.bytes.map((v,k)=>k?v:v^1),e.cs,e.ip]])assert.throws(()=>validateStore(i,...a));}
 assert.deepEqual(frameStores.map(e=>[e.raw,e.bytes]),[[0xcff8,[2,0]],[0xcffa,[3,0x70]],[0xcffc,[24,0]],[0xcffe,[2,0]]]);assert.equal(repairStore.raw,0x2020);assert.deepEqual(repairStore.bytes,[3,0xb0,0,0]);assert.equal(retryStore.raw,0xb000);assert.throws(()=>validateStore(ordinaryStores.length,retryStore.raw,retryStore.bytes,selector,faultEip));assert.throws(()=>validateStore(bootStores.length,retryStore.raw,retryStore.bytes,selector,faultEip));
});
test('exact JS A/D sources distinguish repair table writes and retried data dirtiness while code stays clean',()=>{
 for(const [i,e]of adTransitions.entries()){assert.equal(validateAdTransition(i,e.raw,e.before,e.after,e.cs,e.ip),e.kind);for(const a of [[i,e.raw+4,e.before,e.after,e.cs,e.ip],[i,e.raw,e.before^1,e.after,e.cs,e.ip],[i,e.raw,e.before,e.after^0x40,e.cs,e.ip],[i,e.raw,e.before,e.after,e.cs,e.ip+1],[i+1,e.raw,e.before,e.after,e.cs,e.ip]])assert.throws(()=>validateAdTransition(...a));}
 const p=expectedPages(ordinaryStores,adTransitions);for(const [off,w]of [[0,0x23],[8,0x2063],[12,0x3023],[28,0xa023],[32,0xb063],[52,0xc063],[0x3c0,0xf0023]])assert.equal(wordAt(p.table,off),w);assert.equal(wordAt(p.directory,0),0x2023);assert.deepEqual([...p.data.subarray(0,4)],[0x34,0x12,0x9a,0xbc]);assert.deepEqual([...p.aliasData.subarray(0,4)],[0xad,0xde,0xef,0xbe]);
});
const manufactured=()=>({q:40,attemptOrdinal:41,faultSerial:1,deliveries:[{attemptOrdinal:31,q:30,vector:14,returnEip:faultEip,errorCode:2,fault:true,cr2:0x8000,cs:selector,eip:handlerEip,esp:0xdff8,eflags:2}],cpu:{cs:selector,eip:terminalEip,cr0:0xfffffff1,cr2:0x8000,cr3:0x1000,cr4:0,eflags:2,halted:false,ds:0x10,ss:0x10,eax:0x80001234,ecx:0x1234,edx:0x1000,esp:0xe000,gdtr:{base:0x600,limit:31},idtr:{base:0x3000,limit:0x77},segmentCaches:{1:structuredClone(codeCache),2:structuredClone(dataCache),3:structuredClone(dataCache)},interruptShadow:0,nmiShadow:0,debugShadow:0},stores:ordinaryStores,updates:adTransitions,pages:expectedPages(ordinaryStores,adTransitions)});
test('manufactured terminal and zero-completion ledger refuse duplicate fault charge missing repair wrong cache or any page byte',()=>{
 const s=manufactured();assert.equal(validateMilestone('readback-before-HLT',s),'readback-before-HLT');assert.equal(validateLedger({attemptOrdinal:0,q:0,faultSerial:0,deliveries:[]}),0);
 for(const patch of [{eax:0x1234},{cr2:0},{esp:0xdff8},{eflags:0x86},{cr3:0},{cr4:16},{interruptShadow:1},{ecx:0x5678}])assert.throws(()=>validateMilestone('readback-before-HLT',{...s,cpu:{...s.cpu,...patch}}));for(const patch of [{q:41},{faultSerial:2},{attemptOrdinal:42},{deliveries:[]}])assert.throws(()=>validateLedger({...s,...patch}));
 for(const k of Object.keys(layout)){const b=structuredClone(s);b.pages[k][4095]^=1;assert.throws(()=>validateMilestone('readback-before-HLT',b));}for(const k of [1,2,3]){const b=structuredClone(s);b.cpu.segmentCaches[k].default32=true;assert.throws(()=>validateMilestone('readback-before-HLT',b));}const noRepair=structuredClone(s);noRepair.stores.splice(bootStores.length+4,1);assert.throws(()=>validateMilestone('readback-before-HLT',noRepair));const wrongFrame=structuredClone(s);wrongFrame.pages.stack[0xff8]=0;assert.throws(()=>validateMilestone('readback-before-HLT',wrongFrame));assert.throws(()=>validateMilestone('unknown',s));
});
test('private no-arg factory reset stage returns detached pages and refuses early settle',async()=>{
 await assert.rejects(createPagedPageFaultOracle({gate}));const o=await createPagedPageFaultOracle();try{const s=o.checkpoint();assert.equal(s.q,0);assert.equal(s.attemptOrdinal,0);assert.equal(s.faultSerial,0);assert.equal(o.milestone(),'reset');assert.deepEqual(o.stage(),{asserted:false,changed:false});assert.deepEqual(o.checkpoint(),s);s.pages.stack[0]=255;assert.equal(o.checkpoint().pages.stack[0],0);assert.throws(()=>o.settle());}finally{o.close();}assert.throws(()=>o.step());
});
test('bounded actual private JS page fault repair CR3 reload IRET and once-only retry retains genuine effects',async()=>{
 const o=await createPagedPageFaultOracle();try{const frames=[],cuts=[];for(let i=0;i<=pageFaultProfile.maxAttempts;i++){const s=o.checkpoint();frames.push(s);const name=o.milestone();if(name)cuts.push({name,q:s.q,attemptOrdinal:s.attemptOrdinal,faultSerial:s.faultSerial});if(name==='readback-before-HLT')break;o.stage();o.step();}
  const end=o.checkpoint();assert.equal(end.attemptOrdinal,1+romInstructions.length+ramInstructions.length+1);assert.equal(end.q,end.attemptOrdinal-1);assert.equal(frames.length,end.attemptOrdinal+1);assert.deepEqual(cuts.map(c=>c.name),namedCuts.map(c=>c.name));assert.equal(end.deliveries.length,1);assert.equal(end.reloads.length,1);assert.equal(end.stores.length,ordinaryStores.length);assert.equal(end.updates.length,11);assert.throws(()=>o.step());
  const before=frames.find(s=>s.cpu.cs===selector&&s.cpu.eip===faultEip&&s.faultSerial===0),fault=frames.find(s=>s.cpu.cs===selector&&s.cpu.eip===handlerEip);assert.equal(fault.q,before.q);assert.equal(fault.attemptOrdinal,before.attemptOrdinal+1);assert.equal(fault.board.cycles,before.board.cycles);assert.deepEqual([...fault.pages.data.subarray(0,4)],[0x78,0x56,0x9a,0xbc]);assert.deepEqual([...fault.pages.stack.subarray(0xff8)],[2,0,3,0x70,24,0,2,0]);const failed=fault.attempts.at(-1);assert.deepEqual([failed.completed,failed.faultDelivered,failed.result,failed.returnedEip],[0,true,0,handlerEip]);
  assert.equal(end.attempts.filter(a=>a.cs===selector&&a.eip===faultEip).length,2);assert.equal(end.attempts.filter(a=>a.faultDelivered).length,1);const disc=frames.find(s=>s.cpu.cs===selector&&s.cpu.eip===0x7032);assert.equal(disc.cpu.esp,0xdffa);assert.equal(disc.cpu.eflags,0x86);const retr=frames.find(s=>s.cpu.cs===selector&&s.cpu.eip===faultEip&&s.faultSerial===1);assert.equal(retr.cpu.esp,0xe000);assert.equal(retr.cpu.eflags,2);
  const settled=o.settle();assert.deepEqual(settled.cpu,end.cpu);assert.equal(settled.board.debt,0);const reads=settled.accesses.filter(a=>a.cs===selector&&a.eip===0x7032&&a.raw>=0xcffa&&a.raw<0xd000);assert.deepEqual(reads.map(a=>[a.raw,a.value]),[[0xcffa,3],[0xcffb,0x70],[0xcffc,24],[0xcffd,0],[0xcffe,2],[0xcfff,0]]);
  for(const page of [layout.aliasCode,layout.aliasData,layout.aliasStack])assert.equal(settled.accesses.some(a=>a.cs===selector&&a.raw>=page&&a.raw<page+4096),false);assert.equal(settled.stores.filter(e=>e.cs===selector&&e.raw===layout.data).length,1);
  if(process.env.BW_PAGED_PF_CONTROL_OUTPUT)writeFileSync(process.env.BW_PAGED_PF_CONTROL_OUTPUT,JSON.stringify({schema:'bw.paged-pagefault.js-source-control.v1',scope:'Actual private JS model only; no native PF admission',romSha256:pageFaultProfile.romSha256,frames,cuts,settled},(_,v)=>v instanceof Uint8Array?[...v]:v)+'\n',{flag:'wx'});
  console.log(JSON.stringify({scope:'tiny actual private JS PF source control',attempts:end.attemptOrdinal,q:end.q,cuts,stores:end.stores.length,updates:end.updates.length,ramSha256:settled.ramSha256}));
 }finally{o.close();}
});
