/** Explicitly manufactured source-control states; no factory, instruction or addon execution. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {sha,relativeImports,compiledRevision,ownedBuildBinding,requireReadyBuild,requireReadyBinding,validateBuildBinding} from '../scripts/bochs-cpu3-native-protected-stack/driver-auth.mjs';
import {deriveDriverProvider,profileProviderSha256} from '../scripts/bochs-cpu3-native-protected-stack/driver-provider.mjs';
import {deriveProtectedStackProvider} from '../scripts/bochs-cpu3-native-protected-stack/provider-derivation.mjs';
import {deriveStackComparison,comparisonParentSha256} from '../scripts/bochs-cpu3-native-protected-stack/cpu-comparison.mjs';
import {compareBoundary,stackProgress,validateMilestones,wholeNativeWords} from '../scripts/bochs-cpu3-native-protected-stack/parity.mjs';
import {validateInput,finalizeAuthentication} from '../scripts/bochs-cpu3-native-protected-stack/runner.mjs';
import {namedCuts,bootStores,stackStores,expectedPages,expectedCache} from '../scripts/bochs-cpu3-native-protected-stack/profile.mjs';
const copy=x=>structuredClone(x);
const stackCount=name=>['after-PUSH','after-POP'].includes(name)?1:['entered-CALL','callee-MOV','returned-CALL','before-HLT'].includes(name)?2:0;
function fixture(name='before-HLT',q=30){
 const cut=namedCuts.find(c=>c.name===name);assert.ok(cut);const protectedMode=cut.cs===0x18,dsLoaded=protectedMode&&name!=='entered-protected-RAM',ssLoaded=dsLoaded&&name!=='after-DS-load',sc=stackCount(name),effects=name==='reset'?[]:[...bootStores,...stackStores.slice(0,sc)],pages=expectedPages(effects);
 const j={eax:['callee-MOV','returned-CALL','before-HLT'].includes(name)?0xabcd:1,ecx:name==='before-HLT'?0x5678:0,edx:0,ebx:sc?0x1234:0,esp:['after-PUSH','entered-CALL','callee-MOV'].includes(name)?0x8ffe:['stack-ready','after-POP','returned-CALL','before-HLT'].includes(name)?0x9000:0,ebp:0,esi:0,edi:0,eip:cut.eip,eflags:2,cr0:name==='reset'||name==='after-LGDT'?0x7ffffff0:0x7ffffff1,cr2:0,cr3:0,cr4:0,cs:cut.cs,ds:dsLoaded?0x10:0,ss:ssLoaded?0x10:0,es:0,fs:0,gs:0,pc:(name==='reset'?0xffff0000:protectedMode?0:0xf0000)+cut.eip>>>0,gdtr:name==='reset'?{base:0,limit:0xffff}:{base:0x600,limit:0x1f},idtr:{base:0,limit:0xffff},ldtr:{selector:0,base:0,limit:0xffff,present:true,type:2},tr:{selector:0,base:0,limit:0xffff,present:true,type:11},segmentCaches:Array.from({length:6},()=>({base:0,limit:0xffff,default32:false,present:true})),debugRegisters:[0,0,0,0,0,0,0xffff1ff0,0x400],halted:false,shutdown:false,interruptShadow:name==='after-SS-load'?1:0,nmiShadow:name==='after-SS-load'?1:0,debugShadow:0};
 j.segmentCaches[1]=protectedMode?expectedCache(0x18):{base:name==='reset'?0xffff0000:0xf0000,limit:0xffff,default32:false,present:true};if(dsLoaded)j.segmentCaches[3]=expectedCache(0x10);if(ssLoaded)j.segmentCaches[2]=expectedCache(0x10);
 const n={state:['eax','ecx','edx','ebx','esp','ebp','esi','edi','eip','eflags','cr0','cr2','cr3','cs','ds','ss'].map(k=>j[k]).concat(j.gdtr.base,j.gdtr.limit,j.idtr.base,j.idtr.limit),extra:Array(20).fill(0),segments:Array(90).fill(0),system:Array(30).fill(0),debug:[0,0,0,0,0xffff1ff0,0x400],nativeTicks:q,successfulQuanta:q,mappingEpoch:0,boardA20:1,activityState:0,chargedNativeTicks:1,chargedQuanta:1,reason:1,execution:{attempts:q,completed:q,repIterations:0,repPartial:0,faults:0,portCommits:0,irqDeliveries:0,haltIdleCuts:0},fallback:{bochsRamReads:0,bochsRamWrites:0,bochsDirectPointers:0,bochsPio:0,bochsTimer:0}};
 for(const [i,key]of ['es','cs','ss','ds','fs','gs'].entries()){const selector=j[key],cache=j.segmentCaches[i],valid=i===2&&ssLoaded&&sc?7:1,type=i===1&&protectedMode?11:3;n.segments.splice(i*15,15,i,selector,selector>>>3,0,0,valid,1,0,1,type,cache.base>>>0,cache.limit,0,0,0);}
 n.extra[0]=j.debugRegisters[6];n.extra[1]=j.debugRegisters[7];n.extra.splice(2,3,j.es,j.fs,j.gs);n.extra.splice(5,3,...n.segments.slice(17,20));n.extra[9]=1;n.extra[13]=j.segmentCaches[1].base>>>0;n.extra[14]=0xffff;
 for(let i=0;i<2;i++){n.system[i*15]=i+6;n.system[i*15+6]=1;n.system[i*15+9]=i?11:2;n.system[i*15+11]=0xffff;}
 const board={board:{cycles:4+6*q,debt:q?6:0,deadline:6000,a20Enabled:true},successfulQuanta:q,mappingEpoch:0,generations:name==='reset'?[]:[[0,4],[0x7000,7],...(sc?[[0x8000,sc]]:[])],ram:{bootStores:Math.min(effects.length,11),storeCount:effects.length,admitted:protectedMode&&name!=='entered-protected-RAM',writes:effects.map((w,i)=>({raw:w.raw,bytes:[...w.bytes],generation:i<4?i+1:i<11?i-3:i-10}))}};
 return {n,board,js:{q,cpu:j,board:copy(board.board),pages:copy(pages),stores:effects.map(w=>({...w,bytes:[...w.bytes]}))},pages};
}
test('three copied pages and exact CR0 scope derivative authenticate parents/inverses',()=>{
 const p=deriveDriverProvider(deriveProtectedStackProvider().bytes);assert.equal(p.parentSha256,profileProviderSha256);for(const key of ['ramPages()','gdt:Uint8Array.from','stack:Uint8Array.from'])assert.ok(p.bytes.includes(key));assert.throws(()=>deriveDriverProvider(Buffer.from('unknown')));
 const c=deriveStackComparison(readFileSync(new URL('../scripts/bochs-cpu3-native-cold-bios/parity.mjs',import.meta.url)));assert.equal(c.baseSha256,comparisonParentSha256);assert.ok(c.bytes.includes('j.eip===0x175'));assert.throws(()=>deriveStackComparison(Buffer.from('unknown')));
 assert.ok(relativeImports(readFileSync(new URL('../src/i8086-machine.js',import.meta.url))).includes('./machine-checkpoint.js'));assert.deepEqual(relativeImports(Buffer.from(`const q="import {x} from './foreign.js'";\nexport {\n x\n} from './actual.js';`)),['./actual.js']);
});
test('represented CPU, strict CS/DS/SS rows and three whole pages refuse distinct mutations',()=>{
 const f=fixture();compareBoundary(f.n,f.board,f.js,f.pages);assert.equal(wholeNativeWords(f.n).length,166);
 for(const change of [x=>x.n.state[0]=2,x=>x.n.state[10]=0x7ffffff0,x=>x.n.state[9]=0x802,x=>x.n.segments[20]=3,x=>x.n.segments[47]=3,x=>x.n.segments[50]=7,x=>x.n.segments[35]=1,x=>x.n.segments[39]=2,x=>x.n.system[11]=0,x=>x.n.debug[0]=1,x=>x.n.mappingEpoch=1,x=>x.n.boardA20=0,x=>x.board.board.debt=0,x=>x.pages.code[3000]=1,x=>x.pages.gdt[4095]=1,x=>x.pages.stack[0]=1,x=>x.js.stores[0].raw=0x614,x=>x.js.cpu.cr4=1,x=>x.board.ram.storeCount=12]){const x=copy(f);change(x);assert.throws(()=>compareBoundary(x.n,x.board,x.js,x.pages));}
 const shadow=fixture('after-SS-load',22);compareBoundary(shadow.n,shadow.board,shadow.js,shadow.pages);for(const change of [x=>x.js.cpu.interruptShadow=0,x=>x.js.cpu.nmiShadow=0,x=>x.js.cpu.debugShadow=1,x=>x.n.segments[35]=7]){const x=copy(shadow);change(x);assert.throws(()=>compareBoundary(x.n,x.board,x.js,x.pages));}
 const cleared=fixture('stack-ready',23);compareBoundary(cleared.n,cleared.board,cleared.js,cleared.pages);cleared.js.cpu.interruptShadow=1;assert.throws(()=>compareBoundary(cleared.n,cleared.board,cleared.js,cleared.pages));
});
test('independent progress refuses caps, fallback, IRQ, REP, HLT and missing counters',()=>{
 const n=fixture('before-HLT',1).n;assert.deepEqual(stackProgress({n:0,q:0},n),{n:1,q:1,dn:1,dq:1});for(const change of [x=>x.nativeTicks=513,x=>x.successfulQuanta=513,x=>x.chargedQuanta=0,x=>x.activityState=1,x=>x.reason=4,x=>x.fallback={},x=>x.fallback.bochsDirectPointers=1,x=>x.execution.irqDeliveries=1,x=>x.execution.repIterations=1,x=>delete x.execution.portCommits]){const x=copy(n);change(x);assert.throws(()=>stackProgress({n:0,q:0},x));}const zero={...copy(n),chargedNativeTicks:0,chargedQuanta:0,reason:7};assert.equal(stackProgress({n:1,q:1},zero).dq,0);
});
function manufacturedCuts(){const qs=[0,16,18,19,21,22,23,25,26,27,28,29,30];return namedCuts.map((c,i)=>{const f=fixture(c.name,qs[i]);return {name:c.name,q:qs[i],native:f.n,board:f.board,javascript:f.js,pages:f.pages};});}
test('manufactured thirteen cuts bind both descriptors, stack words, generations and shadow phase',()=>{
 const cuts=manufacturedCuts();assert.equal(validateMilestones(cuts).milestones,13);
 for(const change of [x=>x.pop(),x=>x.reverse(),x=>x[4].q=19,x=>x[3].board.ram.admitted=true,x=>x[4].board.ram.admitted=false,x=>x[4].native.segments[50]=3,x=>x[5].native.segments[35]=7,x=>x[7].native.segments[35]=1,x=>x[5].javascript.cpu.interruptShadow=0,x=>x[6].javascript.cpu.nmiShadow=1,x=>x[7].pages.stack[0xffe]=0,x=>x[9].pages.stack[0xfff]=0,x=>x[10].javascript.cpu.eax=1,x=>x[12].javascript.cpu.ecx=0,x=>x[1].pages.gdt[0x615]=0x91,x=>x[7].board.ram.writes[11].generation=2,x=>x[9].board.generations[2][1]=1]){const x=copy(cuts);change(x);assert.throws(()=>validateMilestones(x));}
});
test('owned static stack authority and manufactured pending/old-profile refusals stay closed',()=>{
 const b=ownedBuildBinding();assert.equal(b.status,'ROOT_REVIEWED_STACK_NATIVE_BUILD');assert.equal(b.compiledRevision,compiledRevision);assert.equal(Object.keys(b.compiledFiles).length,174);assert.equal(b.addonSha256,'4076aca36f5d7e79eb7cdd829746fd35edd852cd407d5c6eab905f7c1799b439');assert.equal(b.buildRun,37186044543);assert.equal(b.artifactId,11296324286);assert.deepEqual(requireReadyBuild(),b);assert.throws(()=>validateInput({}));
 const pending={...copy(b),status:'PENDING_STACK_NATIVE_BUILD',addonSha256:null,buildRun:null,artifactId:null,staticAuthority:null};validateBuildBinding(pending);assert.throws(()=>requireReadyBinding(pending),/pending/);assert.throws(()=>validateBuildBinding({...pending,staticAuthority:b.staticAuthority}));
 for(const change of [x=>x.compiledRevision='f'.repeat(40),x=>x.compiledSourceSha256='0'.repeat(64),x=>delete x.compiledFiles['package.json'],x=>x.compiledFiles['package.json']='0'.repeat(64),x=>x.status='READY',x=>x.addonSha256=null,x=>x.generated['bochs/owned-protected-stack-ROM.bin']='0'.repeat(64),x=>x.generated['bochs/owned-protected-ram-ROM.bin']='0'.repeat(64),x=>x.staticAuthority={},x=>x.staticAuthority.artifactZipBytes=0]){const x=copy(b);change(x);assert.throws(()=>validateBuildBinding(x));}
 for(const h of ['98c7d11961463ae8a4dfbd108cf94d1e745f09f5d7684afa3bc31792cdac203e','9475b94b4dd067bc6c25ccd7c61c60cef5c9696fba0725ed05913838a3ee9873','40179a4f0bc2456e59bc2ea49303e17e29be72ef564adb1fe1a6879abb015ab0'])assert.throws(()=>validateBuildBinding({...b,addonSha256:h}));
});
test('all-outcome source/input/config/tool checks preserve first failure and reject final mutation',()=>{
 const pins={input:'a',driver:{revision:'b'},compiled:{revision:'c'},build:{sha:'d'},configuration:{sha:'e'},node:'f'};assert.equal(finalizeAuthentication({status:'PASS'},null,pins,copy(pins)),null);for(const k of Object.keys(pins)){const after=copy(pins);after[k]='changed';const primary=Error('manufactured first divergence'),r={status:'FAIL',error:String(primary)};assert.equal(finalizeAuthentication(r,primary,pins,after),primary);assert.match(r.error,/first divergence/);assert.match(r.finalAuthenticationError,/final /);}const r={status:'PASS'},failure=Error('manufactured config read failure');assert.equal(finalizeAuthentication(r,null,pins,{},failure),failure);assert.equal(r.status,'FAIL');
});
test('driver source identity authenticates clean HEAD and includes owned build asset in owned alternate fixture',()=>{
 const root=fileURLToPath(new URL('../',import.meta.url)),revision=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),paths=new Set();
 const seeds=['scripts/bochs-cpu3-native-protected-stack/runner.mjs','scripts/bochs-cpu3-native-protected-stack/DRIVER-SOURCE.md','scripts/bochs-cpu3-native-protected-stack/driver-build-binding.json','scripts/bochs-cpu3-native-cold-bios/board-provider.mjs','test/i80386-protected-stack-driver-source.test.mjs','package.json','roms/free-at-bios/LICENSE','roms/free-at-bios/BIOS-bochs-legacy','roms/free-at-bios/vgabios-lgpl.bin'];
 function visit(p){if(paths.has(p))return;paths.add(p);const b=readFileSync(resolve(root,p)),g=execFileSync('git',['show',revision+':'+p],{cwd:root,maxBuffer:16<<20});assert.equal(sha(b),sha(g));if(/\.(js|mjs)$/.test(p))for(const q of relativeImports(b))visit(resolve(root,dirname(p),q).slice(root.length));}for(const p of seeds)visit(p);
 const d=mkdtempSync(join(tmpdir(),'protected-driver-clean-')),clean=join(d,'source');try{mkdirSync(clean);execFileSync('git',['init','--quiet',clean]);const objects=execFileSync('git',['rev-parse','--path-format=absolute','--git-path','objects'],{cwd:root,encoding:'utf8'}).trim();writeFileSync(join(clean,'.git/objects/info/alternates'),objects+'\n');const shallow=execFileSync('git',['rev-parse','--path-format=absolute','--git-path','shallow'],{cwd:root,encoding:'utf8'}).trim();try{writeFileSync(join(clean,'.git/shallow'),readFileSync(shallow));}catch(e){if(e.code!=='ENOENT')throw e;}execFileSync('git',['update-ref','HEAD',revision],{cwd:clean});execFileSync('git',['sparse-checkout','init','--no-cone'],{cwd:clean});execFileSync('git',['sparse-checkout','set','--no-cone','--stdin'],{cwd:clean,input:[...paths].sort().map(p=>'/'+p).join('\n')+'\n'});execFileSync('git',['checkout','--quiet','--detach',revision],{cwd:clean});const raw=execFileSync(process.execPath,['--max-old-space-size=128','--input-type=module','-e',"import {driverSourceIdentity,ownedBuildBinding} from './scripts/bochs-cpu3-native-protected-stack/driver-auth.mjs';console.log(JSON.stringify({source:driverSourceIdentity(),pending:ownedBuildBinding().status}))"],{cwd:clean,encoding:'utf8',timeout:10000,maxBuffer:2<<20});const v=JSON.parse(raw);assert.equal(v.source.revision,revision);assert.deepEqual(Object.keys(v.source.hashes).sort(),[...paths].sort());assert.ok(v.source.hashes['scripts/bochs-cpu3-native-protected-stack/driver-build-binding.json']);assert.equal(v.pending,ownedBuildBinding().status);}finally{rmSync(d,{recursive:true,force:true});}
});
