import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {deriveRamBootstrapRuntime} from '../scripts/bochs-cpu3-native-ram-bootstrap/runtime.mjs';
import {deriveProtectedRamRuntime,transformProtectedRamRuntime,runtimeParentSha256} from '../scripts/bochs-cpu3-native-protected-ram/runtime.mjs';
import {deriveProtectedRamProvider,transformProtectedRamProvider,createOwnedProtectedRamProvider} from '../scripts/bochs-cpu3-native-protected-ram/provider-derivation.mjs';
import {validateProtectedRead,validateProtectedWrite} from '../scripts/bochs-cpu3-native-protected-ram/provider-profile.mjs';
import {protectedRamProfile,stores,instructions,expectedRamPage} from '../scripts/bochs-cpu3-native-protected-ram/profile.mjs';
import {ownedAssets,generatedHashes,sourceIdentity,deriveProtectedAdmission,finalizeProtectedPreparation,validateBuildMetadata,buildReceiptSchema,requiredFeatures,requiredExports,canonicalConfiguration,authenticateConfiguration} from '../scripts/bochs-cpu3-native-protected-ram/build-identity.mjs';
import {finalizePreparation} from '../scripts/prepare-bochs-cpu3-native-cold-bios.mjs';
import {finalizeRamPreparation} from '../scripts/prepare-bochs-cpu3-native-ram-bootstrap.mjs';
import {hotNativeProfile} from '../scripts/bochs-cpu3-native-hot-direct/profile.mjs';
import {upstreamHashes} from '../scripts/bochs-cpu3-native-direct-board/patch.mjs';
import {sha256} from '../scripts/bochs-cpu3-native-owned-clock/derive.mjs';
// Manufactured metadata below is never represented as a genuine native build.
function fixture(tree='/diagnostic-protected-prepared'){
 const source={revision:'a'.repeat(40),hashes:{diagnostic:'b'.repeat(64)}};
 const h4={boardRevision:source.revision,bochsRevision:'0e45b736ef9792eb9b752b0a35db49eaf2faea47',sourceHashes:{...source.hashes},profile:hotNativeProfile,generatedRuntimeSha256:'89acf83dda501a097550e0465b4db2351229a991e51cbf8439d43bad77d4a42a',preparedTree:tree,upstreamHashes,patchedHashes:Object.fromEntries(Object.keys(upstreamHashes).map(p=>[p,'c'.repeat(64)]))};
 const cold=finalizePreparation(h4,source),ram=finalizeRamPreparation(cold,source),manifest=finalizeProtectedPreparation(ram,source);
 const input={preparedManifest:'/diagnostic-manifest.json',preparedManifestSha256:'d'.repeat(64),addon:tree+'/bochs/bw_direct.node',sha256:'e'.repeat(64)};
 const receipt={schema:buildReceiptSchema,status:'BUILD_AND_STATIC_PREFLIGHT_PASS_NO_ADDON_LOAD_OR_GUEST',protectedProfile:protectedRamProfile,sourceRevision:source.revision,sourceHashes:source.hashes,preparedHashes:generatedHashes(),preparedTree:tree,preparedManifestPath:input.preparedManifest,preparedManifestSha256:input.preparedManifestSha256,addonPath:input.addon,addonSha256:input.sha256,requiredFeatures,requiredExports};return structuredClone({source,ram,manifest,input,receipt});
}
test('protected runtime/provider derivatives pin parents, exact inverses and inherited coherence guards',()=>{
 const base=deriveRamBootstrapRuntime().bytes,c=deriveProtectedRamRuntime(),p=deriveProtectedRamProvider();assert.equal(sha256(base),runtimeParentSha256);assert.notEqual(sha256(c.bytes),runtimeParentSha256);
 for(const guard of ['current-code-write','admitted-unexecuted-code-write','page->kind==1?page->decoded:UINT32_MAX','protected-RAM-no-paging','protected-GDT-read-bytes'])assert.ok(c.bytes.includes(guard));assert.ok(c.bytes.indexOf('static bool bw_protected_store')<c.bytes.indexOf('static const uint8_t *bw_host_execute'));
 assert.ok(p.bytes.includes('owned callback lease'));assert.throws(()=>transformProtectedRamRuntime(Buffer.from('unknown')));assert.throws(()=>transformProtectedRamProvider(Buffer.from('unknown')));const corrupt=Buffer.from(base);corrupt[0]^=1;assert.throws(()=>transformProtectedRamRuntime(corrupt));assert.equal(protectedRamProfile.maxNativeTicks,512);assert.equal(protectedRamProfile.totalNativeTicks,undefined);
});
test('closed host policy refuses wrong store order/value/width/admission and nonoperand reads',()=>{
 for(const [i,e]of stores.entries()){assert.equal(validateProtectedWrite(e.raw,Uint8Array.from(e.bytes),i,false),i+1);assert.throws(()=>validateProtectedWrite(e.raw,Uint8Array.from(e.bytes),i,true));const changed=Uint8Array.from(e.bytes);changed[0]^=1;assert.throws(()=>validateProtectedWrite(e.raw,changed,i,false));}
 for(const [raw,n]of [[0x618,8],[0x61c,4],[0xf0180,6]])validateProtectedRead(raw,n);
 for(const [raw,n]of [[0x617,8],[0x61f,2],[0x7000,2],[0xf0185,2],[0xf0180,0]])assert.throws(()=>validateProtectedRead(raw,n));assert.throws(()=>validateProtectedWrite(0x7000,Uint8Array.of(0xb8,0x34),0,false));
});
test('private actual provider admits exactly four stores and generation2 page without CPU steps',async()=>{
 await assert.rejects(createOwnedProtectedRamProvider({}));const p=await createOwnedProtectedRamProvider();p.callbacks.clockTransfer(new Uint32Array(),1);p.begin();p.callbacks.clockTransfer(new Uint32Array(),2);
 assert.throws(()=>p.callbacks.admitExecutePage(0x7000));assert.throws(()=>p.callbacks.writePhysical(0x7000,Uint8Array.of(0xb8,0x34)));assert.throws(()=>p.callbacks.readPhysical(0x7000,2));assert.throws(()=>p.callbacks.packedScalar(3,0x64,1,0xaa));
 for(const e of stores)p.callbacks.writePhysical(e.raw,Uint8Array.from(e.bytes));assert.deepEqual(Array.from(p.callbacks.readPhysical(0x618,8).bytes),[0xff,0xff,0,0,0,0x9b,0,0]);const page=p.callbacks.admitExecutePage(0x7000);assert.deepEqual(page.bytes,expectedRamPage());assert.equal(page.generation,2);assert.throws(()=>p.callbacks.writePhysical(0x7002,Uint8Array.of(0x12,0xf4)));assert.throws(()=>p.callbacks.admitExecutePage(0x107000));p.end();const s=p.checkpoint();assert.equal(s.ram.bootStores,4);assert.equal(s.nativeTicks,0);assert.equal(s.successfulQuanta,0);assert.equal(s.mappingEpoch,0);assert.equal(s.ram.gdt[0x61d],0x9b);assert.deepEqual(p.records(),[]);p.close();
});
function functionText(s,name){const start=s.indexOf(name);assert.ok(start>=0);const brace=s.indexOf('{',start);let n=1,i=brace+1;for(;n&&i<s.length;i++){if(s[i]==='{')n++;if(s[i]==='}')n--;}assert.equal(n,0);return s.slice(start,i);}
test('nonguest C runs actual generated protected store/read/fetch/fullpage predicates',()=>{
 const s=deriveProtectedRamRuntime().bytes.toString(),names=['static uint8_t bw_protected_ram_byte','static bool bw_protected_store','static bool bw_protected_read','static bool bw_protected_descriptor','static bool bw_cold_fetch_domain','static bool bw_cold_fetch_page'];
 const pageProof=s.split('\n').find(l=>l.includes('if(type==1)for(unsigned i=0;i<4096;++i)'));assert.ok(pageProof);
 const accepted=instructions.map(i=>`assert(bw_cold_fetch_domain(0xf000,0,${i.ip===0x133?1:0},0,0xf0000,${i.ip},${i.bytes.length},0xf0000+${i.ip},0,1));`).join('\n');
 const code=`#include <cstdint>\n#include <cstring>\n#include <stdexcept>\n#include <cassert>\nstatic void bw_slice_fail(const char *s){throw std::runtime_error(s);}\n${names.map(n=>functionText(s,n)).join('\n')}\nstatic void actual_page(const uint8_t *b,uint32_t generation){unsigned type=1;struct{const uint8_t *bytes;}page={b};${pageProof}}\ntemplate<class F>void refuse(F f){bool denied=false;try{f();}catch(const std::runtime_error&){denied=true;}assert(denied);}\nint main(){${accepted}
 assert(bw_cold_fetch_domain(0xf000,0,0,0,0xffff0000,0xfff0,5,0xfffffff0,0,1));assert(bw_cold_fetch_domain(0x18,0,1,0,0,0x7000,3,0x7000,0,1));assert(!bw_cold_fetch_domain(0x18,0,0,0,0,0x7000,3,0x7000,0,1));assert(!bw_cold_fetch_domain(0x18,1,1,0,0,0x7000,3,0x7000,0,1));assert(!bw_cold_fetch_domain(0x18,0,1,1,0,0x7000,3,0x7000,0,1));assert(!bw_cold_fetch_domain(0x18,0,1,0,0,0x7003,1,0x7003,0,1));
 uint8_t d[8]={0xff,0xff,0,0,0,0x9b,0,0},b[2]={0xb8,0x34},h[2]={0x12,0xf4};assert(bw_protected_store(0x618,0x618,4,d,0,0xf000,0x106));assert(bw_protected_store(0x61c,0x61c,4,d+4,1,0xf000,0x10f));assert(bw_protected_store(0x7000,0x7000,2,b,0,0xf000,0x118));assert(bw_protected_store(0x7002,0x7002,2,h,1,0xf000,0x11e));
 assert(!bw_protected_store(0x618,0x618,4,d,1,0xf000,0x106));assert(!bw_protected_store(0x618,0x618,3,d,0,0xf000,0x106));assert(!bw_protected_store(0x618,0x618,4,d,0,0x18,0x106));assert(!bw_protected_store(0x618,0x618,4,d,0,0xf000,0x107));assert(!bw_protected_store(0x618,0x619,4,d,0,0xf000,0x106));b[1]=1;assert(!bw_protected_store(0x7000,0x7000,2,b,0,0xf000,0x118));
 assert(bw_protected_read(0x618,0x618,8,1,0xf000,0x133));assert(bw_protected_read(0xf0180,0xf0180,6,2,0xf000,0x124));assert(!bw_protected_read(0x618,0x618,8,2,0xf000,0x133));assert(!bw_protected_read(0x618,0x618,8,1,0xf000,0x124));assert(!bw_protected_read(0x61f,0x61f,2,1,0xf000,0x133));assert(!bw_protected_read(0x618,0x619,8,1,0xf000,0x133));assert(bw_protected_descriptor(0x618,d,8));assert(!bw_protected_descriptor(0x618,d,0));assert(!bw_protected_descriptor(0x61f,d,2));d[7]=1;assert(!bw_protected_descriptor(0x618,d,8));
 uint8_t page[4096]={0xb8,0x34,0x12,0xf4};actual_page(page,2);page[4095]=1;refuse([&]{actual_page(page,2);});page[4095]=0;refuse([&]{actual_page(page,1);});assert(bw_cold_fetch_page(true,0x7000,0x7000,0,0,1,0x7000,0x7000,0x34,0,2,2,1));assert(!bw_cold_fetch_page(true,0x7000,0x7000,0,0,1,0x7000,0x7000,0x35,0,2,2,1));assert(!bw_cold_fetch_page(true,0x7000,0x7000,0,0,1,0x7000,0x7000,0x34,0,2,3,1));return 0;}`;
 const d=mkdtempSync(join(tmpdir(),'protected-policy-'));try{writeFileSync(join(d,'fixture.cc'),code);execFileSync('g++',['-std=c++17','-O0','-Wall','-Wextra','-Werror',join(d,'fixture.cc'),'-o',join(d,'fixture')],{timeout:10000});execFileSync(join(d,'fixture'),[],{timeout:5000});}finally{rmSync(d,{recursive:true,force:true});}
});
test('distinct protected manifest/receipt rejects old profiles/generated bytes and provenance corruption',()=>{
 const f=fixture();assert.deepEqual(f.manifest.originalRamProvenance,f.ram);assert.deepEqual(validateBuildMetadata(f.input,f.source,f.manifest,f.receipt),generatedHashes());
 for(const change of [x=>x.receipt.schema='bw.native-ram-bootstrap-build-receipt.v1',x=>x.receipt.protectedProfile=x.ram.profile,x=>x.manifest.profile=x.ram.profile,x=>x.manifest.actualPreparedHashes=x.ram.actualPreparedHashes,x=>delete x.manifest.originalRamProvenance,x=>x.manifest.originalRamProvenance.generatedRuntimeSha256='0'.repeat(64),x=>x.manifest.sourceHashes.foreign='0'.repeat(64),x=>x.input.addon='/foreign/bw_direct.node',x=>x.manifest.protectedProfile={...protectedRamProfile,maxQuanta:513}]){const v=fixture();change(v);assert.throws(()=>validateBuildMetadata(v.input,v.source,v.manifest,v.receipt));}
 assert.throws(()=>deriveProtectedAdmission(Buffer.from('unknown')));
});
test('generated protected config authenticates exact owned ROM and refuses altered modes/roles',()=>{
 const d=mkdtempSync(join(tmpdir(),'protected-config-'));try{mkdirSync(join(d,'bochs'));const f=fixture(d),p=join(d,'bochsrc'),rom=join(d,'bochs/owned-protected-ram-ROM.bin');const text=canonicalConfiguration(f.manifest,join(d,'run.log'));writeFileSync(p,text);const raw=generatedHashes();assert.equal(raw['bochs/owned-protected-ram-ROM.bin'],protectedRamProfile.romSha256);
 for(const change of [s=>s.replace('guest=16','guest=32'),s=>s.replace('owned-protected-ram-ROM.bin','owned-ram-ROM.bin'),s=>s+'cpu: count=2\n']){writeFileSync(p,change(text));assert.throws(()=>authenticateConfiguration(p,f.manifest));}writeFileSync(p,text);const bad=new Uint8Array(65536);writeFileSync(rom,bad);assert.throws(()=>authenticateConfiguration(p,f.manifest));assert.throws(()=>canonicalConfiguration(f.manifest,'/tmp/a b'));}finally{rmSync(d,{recursive:true,force:true});}
});
test('protected source identity runs in exact clean alternate checkout and rejects dirty source',()=>{
 const root=fileURLToPath(new URL('../',import.meta.url)),revision=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),paths=new Set();
 function visit(p){if(paths.has(p))return;paths.add(p);const b=readFileSync(resolve(root,p)),g=execFileSync('git',['show',revision+':'+p],{cwd:root,maxBuffer:16<<20});assert.equal(sha256(b),sha256(g),'caller current/Git '+p);if(/\.(mjs|js)$/.test(p)){const special=p.startsWith('scripts/bochs-cpu3-native-protected-ram/')||p.startsWith('scripts/bochs-cpu3-native-ram-bootstrap/')||p==='test/i80386-protected-ram-native-source.test.mjs';const regex=special?/^\s*import\s+[^;\n]+?\s*from\s*['"](\.[^'"]+)['"]/gm:/(?:from\s+|import\s*)['"](\.[^'"]+)['"]/g;for(const m of b.toString().matchAll(regex))visit(resolve(root,dirname(p),m[1]).slice(root.length));}}
 for(const p of ownedAssets)visit(p);const d=mkdtempSync(join(tmpdir(),'protected-clean-')),clean=join(d,'source');
 try{mkdirSync(clean);execFileSync('git',['init','--quiet',clean]);const objects=execFileSync('git',['rev-parse','--path-format=absolute','--git-path','objects'],{cwd:root,encoding:'utf8'}).trim();writeFileSync(join(clean,'.git/objects/info/alternates'),objects+'\n');const shallow=execFileSync('git',['rev-parse','--path-format=absolute','--git-path','shallow'],{cwd:root,encoding:'utf8'}).trim();try{writeFileSync(join(clean,'.git/shallow'),readFileSync(shallow));}catch(e){if(e.code!=='ENOENT')throw e;}execFileSync('git',['update-ref','HEAD',revision],{cwd:clean});execFileSync('git',['sparse-checkout','init','--no-cone'],{cwd:clean});execFileSync('git',['sparse-checkout','set','--no-cone','--stdin'],{cwd:clean,input:[...paths].sort().map(p=>'/'+p).join('\n')+'\n'});execFileSync('git',['checkout','--quiet','--detach',revision],{cwd:clean});
 const code=`import {protectedBuildPlan} from './scripts/bochs-cpu3-native-protected-ram/build-identity.mjs'; console.log(JSON.stringify(protectedBuildPlan()))`,opts={cwd:clean,encoding:'utf8',timeout:10000,maxBuffer:2<<20};const plan=JSON.parse(execFileSync(process.execPath,['--max-old-space-size=128','--input-type=module','-e',code],opts));assert.equal(plan.source.revision,revision);assert.deepEqual(Object.keys(plan.source.hashes).sort(),[...paths].sort());assert.deepEqual(plan.generated,generatedHashes());assert.equal(plan.status,'SOURCE_ONLY_REQUIRES_NEW_PREPARATION_AND_BUILD');assert.ok(plan.source.hashes['scripts/bochs-cpu3-native-protected-ram/cpu-profile.mjs']);assert.ok(plan.source.hashes['src/experimental/machine-checkpoint.js']);writeFileSync(join(clean,'dirty-sentinel'),'diagnostic');assert.throws(()=>execFileSync(process.execPath,['--max-old-space-size=128','--input-type=module','-e',code],opts),/frozen clean source/);
 }finally{rmSync(d,{recursive:true,force:true});}
});
