import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from 'node:fs';
import {createOwnedIn8Provider}from '../scripts/bochs-cpu3-native-owned-in8/provider.mjs';
import {createOwnedBulkClockProvider}from '../scripts/bochs-cpu3-native-owned-clock-bulk/provider.mjs';
import {HotDirectBoardFacade}from '../scripts/bochs-cpu3-native-hot-direct/board.mjs';
const empty=()=>new Uint32Array();
function pair(sink=false){const events=[[],[]];const factories=[createOwnedIn8Provider,createOwnedBulkClockProvider];const owners=factories.map((factory,i)=>factory({compactSink:sink?e=>events[i].push(structuredClone(e)):null}));for(const p of owners){assert.deepEqual([...p.callbacks.clockTransfer(empty(),1)],[0,0,4,0,6000,0,1]);p.begin();p.callbacks.clockTransfer(empty(),2);}return {owners,events};}
function commit(ps,words,reason=5){const values=ps.map(p=>[...p.callbacks.clockTransfer(Uint32Array.from(words),reason)]);assert.deepEqual(values[0],values[1]);return values[0];}
function deny(ps,words,reason=5){for(const p of ps)assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.from(words),reason));}
function finish(ps){for(const p of ps)p.end();assert.deepEqual(ps[0].checkpoint(),ps[1].checkpoint());for(const p of ps)p.close();}
function out(ps,port,value){for(const p of ps){p.callbacks.packedScalar(3,port,1,value);p.callbacks.clockTransfer(empty(),6);}}
test('capture OFF aggregate commits match ordered N/fault/QREP effects across every commit reason',()=>{const {owners:ps}=pair();for(const reason of [3,4,5,7,8,9,10,11])commit(ps,[1,3,1,2,1],reason);finish(ps);});
test('CAPON preserves exact kinds, ordinals and all callback state',()=>{const {owners:ps,events}=pair(true);commit(ps,[1,3,2,1]);out(ps,0x43,0);for(const p of ps){p.callbacks.packedScalar(5,0x40,1,0);p.callbacks.clockTransfer(empty(),6);}finish(ps);assert.deepEqual(events[0],events[1]);assert.deepEqual(events[0].filter(e=>e.operation==='quantum').map(e=>e.args),[[1],[0]]);});
test('malformed last word is atomically denied before all tape effects',()=>{const {owners:ps}=pair();deny(ps,[1,2,1,99]);assert.deepEqual(commit(ps,[1]),[1,0,4,0,6000,0,1]);finish(ps);});
test('independent requested N/Q caps and900 word tape boundary',()=>{const {owners:ps}=pair();commit(ps,[...new Array(600).fill(1),...new Array(300).fill(3)]);deny(ps,[1]);deny(ps,[2]);for(const p of ps)assert.throws(()=>p.callbacks.clockTransfer(new Uint32Array(901),5));finish(ps);});
test('phase queries and observers cannot bypass entry or pendingPIO',()=>{const {owners:ps}=pair();for(const p of ps){assert.throws(()=>p.callbacks.clockTransfer(empty(),2));assert.throws(()=>p.callbacks.clockTransfer(empty(),6));assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(1),6));p.callbacks.packedScalar(3,0x43,1,0);assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(1),5));assert.throws(()=>p.callbacks.readPhysical(0,1));p.callbacks.clockTransfer(empty(),6);}finish(ps);});
test('pending mapping rejects N/REP and publishes only ordinaryQ',()=>{const {owners:ps}=pair();out(ps,0x64,0xd1);out(ps,0x60,1);deny(ps,[1]);deny(ps,[3]);commit(ps,[2]);finish(ps);});
function instrumented(factory){const descriptor=Object.getOwnPropertyDescriptor(HotDirectBoardFacade.prototype,'beginRun'),original=HotDirectBoardFacade.prototype.beginRun;let board;HotDirectBoardFacade.prototype.beginRun=function(){board=this;return Reflect.apply(original,this,[]);};let p;try{p=factory();}finally{if(descriptor)Object.defineProperty(HotDirectBoardFacade.prototype,'beginRun',descriptor);else delete HotDirectBoardFacade.prototype.beginRun;}p.callbacks.clockTransfer(empty(),1);p.begin();p.callbacks.clockTransfer(empty(),2);return {p,board};}
// Test-only unsupported prototype instrumentation; no production board/hook admission.
for(const corruption of ['cycles','debt','nativeTicks','successfulQuanta'])test('preexisting '+corruption+' corruption cannot be normalized by aggregate commit',()=>{const results=[createOwnedIn8Provider,createOwnedBulkClockProvider].map(factory=>{const {p,board}=instrumented(factory);if(corruption==='cycles')board.machine.cycles++;else if(corruption==='debt')board.machine._chipDebt=6006;else board[corruption]=0xffffffff;assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(1,2),5));assert.equal(board.active,false);return [board.nativeTicks,board.successfulQuanta,board.machine.cycles,board.machine._chipDebt];});assert.deepEqual(results[0],results[1]);});
test('last dueQ accepted, next Q denied, N remains independent',()=>{const records=[createOwnedIn8Provider,createOwnedBulkClockProvider].map(factory=>{const {p,board}=instrumented(factory);board.machine._chipDeadline=6;assert.deepEqual([...p.callbacks.clockTransfer(Uint32Array.of(3),5)],[0,1,10,6,6,0,1]);assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(2),5));p.callbacks.clockTransfer(Uint32Array.of(1),5);p.end();const result=p.checkpoint();p.close();return result;});assert.deepEqual(records[0],records[1]);});
test('CAPON sink exception keeps partial effect and finally/reentry semantics',()=>{const records=[createOwnedIn8Provider,createOwnedBulkClockProvider].map(factory=>{let p,count=0;p=factory({compactSink:e=>{count++;assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(1),5));if(e.operation==='quantum')throw Error('sink witness');}});p.callbacks.clockTransfer(empty(),1);p.begin();p.callbacks.clockTransfer(empty(),2);assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(1,2,1),5),/sink witness/);p.end();const state=p.checkpoint();p.close();return {count,state};});assert.deepEqual(records[0],records[1]);});
test('source derivative retains exact preflight, original providers remain untouched',()=>{const original=readFileSync(new URL('../scripts/bochs-cpu3-native-owned-in8/provider.mjs',import.meta.url),'utf8'),candidate=readFileSync(new URL('../scripts/bochs-cpu3-native-owned-clock-bulk/provider.mjs',import.meta.url),'utf8');const preflight=s=>s.slice(s.indexOf('   // Entire bounded tape'),s.indexOf('   n=nextN'));assert.equal(preflight(original),preflight(candidate));assert.match(candidate,/this\.machine\.cycles\+=6\*deltaQ/);assert.doesNotMatch(candidate,/this\.machine\.cycles=4/);});

test('private board lifecycle denial precedes all aggregate effects',()=>{for(const field of ['running','active','closed']){const records=[createOwnedIn8Provider,createOwnedBulkClockProvider].map(factory=>{const {p,board}=instrumented(factory);board[field]=field==='running'?false:true;assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(1,2),5));return [board.nativeTicks,board.successfulQuanta,board.machine.cycles,board.machine._chipDebt,board.active];});assert.deepEqual(records[0],records[1]);}});
