import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,dirname} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {ownedAssets} from '../scripts/bochs-cpu3-native-cold-bios/identity.mjs';
import {execFileSync} from 'node:child_process';
import {fixedRamBootstrapRom,ramProgram,ramRomSha256,romInstructions,fetchDomain,expectedRamPage,validateRamWrite,ramBootstrapProfile,namedCuts} from '../scripts/bochs-cpu3-native-ram-bootstrap/profile.mjs';
import {deriveRamBootstrapRuntime,transformRamBootstrapRuntime,qualifiedColdRuntimeSha256} from '../scripts/bochs-cpu3-native-ram-bootstrap/runtime.mjs';
import {deriveRamProvider,transformRamProvider,createOwnedRamBootstrapProvider} from '../scripts/bochs-cpu3-native-ram-bootstrap/provider-derivation.mjs';
import {generatedRamArtifacts,sourceAssets} from '../scripts/bochs-cpu3-native-ram-bootstrap/preparation.mjs';
import {sha256} from '../scripts/bochs-cpu3-native-owned-clock/derive.mjs';
test('owned ROM encodes every instruction, RAM word and branch destination',()=>{
 const rom=fixedRamBootstrapRom(),again=fixedRamBootstrapRom();assert.equal(rom.length,65536);assert.equal(sha256(rom),ramRomSha256);assert.notEqual(rom,again);assert.throws(()=>fixedRamBootstrapRom(rom));
 const instructions=[[0,[0xfa]],[1,[0xb8,0,0]],[4,[0x8e,0xd8]],[6,[0xc7,6,0,0x70,0xb8,1]],[12,[0xc7,6,2,0x70,0,0xea]],[18,[0xc7,6,4,0x70,0x40,0]],[24,[0xc7,6,6,0x70,0,0xf0]],[30,[0xea,0,0x70,0,0]],[0x40,[0x3d,1,0]],[0x43,[0x75,0x0b]],[0x45,[0xc7,6,1,0x70,2,0]],[0x4b,[0xea,0,0x70,0,0]]];
 assert.deepEqual(instructions.map(([ip,b])=>[ip,b.length]),romInstructions);for(const [ip,b]of instructions)assert.deepEqual(Array.from(rom.subarray(ip,ip+b.length)),b);
 assert.deepEqual(Array.from(rom.subarray(0xfff0,0xfff5)),[0xea,0,0,0,0xf0]);assert.equal(0x45+rom[0x44],0x50);assert.equal(rom[0x50],0xf4);assert.deepEqual(ramProgram,[0xb8,1,0,0xea,0x40,0,0,0xf0]);
 const occupied=new Set([...instructions.flatMap(([ip,b])=>b.map((_,i)=>ip+i)),0xfff0,0xfff1,0xfff2,0xfff3,0xfff4]);for(let i=0;i<rom.length;i++)if(!occupied.has(i))assert.equal(rom[i],0xf4);
 rom[0]=0;assert.equal(again[0],0xfa);assert.equal(ramBootstrapProfile.maxQuanta,512);assert.ok(!('totalQuanta'in ramBootstrapProfile));assert.equal(namedCuts.at(-1).eip,0x50);
});
test('instruction fetch denies unknown location, mode, length, mapping and terminal execution',()=>{
 const v={selector:0xf000,cs32:0,pe:0,interrupts:0,base:0xf0000,eip:0,length:1,start:0xf0000,mappingPending:0,a20:1};
 for(const [ip,len]of romInstructions)assert.ok(fetchDomain({...v,eip:ip,length:len,start:v.base+ip}));assert.ok(fetchDomain({...v,base:0xffff0000,eip:0xfff0,length:5,start:0xfffffff0}));
 for(const [ip,len]of [[0x7000,3],[0x7003,5]])assert.ok(fetchDomain({...v,selector:0,base:0,eip:ip,length:len,start:ip}));
 for(const change of [{selector:1},{cs32:1},{pe:1},{interrupts:1},{a20:0},{mappingPending:1},{length:2},{eip:0x50,start:0xf0050},{start:0xf0001},{selector:0,base:0,eip:0x107000,start:0x107000,length:3}])assert.equal(fetchDomain({...v,...change}),false);
 assert.throws(()=>fetchDomain({...v,eip:-1}));
});
test('write ownership refuses changed address/value/order/phase and second patch',()=>{
 assert.equal(validateRamWrite(0x7000,Uint8Array.of(0xb8,1),0,0,false),'boot');assert.equal(validateRamWrite(0x7001,Uint8Array.of(2,0),4,0,true),'patch');
 for(const args of [[0x7002,Uint8Array.of(0xb8,1),0,0,false],[0x7000,Uint8Array.of(0xb8,2),0,0,false],[0x7000,Uint8Array.of(0xb8,1),0,0,true],[0x7001,Uint8Array.of(2,0),4,0,false],[0x7001,Uint8Array.of(2,0),4,1,true],[0x7fff,Uint8Array.of(2,0),4,0,true],[0x7001,Uint8Array.of(2),4,0,true]])assert.throws(()=>validateRamWrite(...args));
 for(const g of [0,1,3,6,-1])assert.throws(()=>expectedRamPage(g));assert.equal(expectedRamPage(4)[1],1);assert.equal(expectedRamPage(5)[1],2);assert.equal(expectedRamPage(5).subarray(8).some(Boolean),false);
});
test('derivatives pin real cold sources, preserve coherence guards and inverse',()=>{
 const c=deriveRamBootstrapRuntime(),p=deriveRamProvider();assert.equal(c.baseSha256,qualifiedColdRuntimeSha256);assert.ok(c.bytes.includes('current-code-write'));assert.ok(c.bytes.includes('admitted-unexecuted-code-write'));assert.ok(c.bytes.includes('page->kind==1?page->decoded:UINT32_MAX'));
 assert.ok(c.bytes.indexOf('static uint8_t bw_ram_bootstrap_byte')<c.bytes.indexOf('static const uint8_t *bw_host_execute'));assert.ok(c.bytes.includes('RAM-bootstrap-patch-write'));assert.ok(p.bytes.includes('no caller config/hooks'));const corrupt=Buffer.from(c.bytes);corrupt[0]^=1;assert.throws(()=>transformRamBootstrapRuntime(corrupt));assert.throws(()=>transformRamProvider(Buffer.alloc(1)));
});
test('private real-board callbacks enforce no hooks, exact writes/page and no PIO without CPU steps',async()=>{
 await assert.rejects(createOwnedRamBootstrapProvider({}));const p=await createOwnedRamBootstrapProvider();assert.ok(Object.isFrozen(p));p.callbacks.clockTransfer(new Uint32Array(),1);p.begin();p.callbacks.clockTransfer(new Uint32Array(),2);
 const initial=p.callbacks.readPhysical(0x7000,8);assert.deepEqual(Array.from(initial.bytes),Array(8).fill(0));assert.throws(()=>p.callbacks.admitExecutePage(0x7000));assert.throws(()=>p.callbacks.writePhysical(0x7001,Uint8Array.of(2,0)));assert.throws(()=>p.callbacks.packedScalar(3,0x64,1,0xaa));
 for(const [raw,lo,hi]of [[0x7000,0xb8,1],[0x7002,0,0xea],[0x7004,0x40,0],[0x7006,0,0xf0]])p.callbacks.writePhysical(raw,Uint8Array.of(lo,hi));
 assert.throws(()=>p.callbacks.admitExecutePage(0x107000));const page=p.callbacks.admitExecutePage(0x7000);assert.deepEqual(page.bytes,expectedRamPage(4));assert.equal(page.generation,4);p.callbacks.writePhysical(0x7001,Uint8Array.of(2,0));assert.throws(()=>p.callbacks.writePhysical(0x7001,Uint8Array.of(2,0)));assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.from({length:513},()=>1),3));p.end();
 const s=p.checkpoint();assert.equal(s.nativeTicks,0);assert.equal(s.successfulQuanta,0);assert.equal(s.ram.writes.length,5);assert.deepEqual(s.ram.code,Array.from(expectedRamPage(5).subarray(0,8)));assert.deepEqual(p.records(),[]);assert.equal(s.mappingEpoch,0);p.close();
});
function functionText(s,name){const start=s.indexOf(name);assert.ok(start>=0);const brace=s.indexOf('{',start);let n=1,i=brace+1;for(;n&&i<s.length;i++){if(s[i]==='{')n++;if(s[i]==='}')n--;}assert.equal(n,0);return s.slice(start,i);}
test('tiny nonguest C executes the actual generated fetch/write and coherence refusal bodies',()=>{
 const s=deriveRamBootstrapRuntime().bytes.toString();const marker='  if(write&&kind==1){\n    const uint32_t g=bw_generation_of(want);static const uint8_t boot';const start=s.indexOf(marker);assert.ok(start>0);const end=s.indexOf('  if(write&&kind==1)bw_write_admission',start);assert.ok(end>start);const pageProof=s.split('\n').find(l=>l.includes('if(type==1)for(unsigned i=0;i<4096;++i)'));assert.ok(pageProof);
 const fixture=`#include <cstdint>\n#include <cstring>\n#include <stdexcept>\n#include <cassert>\nstatic void bw_slice_fail(const char *m){throw std::runtime_error(m);}\n${s.slice(s.indexOf('struct bw_generation {'),s.indexOf('struct bw_pending_write {'))}\n${functionText(s,'static uint8_t bw_ram_bootstrap_byte')}\n${functionText(s,'static bool bw_cold_fetch_domain')}\n${functionText(s,'static bool bw_cold_fetch_page')}\n${s.slice(s.indexOf('struct bw_coherent_page {'),s.indexOf('static void bw_write_admission(uint32_t decoded,unsigned length,unsigned why){'))}\nstatic uint32_t bw_current_code_page=UINT32_MAX,bw_mapping_epoch=0,bw_attempt_cs=0xf000,bw_attempt_eip=6;\n${functionText(s,'static void bw_write_admission(uint32_t decoded,unsigned length,unsigned why){')}\nstatic void actual_write(uint32_t raw,uint32_t want,unsigned length,const uint8_t *data){bool write=true;unsigned kind=1;${s.slice(start,end)}bw_write_admission(want,length,0);}\nstatic void actual_page(const uint8_t *bytes,uint32_t generation){unsigned type=1;struct {const uint8_t *bytes;} page={bytes};${pageProof}}\ntemplate<class F> void refused(F f){bool failed=false;try{f();}catch(const std::runtime_error&){failed=true;}assert(failed);}\nint main(){\nassert(bw_cold_fetch_domain(0,0,0,0,0,0x7000,3,0x7000,0,1));assert(!bw_cold_fetch_domain(0,0,0,0,0,0x7001,3,0x7001,0,1));assert(!bw_cold_fetch_domain(0xf000,0,0,0,0xf0000,0x50,1,0xf0050,0,1));\nassert(bw_cold_fetch_page(true,0x7000,0x7000,0,0,1,0x7000,0x7000,1,0,4,4,1));assert(!bw_cold_fetch_page(true,0x7000,0x7000,0,0,1,0x7000,0x7000,2,0,4,4,1));assert(!bw_cold_fetch_page(true,0x7000,0x7000,0,0,1,0x7000,0x7000,1,0,4,5,1));refused([]{bw_ram_bootstrap_byte(0,3);});\nuint8_t owned[4096]={0xb8,1,0,0xea,0x40,0,0,0xf0};actual_page(owned,4);owned[4095]=1;refused([&]{actual_page(owned,4);});owned[4095]=0;owned[8]=1;refused([&]{actual_page(owned,4);});owned[8]=0;owned[1]=2;refused([&]{actual_page(owned,4);});actual_page(owned,5);\nuint8_t a[2]={0xb8,1};actual_write(0x7000,0x7000,2,a);refused([&]{actual_write(0x7002,0x7002,2,a);});bw_generation_of(0x7000)=4;bw_attempt_eip=0x45;uint8_t patch[2]={2,0};bw_page_count=1;bw_pages[0].kind=1;bw_pages[0].epoch=0;bw_pages[0].decoded=0x7000;bw_pages[0].executed=false;refused([&]{actual_write(0x7001,0x7001,2,patch);});bw_pages[0].executed=true;actual_write(0x7001,0x7001,2,patch);bw_current_code_page=0x7000;refused([&]{actual_write(0x7001,0x7001,2,patch);});bw_current_code_page=UINT32_MAX;bw_attempt_cs=0;refused([&]{actual_write(0x7001,0x7001,2,patch);});bw_attempt_cs=0xf000;bw_generation_of(0x7000)=5;refused([&]{actual_write(0x7001,0x7001,2,patch);});return 0;}\n`;
 const dir=mkdtempSync(join(tmpdir(),'ram-bootstrap-policy-'));try{writeFileSync(join(dir,'fixture.cc'),fixture);execFileSync('g++',['-std=c++17','-O0','-Wall','-Wextra','-Werror',join(dir,'fixture.cc'),'-o',join(dir,'fixture')],{timeout:10000});execFileSync(join(dir,'fixture'),[],{timeout:5000});}finally{rmSync(dir,{recursive:true,force:true});}
});
test('source build plan uses an exact clean isolated checkout and refuses dirty source',()=>{
 const root=fileURLToPath(new URL('../',import.meta.url)),revision=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),paths=new Set();
 function visit(p){if(paths.has(p))return;assert.ok(!p.startsWith('../')&&!p.startsWith('/'));paths.add(p);const b=readFileSync(resolve(root,p)),git=execFileSync('git',['show',revision+':'+p],{cwd:root,maxBuffer:16<<20});assert.equal(sha256(b),sha256(git),'caller current/Git source '+p);if(/\.(mjs|js)$/.test(p)){const imports=p.startsWith('scripts/bochs-cpu3-native-ram-bootstrap/')||p==='test/i80386-ram-bootstrap-source.test.mjs'?/^\s*import\s+[^;\n]+?\s*from\s*['"](\.[^'"]+)['"]/gm:/(?:from\s+|import\s*)['"](\.[^'"]+)['"]/g;for(const m of b.toString().matchAll(imports)){const q=resolve(root,dirname(p),m[1]);assert.ok(q.startsWith(root));visit(q.slice(root.length));}}}
 for(const p of [...ownedAssets,...sourceAssets])visit(p);
 const dir=mkdtempSync(join(tmpdir(),'ram-clean-source-')),caller=join(dir,'dirty-caller'),clean=join(dir,'clean-source');
 function checkout(from,to){mkdirSync(to);execFileSync('git',['init','--quiet',to],{timeout:10000});const objects=execFileSync('git',['rev-parse','--path-format=absolute','--git-path','objects'],{cwd:from,encoding:'utf8',timeout:10000}).trim();writeFileSync(join(to,'.git/objects/info/alternates'),objects+'\n');const shallow=execFileSync('git',['rev-parse','--path-format=absolute','--git-path','shallow'],{cwd:from,encoding:'utf8',timeout:10000}).trim();try{writeFileSync(join(to,'.git/shallow'),readFileSync(shallow));}catch(e){if(e.code!=='ENOENT')throw e;}execFileSync('git',['update-ref','HEAD',revision],{cwd:to,timeout:10000});execFileSync('git',['sparse-checkout','init','--no-cone'],{cwd:to,timeout:10000});execFileSync('git',['sparse-checkout','set','--no-cone','--stdin'],{cwd:to,input:[...paths].sort().map(p=>'/'+p).join('\n')+'\n',timeout:10000});execFileSync('git',['checkout','--quiet','--detach',revision],{cwd:to,timeout:10000});assert.equal(execFileSync('git',['status','--porcelain'],{cwd:to,encoding:'utf8'}).trim(),'');}
 try{
  checkout(root,caller);const codeFor=where=>`import {ramBuildProfilePlan} from ${JSON.stringify(pathToFileURL(join(where,'scripts/bochs-cpu3-native-ram-bootstrap/preparation.mjs')).href)};console.log(JSON.stringify(ramBuildProfilePlan()))`;
  execFileSync('git',['update-index','--no-skip-worktree','package-lock.json'],{cwd:caller});const lock=execFileSync('git',['show',revision+':package-lock.json'],{cwd:caller,maxBuffer:16<<20});writeFileSync(join(caller,'package-lock.json'),Buffer.concat([lock,Buffer.from('\n')]));mkdirSync(join(caller,'blinkenrocket-firmware'));writeFileSync(join(caller,'blinkenrocket-firmware/fixture'),'manufactured CI checkout');const dirty=execFileSync('git',['status','--porcelain'],{cwd:caller,encoding:'utf8'});assert.match(dirty,/M package-lock\.json/);assert.match(dirty,/\?\? blinkenrocket-firmware\//);assert.throws(()=>execFileSync(process.execPath,['--max-old-space-size=128','--input-type=module','-e',codeFor(caller)],{cwd:caller,timeout:10000,stdio:'pipe'}),/frozen clean source/);
  checkout(caller,clean);
  for(const p of paths)assert.equal(sha256(readFileSync(join(clean,p))),sha256(readFileSync(resolve(root,p))),'exact isolated source '+p);
  const code=codeFor(clean);
  const plan=JSON.parse(execFileSync(process.execPath,['--max-old-space-size=128','--input-type=module','-e',code],{cwd:clean,encoding:'utf8',timeout:10000,maxBuffer:2<<20})),a=generatedRamArtifacts();assert.equal(a.rom.length,65536);assert.equal(plan.generatedHashes['owned-ram-ROM.bin'],ramRomSha256);assert.notEqual(plan.generatedHashes['bochs/cpu/bw_slice_runtime.inc'],qualifiedColdRuntimeSha256);assert.equal(plan.status,'SOURCE_ONLY_REQUIRES_SEPARATE_BUILD_AND_ADMISSION');assert.equal(plan.abiVersion,4);assert.equal(plan.profile.maxNativeTicks,512);assert.ok(plan.originalAddonNotAdmitted);assert.equal(plan.source.revision,revision);assert.deepEqual(Object.keys(plan.source.hashes).sort(),[...paths].sort());
  assert.equal(execFileSync('git',['status','--porcelain'],{cwd:caller,encoding:'utf8'}),dirty,'caller remains dirty and unchanged');
 }finally{rmSync(dir,{recursive:true,force:true});}
});
