import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {deriveProtectedRamRuntime} from '../scripts/bochs-cpu3-native-protected-ram/runtime.mjs';
import {deriveProtectedRamProvider} from '../scripts/bochs-cpu3-native-protected-ram/provider-derivation.mjs';
import {deriveProtectedStackRuntime,transformProtectedStackRuntime,runtimeParentSha256,shadowSources} from '../scripts/bochs-cpu3-native-protected-stack/runtime.mjs';
import {deriveProtectedStackProvider,transformProtectedStackProvider,createOwnedProtectedStackProvider,providerParentSha256} from '../scripts/bochs-cpu3-native-protected-stack/provider-derivation.mjs';
import {validateProtectedRead,validateProtectedWrite} from '../scripts/bochs-cpu3-native-protected-stack/provider-profile.mjs';
import {stores,bootStores,expectedPages,ramProgram,romInstructions,ramInstructions,farJumpIp,afterLgdt,protectedStackProfile} from '../scripts/bochs-cpu3-native-protected-stack/profile.mjs';
import {sha256,replacement} from '../scripts/bochs-cpu3-native-owned-clock/derive.mjs';
function inverse(d){let s=d.bytes.toString();for(const e of [...d.edits].reverse())if(e.count){assert.equal(s.split(e.next).length-1,e.count);s=s.split(e.next).join(e.old);}else s=replacement(s,e.next,e.old,'test inverse');return Buffer.from(s);}
test('stack derivatives authenticate both held sources and exact inverses without changing coherence order',()=>{
 const c=deriveProtectedStackRuntime(),p=deriveProtectedStackProvider();assert.equal(sha256(deriveProtectedRamRuntime().bytes),runtimeParentSha256);assert.equal(sha256(deriveProtectedRamProvider().bytes),providerParentSha256);assert.equal(sha256(inverse(c)),runtimeParentSha256);assert.equal(sha256(inverse(p)),providerParentSha256);
 for(const guard of ['current-code-write','admitted-unexecuted-code-write','protected-RAM-no-paging','protected-stack-shadow-phase','protected-GDT-read-bytes'])assert.ok(c.bytes.includes(guard));assert.ok(c.bytes.indexOf('static bool bw_protected_store')<c.bytes.indexOf('static const uint8_t *bw_host_execute'));assert.ok(p.bytes.includes('owned callback lease'));
 for(const [transform,base]of [[transformProtectedStackRuntime,deriveProtectedRamRuntime().bytes],[transformProtectedStackProvider,deriveProtectedRamProvider().bytes]]){assert.throws(()=>transform(Buffer.from('unknown')));assert.throws(()=>transform(Buffer.concat([base,Buffer.from('\n')])));}
 console.log(JSON.stringify({scope:'derived source hashes only; no native build',runtimeSha256:sha256(c.bytes),providerSha256:sha256(p.bytes),romSha256:protectedStackProfile.romSha256}));
});
test('host stack policy requires exact boot then admitted stack effects and bounded operand reads',()=>{
 for(const [i,s]of stores.entries()){const admitted=i>=11;assert.equal(validateProtectedWrite(s.raw,Uint8Array.from(s.bytes),i,admitted),i+1);assert.throws(()=>validateProtectedWrite(s.raw,Uint8Array.from(s.bytes),i,!admitted));const changed=Uint8Array.from(s.bytes);changed[0]^=1;assert.throws(()=>validateProtectedWrite(s.raw,changed,i,admitted));assert.throws(()=>validateProtectedWrite(s.raw+1,Uint8Array.from(s.bytes),i,admitted));}
 for(const [raw,width]of [[0x610,8],[0x618,8],[0xf0180,6],[0x8ffe,2]])validateProtectedRead(raw,width);
 for(const [raw,width]of [[0x60f,8],[0x61f,2],[0xf0185,2],[0x8ffd,2],[0x8ffe,1],[0x8ffe,3],[0x7000,2],[0xf0180,0]])assert.throws(()=>validateProtectedRead(raw,width));assert.throws(()=>validateProtectedWrite(0x8ffe,Uint8Array.of(0x12,0x70),11,true));assert.throws(()=>validateProtectedWrite(0x8ffe,Uint8Array.of(0x12,0x70),13,true));
});
test('actual private provider publishes GDT4 code7 stack2 generations without CPU execution',async()=>{
 await assert.rejects(createOwnedProtectedStackProvider({}));const p=await createOwnedProtectedStackProvider();try{p.callbacks.clockTransfer(new Uint32Array(),1);p.begin();p.callbacks.clockTransfer(new Uint32Array(),2);assert.throws(()=>p.callbacks.admitExecutePage(0x7000));assert.throws(()=>p.callbacks.writePhysical(0x8ffe,Uint8Array.of(0x34,0x12)));assert.throws(()=>p.callbacks.packedScalar(3,0x64,1,0xaa));
  for(const s of bootStores)p.callbacks.writePhysical(s.raw,Uint8Array.from(s.bytes));const page=p.callbacks.admitExecutePage(0x7000);assert.equal(page.generation,7);assert.deepEqual(page.bytes,expectedPages(bootStores).code);assert.throws(()=>p.callbacks.admitExecutePage(0x8000));assert.throws(()=>p.callbacks.admitExecutePage(0x107000));
  p.callbacks.writePhysical(0x8ffe,Uint8Array.of(0x34,0x12));assert.deepEqual([...p.callbacks.readPhysical(0x8ffe,2).bytes],[0x34,0x12]);p.callbacks.writePhysical(0x8ffe,Uint8Array.of(0x12,0x70));assert.deepEqual([...p.callbacks.readPhysical(0x8ffe,2).bytes],[0x12,0x70]);assert.throws(()=>p.callbacks.writePhysical(0x8ffe,Uint8Array.of(0x12,0x70)));p.end();const c=p.checkpoint();assert.equal(c.ram.storeCount,13);assert.equal(c.ram.bootStores,11);assert.equal(c.ram.admitted,true);assert.deepEqual(c.ram.writes.map(w=>w.generation),[1,2,3,4,1,2,3,4,5,6,7,1,2]);assert.deepEqual(Uint8Array.from(c.ram.gdt),expectedPages().gdt);assert.deepEqual(Uint8Array.from(c.ram.code),expectedPages().code);assert.deepEqual(Uint8Array.from(c.ram.stack),expectedPages().stack);assert.equal(c.nativeTicks,0);assert.equal(c.successfulQuanta,0);assert.equal(c.mappingEpoch,0);assert.deepEqual(p.records(),[]);
 }finally{p.close();}
});
function functionText(s,name){const start=s.indexOf(name);assert.ok(start>=0);const brace=s.indexOf('{',start);let n=1,i=brace+1;for(;n&&i<s.length;i++){if(s[i]==='{')n++;if(s[i]==='}')n--;}assert.equal(n,0);return s.slice(start,i);}
test('nonguest C fixture runs the generated domain, returned operands, shadow and whole-page predicates',()=>{
 const s=deriveProtectedStackRuntime().bytes.toString();const names=['static uint8_t bw_protected_ram_byte','static bool bw_protected_store','static bool bw_protected_read','static bool bw_protected_observed','static bool bw_stack_shadow_phase','static bool bw_cold_fetch_domain','static bool bw_cold_fetch_page'];const pageProof=s.split('\n').find(l=>l.includes('if(type==1)for(unsigned i=0;i<4096;++i)'));assert.ok(pageProof);
 const accepted=romInstructions.map(i=>`assert(bw_cold_fetch_domain(0xf000,0,${i.ip===farJumpIp?1:0},0,0xf0000,${i.ip},${i.bytes.length},0xf0000+${i.ip},0,1));`).concat(ramInstructions.map(i=>`assert(bw_cold_fetch_domain(24,0,1,0,0,${i.ip},${i.bytes.length},${i.ip},0,1));`)).join('\n');
 const effects=stores.map((e,i)=>`{uint8_t b[4]={${e.bytes.join(',')}};assert(bw_protected_store(${e.raw},${e.raw},${e.bytes.length},b,${e.raw<4096?i:e.raw<0x8000?i-4:i-11},${e.cs},${e.ip}));assert(!bw_protected_store(${e.raw},${e.raw},${e.bytes.length},b,99,${e.cs},${e.ip}));assert(!bw_protected_store(${e.raw},${e.raw}+1,${e.bytes.length},b,${e.raw<4096?i:e.raw<0x8000?i-4:i-11},${e.cs},${e.ip}));b[0]^=1;assert(!bw_protected_store(${e.raw},${e.raw},${e.bytes.length},b,${e.raw<4096?i:e.raw<0x8000?i-4:i-11},${e.cs},${e.ip}));}`).join('\n');
 const code=`#include <cstdint>\n#include <cstring>\n#include <stdexcept>\n#include <cassert>\nstatic void bw_slice_fail(const char*s){throw std::runtime_error(s);}\n${names.map(n=>functionText(s,n)).join('\n')}\nstatic void actual_page(const uint8_t*b,uint32_t generation){unsigned type=1;struct{const uint8_t*bytes;}page={b};${pageProof}}\ntemplate<class F>void refuse(F f){bool denied=false;try{f();}catch(const std::runtime_error&){denied=true;}assert(denied);}\nint main(){${accepted}\n${effects}
 assert(!bw_cold_fetch_domain(24,0,1,0,0,0x7015,1,0x7015,0,1));assert(!bw_cold_fetch_domain(24,1,1,0,0,0x7005,2,0x7005,0,1));assert(!bw_cold_fetch_domain(24,0,1,1,0,0x7005,2,0x7005,0,1));
 assert(bw_protected_read(0x610,0x610,8,1,24,0x7003));assert(bw_protected_read(0x610,0x610,8,1,24,0x7005));assert(bw_protected_read(0x618,0x618,8,1,0xf000,${farJumpIp}));assert(bw_protected_read(0xf0180,0xf0180,6,2,0xf000,${afterLgdt-6}));assert(bw_protected_read(0x8ffe,0x8ffe,2,1,24,0x700e));assert(bw_protected_read(0x8ffe,0x8ffe,2,1,24,0x7019));
 assert(!bw_protected_read(0x610,0x610,8,2,24,0x7003));assert(!bw_protected_read(0x610,0x610,0,1,24,0x7003));assert(!bw_protected_read(0x617,0x617,2,1,24,0x7003));assert(!bw_protected_read(0x8ffe,0x8ffe,2,1,24,0x700f));assert(!bw_protected_read(0x8ffe,0x8ffe,1,1,24,0x700e));assert(!bw_protected_read(0x610,0x611,8,1,24,0x7003));
 uint8_t data[8]={255,255,0,0,0,0x93,0,0},cs[8]={255,255,0,0,0,0x9b,0,0},push[2]={0x34,0x12},call[2]={0x12,0x70};assert(bw_protected_observed(0x610,data,8,24,0x7005));assert(bw_protected_observed(0x618,cs,8,0xf000,${farJumpIp}));assert(!bw_protected_observed(0x610,data,0,24,0x7005));assert(!bw_protected_observed(0x617,data,2,24,0x7005));assert(!bw_protected_observed(0x610,data,8,24,0x7007));assert(bw_protected_observed(0x8ffe,push,2,24,0x700e));assert(bw_protected_observed(0x8ffe,call,2,24,0x7019));assert(!bw_protected_observed(0x8ffe,call,2,24,0x700e));data[5]=0x92;assert(!bw_protected_observed(0x610,data,8,24,0x7005));
 assert(bw_stack_shadow_phase(24,0x7007,true,true));assert(!bw_stack_shadow_phase(24,0x7007,false,true));assert(!bw_stack_shadow_phase(24,0x7007,true,false));assert(bw_stack_shadow_phase(24,0x7005,false,false));assert(bw_stack_shadow_phase(24,0x700a,false,false));assert(!bw_stack_shadow_phase(24,0x700a,true,true));
 uint8_t page[4096]={${ramProgram.join(',')}};actual_page(page,7);page[4095]=1;refuse([&]{actual_page(page,7);});page[4095]=0;refuse([&]{actual_page(page,6);});assert(bw_cold_fetch_page(true,0x7000,0x7000,0,0,1,0x7000,0x7000,0x10,0,7,7,1));assert(!bw_cold_fetch_page(true,0x7000,0x7000,0,0,1,0x7000,0x7000,0x11,0,7,7,1));return 0;}`;
 const d=mkdtempSync(join(tmpdir(),'protected-stack-policy-'));try{writeFileSync(join(d,'fixture.cc'),code);execFileSync('g++',['-std=c++17','-O0','-Wall','-Wextra','-Werror',join(d,'fixture.cc'),'-o',join(d,'fixture')],{timeout:10000});execFileSync(join(d,'fixture'),[],{timeout:5000});}finally{rmSync(d,{recursive:true,force:true});}
});
test('profile/source scope is distinct and the native inhibit method is not an invented snapshot shadow',()=>{
 assert.equal(protectedStackProfile.kind,'fixed-protected-code16-data-stack-call-v1');assert.equal(protectedStackProfile.maxNativeTicks,512);assert.equal(protectedStackProfile.totalNativeTicks,undefined);assert.equal(protectedStackProfile.status,'SOURCE_ONLY_NO_NATIVE_BUILD_OR_ADMISSION');assert.equal(shadowSources.artifact,11283630476);assert.match(shadowSources.eventSha256,/^[a-f0-9]{64}$/);const c=deriveProtectedStackRuntime().bytes.toString();assert.ok(c.includes('cpu->interrupts_inhibited(BX_INHIBIT_INTERRUPTS),cpu->interrupts_inhibited(BX_INHIBIT_DEBUG)'));assert.ok(c.includes(protectedStackProfile.romSha256));assert.equal(c.includes('if(strcmp(sha,"b4e163a3c72cb9986b748cfc92635b6aa11b2f9414a19d4e5c70d27137e9fc83"))return 0;'),false);
});
