import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from 'node:fs';
import {assembleOwnedPicImrRom,picImrWitness}from '../scripts/i80386-free-owned-pic-imr.mjs';
import {assembleOwnedIn8Rom}from '../scripts/i80386-free-owned-in8.mjs';
import {createOwnedPicImrProvider}from '../scripts/bochs-cpu3-native-owned-pic-imr/provider.mjs';
import {deriveOwnedPicImrRuntime}from '../scripts/bochs-cpu3-native-owned-pic-imr/runtime.mjs';
import {deriveOwnedIn8Runtime}from '../scripts/bochs-cpu3-native-owned-in8/runtime.mjs';
const ROM='8a7380f01bbc40985d377fe9764667749c36b05d45ee602b28c7e68556bd509f',empty=()=>new Uint32Array();
function owner(sink=null){const p=createOwnedPicImrProvider({compactSink:sink});p.callbacks.clockTransfer(empty(),1);p.begin();p.callbacks.clockTransfer(empty(),2);return p;}
function out(p,port,value){const r=p.callbacks.packedScalar(3,port,1,value);p.callbacks.clockTransfer(empty(),6);return r;}
function input(p,port){const r=p.callbacks.packedScalar(5,port,1,0);p.callbacks.clockTransfer(empty(),6);return r;}
function pics(snapshot){return {master:snapshot.board.pic1,slave:snapshot.board.pic2};}
function initialize(p){for(const [port,value]of [[0x20,0x11],[0xa0,0x11],[0x21,0x20],[0xa1,0x28],[0x21,4],[0xa1,2],[0x21,1],[0xa1,1],[0xa1,255],[0x21,255]])out(p,port,value);}
test('PIC ROM contains exact masked reads and retains the original fixture elsewhere',()=>{const r=assembleOwnedPicImrRom(),old=readFileSync(new URL('./fixtures/i80386-free-owned-in8.S',import.meta.url),'utf8'),actual=readFileSync(new URL('./fixtures/i80386-free-owned-pic-imr.S',import.meta.url),'utf8');assert.equal(r.sha256,ROM);assert.equal(r.rom.length,65536);assert.equal(r.symbols.setup,0x100);assert.deepEqual([...r.rom.subarray(r.symbols.pic_imr_read_master,r.symbols.pic_imr_read_master+5)],[0xe4,0x21,0xa2,0x92,0x05]);assert.deepEqual([...r.rom.subarray(r.symbols.pic_imr_read_slave,r.symbols.pic_imr_read_slave+5)],[0xe4,0xa1,0xa2,0x93,0x05]);const start=actual.indexOf(' /* Distinct PIC IMR witness:'),end=actual.indexOf(' movb $0xfe,%al',start);assert.ok(start>0&&end>start);const inverse=(actual.slice(0,start)+actual.slice(end)).replace('\n.global pic_imr_read_master,pic_imr_read_slave','');assert.equal(inverse,old);assert.notEqual(r.sha256,assembleOwnedIn8Rom().sha256);assert.deepEqual(picImrWitness.expectedBytes,[255,255]);});
test('new native initializer ROM admission is the only C derivative',()=>{const r=deriveOwnedPicImrRuntime(),base=deriveOwnedIn8Runtime();assert.equal(r.edits.length,1);assert.equal(r.bytes.toString().replace(r.edits[0].next,r.edits[0].old),base.bytes.toString());assert.ok(r.bytes.toString().includes('if(strcmp(sha,"'+ROM+'"))return 0;'));const init=r.bytes.toString().slice(r.bytes.toString().indexOf('extern "C" int bw_direct_initialize('));assert.ok(init.indexOf(ROM)<init.indexOf('compare_exchange_strong'));});
test('candidate owner preserves old typed IN and guards with only fixed fixture substitutions',()=>{let candidate=readFileSync(new URL('../scripts/bochs-cpu3-native-owned-pic-imr/provider.mjs',import.meta.url),'utf8');const original=readFileSync(new URL('../scripts/bochs-cpu3-native-owned-in8/provider.mjs',import.meta.url),'utf8');candidate=candidate.replace("from '../bochs-cpu3-native-owned-in8/reset-witness.mjs'","from './reset-witness.mjs'").replaceAll('assembleOwnedPicImrRom','assembleOwnedIn8Rom').replaceAll('i80386-free-owned-pic-imr.mjs','i80386-free-owned-in8.mjs').replaceAll('createOwnedPicImrProvider','createOwnedIn8Provider').replace(ROM,'25c242668fb1e0cbf940a35045a5e1173d992232766a4cbdb6a369ef3929a939').replace('picImrWitness:Array.from(board.machine.mem.subarray(0x592,0x594)),','');assert.equal(candidate,original);});
for(const port of [0x21,0xa1])test('masked IMR read '+port+' preserves full master/slave state with no ACK or clock charge',()=>{const events=[],p=owner(e=>events.push(e));initialize(p);p.end();const before=p.checkpoint();p.begin();p.callbacks.clockTransfer(empty(),2);const r=input(p,port);p.end();const after=p.checkpoint();assert.deepEqual([...r],[255,before.mappingEpoch,1]);assert.deepEqual(pics(after),pics(before));assert.equal(after.nativeTicks,before.nativeTicks);assert.equal(after.successfulQuanta,before.successfulQuanta);assert.equal(after.board.cycles,before.board.cycles);assert.equal(after.mappingEpoch,before.mappingEpoch);assert.equal(events.filter(e=>e.operation==='inPort').length,1);assert.equal(events.filter(e=>e.operation==='acknowledgeIrq').length,0);p.close();});
for(const port of [0x21,0xa1])test('armed poll '+port+' refusal preserves PIC state after already committed tape clocks',()=>{const events=[],p=owner(e=>events.push(e));initialize(p);out(p,port===0x21?0x20:0xa0,0x0c);p.end();const before=p.checkpoint();assert.equal((port===0x21?before.board.pic1:before.board.pic2).pollPending,true);p.begin();p.callbacks.clockTransfer(empty(),2);p.callbacks.clockTransfer(Uint32Array.of(2,1),5);assert.throws(()=>p.callbacks.packedScalar(5,port,1,0),/no poll/);p.end();const after=p.checkpoint();assert.deepEqual(pics(after),pics(before));assert.equal(after.nativeTicks,before.nativeTicks+1);assert.equal(after.successfulQuanta,before.successfulQuanta+1);assert.equal(after.board.cycles,before.board.cycles+6);assert.equal(after.board.debt,before.board.debt+6);assert.equal(after.mappingEpoch,before.mappingEpoch);assert.equal(events.filter(e=>e.operation==='inPort').length,0);assert.equal(events.filter(e=>e.operation==='acknowledgeIrq').length,0);p.close();});
test('PIC typed read requires exactly one post-PIO query before another callback',()=>{const p=owner();initialize(p);assert.equal(p.callbacks.packedScalar(5,0x21,1,0)[0],255);assert.throws(()=>p.callbacks.packedScalar(5,0xa1,1,0),/lease/);assert.throws(()=>p.end());p.callbacks.clockTransfer(empty(),6);assert.equal(input(p,0xa1)[0],255);p.end();p.close();});
for(const args of [[5,0x20,1,0],[5,0x21,2,0],[5,0xa1,1,1]])test('malformed PIC read denied before event '+args,()=>{const events=[],p=owner(e=>events.push(e));assert.throws(()=>p.callbacks.packedScalar(...args));p.end();assert.equal(events.length,0);p.close();});
