import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync,mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {gunzipSync} from 'node:zlib';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {execFileSync} from 'node:child_process';
import {derivePagedPageFaultRuntime,transformPagedPageFaultRuntime,runtimeParentSha256} from '../scripts/bochs-cpu3-native-paged-pagefault/runtime.mjs';
import {derivePagedPageFaultProvider,transformPagedPageFaultProvider,providerParentSha256} from '../scripts/bochs-cpu3-native-paged-pagefault/provider-derivation.mjs';
import {deriveDriverProvider} from '../scripts/bochs-cpu3-native-paged-pagefault/driver-provider.mjs';
import {nativeWalkOwner,nativeWalkAllowed,validatePageFaultWrite,nativeFrameStores,entries,nativeAdUpdate} from '../scripts/bochs-cpu3-native-paged-pagefault/provider-profile.mjs';
import {validateBuildBinding,requireReadyBuild,requireReadyBinding,driverSourceIdentity,relativeImports,regularBytes} from '../scripts/bochs-cpu3-native-paged-pagefault/driver-auth.mjs';
import {validateInput,derivePageFaultLifecycle,verifyHeldLifecycle,finalizeAuthentication} from '../scripts/bochs-cpu3-native-paged-pagefault/runner.mjs';
import {pageFaultProgress,stepReferenceForReturn,compareBoundary,wholeNativeWords,inspectFields,startOrAdvanceFaultLedger,validateDescriptorRows,validateNativeEffects,validateMemoryTape} from '../scripts/bochs-cpu3-native-paged-pagefault/parity.mjs';
import {bootStores,frameStores,adTransitions,expectedPages,layout,selector,dataSelector,codeCache,dataCache,repairStore,retryStore} from '../scripts/bochs-cpu3-native-paged-pagefault/profile.mjs';
import {sha256} from '../scripts/bochs-cpu3-native-owned-clock/derive.mjs';
const clone=structuredClone;
const pending=JSON.parse(readFileSync(new URL('../scripts/bochs-cpu3-native-paged-pagefault/driver-build-binding.json',import.meta.url)));
let derivedProviderForSourceControls;
// Existing native/board/JS snapshots are manufactured except the labelled genuine saved reset regression below. No provider/oracle factory or CPU is called.
function fixture(fault=false){
 const q=49,N=q+Number(fault),cpu={eax:0x80001234,ecx:0,edx:0,ebx:0,esp:fault?0xdff8:0xe000,ebp:0,esi:0,edi:0,eip:fault?0x7020:0x7003,eflags:2,cr0:0xfffffff1,cr2:fault?0x8000:0,cr3:0x1000,cr4:0,cs:selector,ds:dataSelector,ss:dataSelector,es:0,fs:0,gs:0,gdtr:{base:0x600,limit:31},idtr:{base:0x3000,limit:0x77},debugRegisters:Array(8).fill(0),halted:false,shutdown:false,interruptShadow:0,nmiShadow:0,debugShadow:0,pc:fault?0x7020:0x7003};
 cpu.segmentCaches=[dataCache,codeCache,dataCache,dataCache,dataCache,dataCache].map(c=>({...c}));cpu.ldtr={selector:0,base:0,limit:0,present:false,type:0};cpu.tr={...cpu.ldtr};
 const n={state:['eax','ecx','edx','ebx','esp','ebp','esi','edi','eip','eflags','cr0','cr2','cr3','cs','ds','ss'].map(k=>cpu[k]).concat([0x600,31,0x3000,0x77]),extra:Array(20).fill(0),segments:[],system:Array(30).fill(0),debug:Array(6).fill(0),nativeTicks:String(N),successfulQuanta:String(q),mappingEpoch:0,boardA20:1};
 for(const [i,k]of ['es','cs','ss','ds','fs','gs'].entries()){const s=cpu[k],c=cpu.segmentCaches[i],valid=(i===2||i===3)&&fault?7:1;n.segments.push(i,s,s>>>3,0,0,valid,Number(c.present),0,1,i===1?11:3,c.base>>>0,c.limit>>>0,0,Number(c.default32),0);}
 n.extra.splice(2,6,cpu.es,cpu.fs,cpu.gs,...n.segments.slice(17,20));n.extra[9]=1;n.extra[13]=0;n.extra[14]=65535;n.extra[16]=0;n.system[0]=6;n.system[15]=7;
 n.execution=Object.fromEntries(['attempts','completed','repIterations','repPartial','faults','portCommits','irqDeliveries','haltIdleCuts'].map(k=>[k,String(k==='attempts'?N:k==='completed'?q:k==='faults'?Number(fault):0)]));n.fallback=Object.fromEntries(['bochsRamReads','bochsRamWrites','bochsDirectPointers','bochsPio','bochsTimer'].map(k=>[k,'0']));n.callbacks=Object.fromEntries(['physicalReads','physicalWrites','executePages','nativeTickCallbacks','quantumCallbacks'].map(k=>[k,'0']));n.clockTransfers={transfers:'0',commits:'0',words:'0'};
 const stores=[...bootStores,...(fault?frameStores:[])].map(w=>({...w,bytes:[...w.bytes]})),updates=adTransitions.slice(0,fault?7:4),pages=expectedPages(stores,updates),js={q,attemptOrdinal:N,faultSerial:Number(fault),cpu,board:{cycles:298,a20Enabled:true},pages:clone(pages),stores,updates,deliveries:fault?[{vector:14,returnEip:0x7003,errorCode:2,fault:true,cr2:0x8000,cs:selector,eip:0x7020,esp:0xdff8,eflags:2,q:49,attemptOrdinal:50}]:[]};
 const ads=Object.values(entries).filter(e=>e.raw!==entries.data.raw&&(![entries.idt.raw,entries.table.raw,entries.stack.raw].includes(e.raw)||fault&&e.raw!==entries.table.raw)).map(e=>({kind:'ad',raw:e.raw,before:e.value,after:e.value|(e.raw===entries.stack.raw?0x60:0x20),bytes:[]}));for(const e of ads)e.bytes=[e.after&255,e.after>>>8&255,e.after>>>16&255,e.after>>>24];
 const writes=[...bootStores.map(w=>({kind:'boot',raw:w.raw,bytes:[...w.bytes]})),...ads,...(fault?nativeFrameStores.map(w=>({kind:'frame',raw:w.raw,bytes:[...w.bytes]})):[])],board={nativeTicks:N,successfulQuanta:q,board:clone(js.board),ram:{writes,reads:[],bootStores:31,frameWords:fault?4:0,storeCount:writes.length,repaired:false,dataWritten:false,admitted:true}};
 return {n,js,pages,board};
}
function returned(n,reason=1,dn=1,dq=1){n=clone(n);Object.assign(n,{reason,activityState:0,chargedNativeTicks:dn,chargedQuanta:dq,sliceBytes:new Uint8Array(160)});const v=new DataView(n.sliceBytes.buffer),u=(o,x)=>v.setUint32(o,x,true);for(const [o,x]of [[0,reason],[4,1],[8,1],[12,dn],[16,1],[20,dq]])u(o,x);for(const [i,k]of ['nativeTicks','successfulQuanta',...Object.keys(n.execution)].entries())v.setBigUint64(24+8*i,BigInt(i<2?n[k]:n.execution[k]),true);v.setUint16(104,n.state[13],true);u(108,n.state[8]);if(reason===2)for(const [o,x]of [[112,1],[116,14],[120,2],[124,0x8000]])u(o,x);return n;}
test('fresh PF build authority and manufactured pending old addon refusals before factories',()=>{
 assert.equal(validateBuildBinding(pending),pending);assert.equal(requireReadyBuild().addonSha256,'14bc8ef0e06030203ec642537846eb78388f857f8728cb201942f6eb9daf35c0');
 const unbuilt={...clone(pending),status:'PENDING_NATIVE_FAULT_RUNTIME_BUILD_AND_EXECUTION',compiledRevision:null,compiledSourceSha256:null,compiledFiles:{},generated:{},addonSha256:null,buildRun:null,artifactId:null,staticAuthority:null};assert.equal(validateBuildBinding(unbuilt),unbuilt);assert.throws(()=>requireReadyBinding(unbuilt),/pending/);
 for(const change of [b=>b.status='ROOT_REVIEWED_PF_BUILD',b=>b.addonSha256='92a5121df194c6675303913ebd527e7d0253e29e686b2cbd8dd91fb579489b6f',b=>b.abiVersion=5,b=>b.compiledFiles['fake']='0'.repeat(64),b=>b.staticAuthority.preparedManifestSha256='0'.repeat(64)]){const b=clone(pending);change(b);assert.throws(()=>validateBuildBinding(b));}
 const input={compiledRoot:'/owned/compiled',compiledRevision:pending.compiledRevision,driverRevision:'f'.repeat(40),driverSourceSha256:'c'.repeat(64),addon:'/owned/addon',sha256:pending.addonSha256,configuration:'/owned/config',preparedManifest:'/owned/prepare',preparedManifestSha256:pending.staticAuthority.preparedManifestSha256,buildReceipt:'/owned/receipt',buildReceiptSha256:pending.staticAuthority.buildReceiptSha256,output:'/owned/output',nativeTrace:false};assert.equal(validateInput(input),input);assert.throws(()=>validateInput({...input,sha256:'92a5121df194c6675303913ebd527e7d0253e29e686b2cbd8dd91fb579489b6f'}));
});
test('new runtime and provider preserve exact held derivatives and unknown source refuses',()=>{
 const r=derivePagedPageFaultRuntime(),p=derivePagedPageFaultProvider(),a=deriveDriverProvider(p.bytes);derivedProviderForSourceControls=p.bytes;assert.equal(r.baseSha256,runtimeParentSha256);assert.equal(p.baseSha256,providerParentSha256);assert.equal(a.parentSha256,sha256(p.bytes));
 for(const [bytes,transform]of [[Buffer.from('unknown runtime'),transformPagedPageFaultRuntime],[Buffer.from('unknown provider'),transformPagedPageFaultProvider],[Buffer.from('unknown adapter'),deriveDriverProvider]])assert.throws(()=>transform(bytes));
 const source=r.bytes.toString();assert.ok(source.indexOf('static void bw_pf_observe_tlb(void);')<source.indexOf('void bw_slice_note_tlb_flush(void)'));assert.ok(source.indexOf('static bool bw_pf_fault_allowed(')<source.indexOf('void bw_slice_note_fault('));assert.match(source,/fault-delivery-clock/);assert.match(source,/fixed-PF-delivered-frame-state/);assert.match(source,/PF-completed-owner-phase/);assert.ok(!source.includes('bw_slice_fail("cold-BIOS-no-fault")'));
 const held=readFileSync(new URL('../scripts/bochs-cpu3-native-paged-int-iret/runner.mjs',import.meta.url));assert.ok(derivePageFaultLifecycle(held).toString().includes('stepReferenceForReturn(oracle,next)'));verifyHeldLifecycle();
});
test('delivery and failed operand owners cannot be confused with generic prefetch',()=>{
 assert.equal(nativeWalkOwner(24,0x7003,24,0x7003,1).phase,'fault-delivery');assert.equal(nativeWalkOwner(24,0x7006,24,0x7003,0).phase,'fault-or-retry-write');assert.equal(nativeWalkOwner(24,0x7029,24,0x7020,0).phase,'handler-PTE-repair');
 assert.ok(nativeWalkAllowed(2,entries.idt.raw,4,24,0x7003,24,0x7003,1));assert.equal(nativeWalkAllowed(2,entries.code.raw,4,24,0x7003,24,0x7003,1),false);assert.equal(nativeWalkAllowed(2,entries.data.raw,4,24,0x7006,24,0x7000,0),false);assert.equal(nativeWalkAllowed(2,entries.code.raw,4,24,0x7006,24,0x7003,0),false);assert.equal(nativeWalkAllowed(2,entries.idt.raw,3,24,0x7003,24,0x7003,1),false);assert.equal(nativeWalkAllowed(2,entries.idt.raw,4,24,0x7003,24,0x7000,1),false);
 const state={boot:31,admitted:true,frameWords:0,repaired:false,dataWritten:false,tableValues:{[entries.stack.raw]:0xc063,[entries.table.raw]:0x2063,[entries.data.raw]:0}};for(const e of nativeFrameStores){assert.equal(validatePageFaultWrite(e.raw,Uint8Array.from(e.bytes),state).kind,'frame');state.frameWords++;}assert.throws(()=>validatePageFaultWrite(nativeFrameStores[0].raw,Uint8Array.from(nativeFrameStores[0].bytes),state));assert.throws(()=>validatePageFaultWrite(retryStore.raw,Uint8Array.from(retryStore.bytes),state));assert.equal(validatePageFaultWrite(repairStore.raw,Uint8Array.from(repairStore.bytes),state).kind,'repair');assert.throws(()=>nativeAdUpdate(entries.data.raw,0,0x60));
});
test('FAULT N1 Q0 steps the genuine-reference interface exactly once while prefetch does not',()=>{
 const f=fixture(true),r=returned(f.n,2,1,0),p=pageFaultProgress({n:49,q:49,faults:0},r);assert.deepEqual([p.classification,p.n,p.q,p.attemptOrdinal],['EXACT_SINGLE_FAULT_DELIVERY',50,49,50]);let calls=0;const oracle={step(){calls++;return {attemptOrdinal:50,q:49,completed:0,faultDelivered:true};}};stepReferenceForReturn(oracle,p);assert.equal(calls,1);
 stepReferenceForReturn(oracle,{classification:'PREFETCH_RAW_UNMATCHED'});assert.equal(calls,1);assert.throws(()=>stepReferenceForReturn({step(){return {attemptOrdinal:50,q:50,completed:1,faultDelivered:false};}},p));assert.throws(()=>pageFaultProgress({n:50,q:49,faults:1},r));const bad=clone(r);new DataView(bad.sliceBytes.buffer).setUint32(120,0,true);assert.throws(()=>pageFaultProgress({n:49,q:49,faults:0},bad));
 const b=fixture(false),prefetch=returned(b.n,1,0,0);assert.equal(pageFaultProgress({n:49,q:49,faults:0},prefetch).classification,'PREFETCH_RAW_UNMATCHED');assert.equal(startOrAdvanceFaultLedger(null,b.n,r,b.pages,f.pages).faultSerial,1);const pages=clone(f.pages);pages.data[0]=0x34;assert.throws(()=>startOrAdvanceFaultLedger(null,b.n,r,b.pages,pages));
 // Actual production bodies, extracted from authenticated generated source, run on a manufactured clock-only board.
 // No SourcePagedPageFaultBoard constructor, actual machine/provider factory or CPU is used.
 const source=(derivedProviderForSourceControls??derivePagedPageFaultProvider().bytes).toString(),stateStart=source.indexOf(' const state=()=>'),stateEnd=source.indexOf(' const callback=',stateStart),clockStart=source.indexOf('  clockTransfer(words,reason){'),clockEnd=source.indexOf('\n });\n return Object.freeze',clockStart);assert.ok(stateStart>=0&&stateEnd>stateStart&&clockStart>=0&&clockEnd>clockStart);
 const tick=source.match(/^ nativeTick\(\)\{.*\}$/m),quantum=source.match(/^ quantum\(kind\)\{.*\}$/m);assert.ok(tick&&quantum);assert.equal(source.split(tick[0]).length-1,1);assert.equal(source.split(quantum[0]).length-1,1);
 const machine={cycles:4+6*49,_chipDebt:6*49,_chipDeadline:6000,_a20Enabled:true},board={nativeTicks:49,successfulQuanta:49,mappingEpoch:0,machine,_call(k,args,fn){return fn();}};
 Object.assign(board,Function('assert','coldBoardProfile','return ({'+tick[0]+','+quantum[0]+'});')(assert,{maxNativeTicks:512,maxQuanta:512}));
 const call=(k,args=[])=>Reflect.apply(board[k],board,args),clock=Function('assert','board','call','coldBoardProfile',`let lease=true,closed=false,initialized=true,entry=false,postPio=false,mappingPending=false,active=false,n=0,q=0;${source.slice(stateStart,stateEnd)}return ({${source.slice(clockStart,clockEnd)}}).clockTransfer;`)(assert,board,call,{maxNativeTicks:512,maxQuanta:512});
 assert.deepEqual([...clock(Uint32Array.of(1),8)],[50,49,298,294,6000,0,1],'N-only fault leaves Q/device clock unchanged');
 for(let i=0;i<7;i++){const state=clock(Uint32Array.of(1,2),4);assert.deepEqual([...state],[51+i,50+i,4+6*(50+i),6*(50+i),6000,0,1],'following instructions preserve exactly one permanent N-Q offset');}
 const prior=clone({n:board.nativeTicks,q:board.successfulQuanta,cycles:machine.cycles,debt:machine._chipDebt});assert.throws(()=>clock(Uint32Array.of(1,9),4));assert.deepEqual({n:board.nativeTicks,q:board.successfulQuanta,cycles:machine.cycles,debt:machine._chipDebt},prior,'whole tape preflight rejects before any effect');
});
test('comparable wholeboards ten pages and native cache rows remain strict with unmatched prefetch raw',()=>{
 const f=fixture(true),n=returned(f.n,2,1,0);for(const key of Object.keys(layout)){assert.notStrictEqual(f.pages[key],f.js.pages[key],'independent manufactured native/JS page '+key);assert.notStrictEqual(f.pages[key].buffer,f.js.pages[key].buffer);}assert.equal(compareBoundary(n,f.board,f.js,f.pages,'resume','EXACT_SINGLE_FAULT_DELIVERY').status,'COMPARABLE_PARITY_PASS');
 for(const change of [x=>x.pages.code[4095]=1,x=>x.board.board.cycles++,x=>x.n.segments[35]=1,x=>x.n.segments[50]=3,x=>x.n.state[0]^=1]){const x=clone(f);change(x);assert.throws(()=>compareBoundary(x.n,x.board,x.js,x.pages,'resume','EXACT_SINGLE_FAULT_DELIVERY'));}
 const p=clone(f.pages);p.table[4095]=1;const b=clone(f.board);b.board.cycles++;assert.equal(compareBoundary(f.n,b,f.js,p,'resume','PREFETCH_RAW_UNMATCHED').status,'UNMATCHED_PHASE');assert.throws(()=>validateDescriptorRows({...f.n,segments:f.n.segments.map((v,i)=>i===20?3:v)},f.js,f.board));
});
test('native frame and A D tapes are independent yet cannot smuggle extra writes or lost callbacks',()=>{
 const f=fixture(true);assert.equal(validateNativeEffects(f.board,f.js).frameWrites,4);const reversed=clone(f.board);reversed.ram.writes=reversed.ram.writes.map(w=>w.kind==='frame'?{...w,bytes:[...w.bytes]}:w);const frames=reversed.ram.writes.filter(w=>w.kind==='frame');[frames[0].raw,frames[3].raw]=[frames[3].raw,frames[0].raw];assert.throws(()=>validateNativeEffects(reversed,f.js));
 const unknown=clone(f.board);unknown.ram.writes.push({kind:'unknown',raw:0,bytes:[1]});assert.throws(()=>validateNativeEffects(unknown,f.js));const events=f.board.ram.writes.map((w,i)=>({...w,direction:'write',ordinal:i,generation:i,nativeTicks:49,successfulQuanta:49})),board=clone(f.board);board.ram.writes=events.map(({direction,ordinal,...w})=>w);assert.equal(validateMemoryTape(events,board).events,events.length);assert.throws(()=>validateMemoryTape(events.slice(1),board));
});
test('all-outcome authentication retains primary failure independently of missing or changed guards',()=>{
 const before=Object.fromEntries(['input','driver','compiled','build','configuration','node'].map(k=>[k,k])),receipt={status:'PASS'},primary=Error('first divergence');assert.equal(finalizeAuthentication(receipt,primary,before,{...before,input:'changed'}),primary);assert.equal(receipt.status,'FAIL');assert.match(receipt.finalAuthenticationError,/final input/);const missing={...before};delete missing.configuration;assert.ok(finalizeAuthentication({status:'PASS'},null,before,missing));assert.equal(finalizeAuthentication({status:'PASS'},null,before,{...before}),null);
});
test('frozen source identity includes real fault policy and held multiline checkpoint import',async()=>{
 const root=fileURLToPath(new URL('../',import.meta.url)),head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),paths=new Map();
 // Same explicit dynamic seeds as the held production identity. Authenticate caller bytes even when unrelated CI setup is dirty.
 const seeds=['scripts/bochs-cpu3-native-paged-pagefault/runner.mjs','scripts/bochs-cpu3-native-paged-pagefault/NATIVE-DRIVER-SOURCE.md','scripts/bochs-cpu3-native-paged-pagefault/driver-build-binding.json','scripts/bochs-cpu3-native-paged-pagefault/runtime.mjs','scripts/bochs-cpu3-native-paged-pagefault/saved-js-fault-phases.json','scripts/bochs-cpu3-native-paged-pagefault/actual-first-pf-build-prepare.json.gz','scripts/bochs-cpu3-native-paged-pagefault/actual-first-pf-reset-failure.json.gz','test/i80386-paged-pagefault-native-runtime-driver.test.mjs','scripts/bochs-cpu3-native-paged-int-iret/runner.mjs','scripts/bochs-cpu3-native-cold-bios/board-provider.mjs','scripts/bochs-cpu3-native-direct-board/runtime.inc','scripts/bochs-cpu3-native-owned-clock/clock.inc','scripts/bochs-cpu3-native-owned-clock/abi.h','src/experimental/i80386.js','package.json','roms/free-at-bios/LICENSE','roms/free-at-bios/BIOS-bochs-legacy','roms/free-at-bios/vgabios-lgpl.bin'];
 function visit(name){if(paths.has(name))return;const path=resolve(root,name);assert.ok(path.startsWith(root));const b=readFileSync(path),g=execFileSync('git',['show',head+':'+name],{cwd:root,maxBuffer:32<<20});assert.equal(sha256(b),sha256(g),'caller current/Git '+name);paths.set(name,sha256(b));if(/\.(mjs|js)$/.test(name))for(const relative of relativeImports(b))visit(resolve(dirname(path),relative).slice(root.length));}
 for(const name of seeds)visit(name);
 const callerStatus=execFileSync('git',['status','--porcelain'],{cwd:root,encoding:'utf8'}),d=mkdtempSync(join(tmpdir(),'paged-pf-driver-identity-')),clean=join(d,'source');
 try{
  mkdirSync(clean);execFileSync('git',['init','--quiet',clean],{timeout:10000});const objects=execFileSync('git',['rev-parse','--path-format=absolute','--git-path','objects'],{cwd:root,encoding:'utf8'}).trim();writeFileSync(join(clean,'.git/objects/info/alternates'),objects+'\n');
  const shallow=execFileSync('git',['rev-parse','--path-format=absolute','--git-path','shallow'],{cwd:root,encoding:'utf8'}).trim();try{writeFileSync(join(clean,'.git/shallow'),readFileSync(shallow));}catch(e){if(e.code!=='ENOENT')throw e;}
  execFileSync('git',['update-ref','HEAD',head],{cwd:clean,timeout:10000});execFileSync('git',['sparse-checkout','init','--no-cone'],{cwd:clean,timeout:10000});execFileSync('git',['sparse-checkout','set','--no-cone','--stdin'],{cwd:clean,input:[...paths.keys()].sort().map(p=>'/'+p).join('\n')+'\n',timeout:10000});execFileSync('git',['checkout','--quiet','--detach',head],{cwd:clean,timeout:10000});
  const owned=await import(pathToFileURL(join(clean,'scripts/bochs-cpu3-native-paged-pagefault/driver-auth.mjs')).href),identity=owned.driverSourceIdentity();assert.equal(identity.revision,head);assert.deepEqual(identity.hashes,Object.fromEntries([...paths].sort(([a],[b])=>a.localeCompare(b))));
  assert.ok(identity.hashes['scripts/bochs-cpu3-native-paged-pagefault/runtime.mjs']);assert.ok(identity.hashes['scripts/bochs-cpu3-native-paged-pagefault/native-fault-policy.mjs']);assert.ok(identity.hashes['src/machine-checkpoint.js']);assert.ok(identity.hashes['scripts/bochs-cpu3-native-paged-int-iret/evidence.mjs']);assert.ok(identity.hashes['src/experimental/i80386.js']);
  // Manufacture the observed CI dirt only in the owned fixture; the production guard must still refuse it.
  execFileSync('git',['sparse-checkout','add','/package-lock.json'],{cwd:clean,timeout:10000});const lock=join(clean,'package-lock.json');writeFileSync(lock,readFileSync(lock).toString()+'\n');mkdirSync(join(clean,'blinkenrocket-firmware'));writeFileSync(join(clean,'blinkenrocket-firmware/fixture'),'owned CI setup marker');assert.throws(()=>owned.driverSourceIdentity(),/clean frozen PF driver/);
 }finally{rmSync(d,{recursive:true,force:true});assert.equal(execFileSync('git',['status','--porcelain'],{cwd:root,encoding:'utf8'}),callerStatus,'caller Git status unchanged');}
});

test('genuine first PF manifest exceeds held cap and is admitted by bounded four MiB source seam',()=>{
 const fixture=readFileSync(new URL('../scripts/bochs-cpu3-native-paged-pagefault/actual-first-pf-build-prepare.json.gz',import.meta.url));assert.ok(fixture.length<(1<<20));const raw=gunzipSync(fixture,{maxOutputLength:4<<20});assert.equal(raw.length,2135534);assert.equal(sha256(raw),'b1268ecffc11ae4704f3df95bb92fa3bbf60a18111e74383f99ff8ce58503d53');assert.ok(raw.length>(2<<20));
 const d=mkdtempSync(join(tmpdir(),'paged-pf-manifest-cap-'));try{const p=join(d,'prepare.json');writeFileSync(p,raw);assert.throws(()=>regularBytes(p,2<<20));assert.deepEqual(regularBytes(p,4<<20),raw);const manifest=JSON.parse(regularBytes(p,4<<20));assert.equal(manifest.schema,'bw.paged-pagefault.prepared.v1');assert.equal(manifest.boardRevision,'5df525f72790876d35e49d936bac1f1284fa81e7');assert.equal(Object.keys(manifest.sourceHashes).length,243);assert.deepEqual(manifest.actualPreparedHashes,pending.generated);}finally{rmSync(d,{recursive:true,force:true});}
 const held=readFileSync(new URL('../scripts/bochs-cpu3-native-paged-int-iret/runner.mjs',import.meta.url)),derived=derivePageFaultLifecycle(held).toString();assert.ok(derived.includes('regularBytes(input.preparedManifest,4<<20)'));assert.ok(!derived.includes('regularBytes(input.preparedManifest,2<<20)'));verifyHeldLifecycle();
});


// Exact compressed body from the failed first native run, not a guest replay. Only ABI uint64
// metadata is restored to its live BigInt type; raw166 words and board clocks remain Numbers.
function liveCounters(n){const live=clone(n);for(const k of ['nativeTicks','successfulQuanta'])live[k]=BigInt(live[k]);for(const k of ['execution','fallback','callbacks','clockTransfers'])for(const f of Object.keys(live[k]))live[k][f]=BigInt(live[k][f]);return live;}
test('genuine saved reset restores live BigInt metadata without weakening canonical bounds or raw words',()=>{
 const compressed=readFileSync(new URL('../scripts/bochs-cpu3-native-paged-pagefault/actual-first-pf-reset-failure.json.gz',import.meta.url));assert.equal(compressed.length,32925);assert.equal(sha256(compressed),'be7b1b76d32a243bdc582633351f92ae80749bd118d07b7cdef1b03babbdd7fb');
 const raw=gunzipSync(compressed,{maxOutputLength:1<<20});assert.equal(raw.length,354506);assert.equal(sha256(raw),'d9f3c4e9cf2544cbf9d7be9b53b5d4553cd1d346e141a98622db28ffbd72778a');const saved=JSON.parse(raw);assert.equal(saved.status,'FAIL');assert.match(saved.error,/'bigint' !== 'string'/);assert.deepEqual(saved.progress,{n:0,q:0,faults:0,attemptOrdinal:0,resumes:0,zeroQ:0});assert.deepEqual(saved.boundaries,[]);
 const persisted=saved.lastSuccessfullyReturnedNative,live=liveCounters(persisted),board=saved.partialProvider.state,js=clone(saved.partialJavascript),pages=Object.fromEntries(Object.entries(saved.partialProvider.pages).map(([k,p])=>[k,Uint8Array.from(p)]));js.pages=Object.fromEntries(Object.entries(js.pages).map(([k,p])=>[k,Uint8Array.from(p)]));
 assert.deepEqual(wholeNativeWords(live),wholeNativeWords(persisted));assert.equal(wholeNativeWords(live).length,166);assert.equal(compareBoundary(live,board,js,pages,'reset').status,'COMPARABLE_PARITY_PASS');assert.equal(compareBoundary(persisted,board,js,pages,'reset').status,'COMPARABLE_PARITY_PASS');
 const prefetch=returned(live,1,0,0);assert.equal(pageFaultProgress({n:0,q:0,faults:0},prefetch).classification,'PREFETCH_RAW_UNMATCHED');assert.deepEqual(wholeNativeWords(prefetch),wholeNativeWords(live));
 const f=fixture(true),fault=returned(liveCounters(f.n),2,1,0);assert.deepEqual(pageFaultProgress({n:49,q:49,faults:0},fault),pageFaultProgress({n:49,q:49,faults:0},returned(f.n,2,1,0)),'manufactured returned ABI fault metadata retains exact accounting under both representations');
 for(const invalid of [0,0.5,null,false,{},[],'','00',' 0','+0','-1','0x0','0.0','1e0',-1n,513n,'513']){const n=clone(live);n.nativeTicks=invalid;assert.throws(()=>wholeNativeWords(n));assert.throws(()=>compareBoundary(n,board,js,pages,'reset'));}
 for(const invalid of [0,'01',-1n,1_000_001n,'1000001']){const n=clone(live);n.callbacks.physicalReads=invalid;assert.throws(()=>wholeNativeWords(n));}for(const maximum of [1_000_000n,'1000000']){const n=clone(live);n.callbacks.physicalReads=maximum;assert.equal(wholeNativeWords(n).length,166);}
 const badWord=clone(live);badWord.state[0]=BigInt(badWord.state[0]);assert.throws(()=>wholeNativeWords(badWord),'raw uint32 words remain Numbers');const wrongPage=clone(pages);wrongPage.code[4095]^=1;assert.throws(()=>compareBoundary(live,board,js,wrongPage,'reset'),'genuine whole page guard unchanged');
});
