import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {execFileSync} from 'node:child_process';
import {deriveNonidentityPagingRuntime} from '../scripts/bochs-cpu3-native-nonidentity-paging/runtime.mjs';
import {deriveNonidentityPagingProvider} from '../scripts/bochs-cpu3-native-nonidentity-paging/provider-derivation.mjs';
import {derivePagedIntIretRuntime,transformPagedIntIretRuntime,runtimeParentSha256} from '../scripts/bochs-cpu3-native-paged-int-iret/runtime.mjs';
import {derivePagedIntIretProvider,transformPagedIntIretProvider,createOwnedPagedIntIretProvider,providerParentSha256} from '../scripts/bochs-cpu3-native-paged-int-iret/provider-derivation.mjs';
import {nativeIntIretProfile,nativeWalkAllowed,nativeWalkOwner,walkOwners,validateIntRead,validateIntWrite,nativeAdUpdate,expectedRamPage,generationBeforeBoot,nativeFrameStores,nativeShadowPhase} from '../scripts/bochs-cpu3-native-paged-int-iret/provider-profile.mjs';
import {entries,bootStores,ramProgram,dword,farJumpIp,afterSs,expectedPages,layout} from '../scripts/bochs-cpu3-native-paged-int-iret/profile.mjs';
import {replacement,sha256} from '../scripts/bochs-cpu3-native-owned-clock/derive.mjs';
function inverse(d){let s=d.bytes.toString();for(const e of [...d.edits].reverse())if(e.count){assert.equal(s.split(e.next).length-1,e.count);s=s.split(e.next).join(e.old);}else s=replacement(s,e.next,e.old,'test inverse');return Buffer.from(s);}
const state=()=>({boot:0,admitted:false,frameWords:0,tableValues:Object.fromEntries(Object.values(entries).map(e=>[e.raw,e.value]))});
const nativeAd=[[0x1000,0x2023],[0x23c0,0xf0023],[0x2000,0x23],[0x201c,0xa023],[0x200c,0x3023],[0x2034,0xc063]];
test('INT runtime/provider source authenticates held hashes and exact full inverses',()=>{
 const c=derivePagedIntIretRuntime(),p=derivePagedIntIretProvider();assert.equal(sha256(inverse(c)),runtimeParentSha256);assert.equal(sha256(inverse(p)),providerParentSha256);
 for(const [f,b]of [[transformPagedIntIretRuntime,deriveNonidentityPagingRuntime().bytes],[transformPagedIntIretProvider,deriveNonidentityPagingProvider().bytes]]){assert.throws(()=>f(Buffer.from('unknown')));assert.throws(()=>f(Buffer.concat([b,Buffer.from('\n')])));}
 for(const guard of ['current-code-write','admitted-unexecuted-code-write','executable-table-ad-write','execute-cache-generation','coherence-pending-boundary','paging-physical-fetch','paging-observed-bytes','paging-CR0-CR3-phase','paged-INT-shadow-phase'])assert.ok(c.bytes.includes(guard));assert.ok(c.bytes.indexOf('static bool bw_paging_store')<c.bytes.indexOf('static const uint8_t *bw_host_execute'));assert.ok(c.bytes.includes(nativeIntIretProfile.romSha256));assert.equal(nativeIntIretProfile.status,'SOURCE_ONLY_NO_PREPARATION_BUILD_OR_GUEST');assert.equal(nativeIntIretProfile.maxQuanta,512);assert.notEqual(nativeIntIretProfile.romSha256,'7be28f0fabe164ab69d362b5e14b86181d8588e227bbc314f9204501101add35');
 console.log(JSON.stringify({scope:'generated source only; no build/addon/CPU',runtimeSha256:sha256(c.bytes),providerSha256:sha256(p.bytes),romSha256:nativeIntIretProfile.romSha256}));
});
test('native gate/frame walk phases and combined AD refuse wrong owner/address/value/shadow',()=>{
 for(const o of walkOwners){const [cs,ip]=o.attempt?[o.attempt.cs,o.attempt.ip]:[0xf000,0x123];assert.equal(nativeWalkOwner(o.liveCs,o.liveIp,cs,ip)?.phase,o.phase);for(const raw of [0x1000,...o.leaves]){const read=raw===0x1000?1:2;assert.equal(nativeWalkAllowed(read,raw,4,o.liveCs,o.liveIp,cs,ip),true);assert.equal(nativeWalkAllowed(read,raw,0,o.liveCs,o.liveIp,cs,ip),false);assert.equal(nativeWalkAllowed(read,raw+1,4,o.liveCs,o.liveIp,cs,ip),false);assert.equal(nativeWalkAllowed(read,raw,4,o.liveCs^1,o.liveIp,cs,ip),false);}if(o.attempt)assert.equal(nativeWalkOwner(o.liveCs,o.liveIp,cs,ip+1),null);}
 nativeAdUpdate(0x2034,0xc003,0xc063);for(const a of [[0x2034,0xc003,0xc023],[0x2034,0xc023,0xc063],[0x201c,0xa023,0xa063],[0x200c,0x3023,0x3063],[0x1000,0x2023,0x2063],[0x2038,0xc003,0xc063]])assert.throws(()=>nativeAdUpdate(...a));
 assert.equal(nativeWalkAllowed(4,0x2034,4,24,0x7005,24,0x7003),true);assert.equal(nativeWalkAllowed(4,0x2034,4,24,0x7014,24,0x7013),true,'entry address read/write kind shape; exact D phase enforced by C store');assert.equal(nativeWalkAllowed(4,0x2034,4,24,0x7000,0,0),false);
 assert.equal(nativeShadowPhase(0xf000,afterSs,true,true),true);assert.equal(nativeShadowPhase(0xf000,afterSs,false,false),false);assert.equal(nativeShadowPhase(24,0x7003,false,false),true);assert.equal(nativeShadowPhase(24,0x7003,true,false),false);
});
test('native host predicates own all boot writes, exactly FLAGS/CS/IP words and legal read spans',()=>{
 const s=state();for(const e of bootStores){const old=structuredClone(s);const bad=Uint8Array.from(e.bytes);bad[0]^=1;assert.throws(()=>validateIntWrite(e.raw,bad,s));assert.deepEqual(s,old);s.boot=validateIntWrite(e.raw,Uint8Array.from(e.bytes),s).nextBoot;}
 assert.throws(()=>validateIntWrite(0xcffe,Uint8Array.of(2,0),s));for(const [raw,value]of nativeAd){const n=validateIntWrite(raw,dword(value),s);assert.equal(n.kind,'ad');s.tableValues[raw]=n.after;}s.admitted=true;
 for(const e of nativeFrameStores){assert.throws(()=>validateIntWrite(e.raw+1,Uint8Array.from(e.bytes),s));const n=validateIntWrite(e.raw,Uint8Array.from(e.bytes),s);assert.equal(n.kind,'frame');s.frameWords=n.nextFrameWords;}assert.throws(()=>validateIntWrite(0xcffa,Uint8Array.of(5,0x70),s));assert.throws(()=>validateIntWrite(0xa000,Uint8Array.of(0),s));
 for(const a of [[0xf0406,6],[0x3180,8],[0xcffa,2],[0xcffc,2],[0xcffe,2],[0x2034,4],[0x618,8]])validateIntRead(...a);for(const a of [[0x3180,0],[0x3187,2],[0xdffa,2],[0x8000,4],[0x2034,3],[0xcfff,2],[0xf040b,2]])assert.throws(()=>validateIntRead(...a));assert.equal(Object.keys(layout).length,10);
});
function functionText(s,name){const at=s.indexOf(name);assert.ok(at>=0);const brace=s.indexOf('{',at);let n=1,i=brace+1;for(;n&&i<s.length;i++){if(s[i]==='{')n++;if(s[i]==='}')n--;}assert.equal(n,0);return s.slice(at,i);}
test('tiny nonguest C fixture exercises actual generated boot/gate/frame/AD/fetch/shadow predicates',()=>{
 const source=derivePagedIntIretRuntime().bytes.toString(),from=source.indexOf('static unsigned bw_paging_boot=0'),to=source.indexOf('static int bw_host_memory(',from);assert.ok(from>=0&&to>from);const helpers=source.slice(from,to),domain=functionText(source,'static bool bw_cold_fetch_domain'),page=functionText(source,'static bool bw_cold_fetch_page');
 const boot=bootStores.map((e,i)=>`{uint8_t b[4]={${e.bytes}};assert(!bw_paging_store(${e.raw},${e.raw},4,b,${generationBeforeBoot[i]},0xf000,${e.ip+1},0,0,0));assert(bw_paging_store(${e.raw},${e.raw},4,b,${generationBeforeBoot[i]},0xf000,${e.ip},0,0,0));bw_paging_commit(${e.raw},b,0);}`).join('\n');
 const frames=nativeFrameStores.map((e,i)=>`{uint8_t b[2]={${e.bytes}};assert(!bw_paging_store(${e.raw},${e.raw},2,b,${i},24,0x7003,0,24,0x7010));assert(!bw_paging_store(${e.raw},${e.raw},2,b,${i},24,0x7000,0,24,0x7005));assert(bw_paging_store(${e.raw},${e.raw},2,b,${i},24,0x7003,0,24,0x7005));bw_paging_commit(${e.raw},b,0);}`).join('\n');
 const code=`#include <cstdint>\n#include <cstring>\n#include <stdexcept>\n#include <cassert>\nstatic void bw_slice_fail(const char*s){throw std::runtime_error(s);}\n${helpers}\n${domain}\n${page}\nint main(){${boot}
 assert(bw_paging_boot==20);uint8_t ad[4]={0x63,0xc0,0,0};assert(!bw_paging_store(0x2034,0x2034,4,ad,5,24,0x7013,4,24,0x7014));assert(!bw_paging_store(0x2034,0x2034,4,ad,5,24,0x7003,2,24,0x7005));assert(!bw_paging_store(0x2034,0x2034,4,ad,5,24,0x7003,4,24,0x7010));assert(bw_paging_store(0x2034,0x2034,4,ad,5,24,0x7003,4,24,0x7005));bw_paging_commit(0x2034,ad,4);assert(!bw_paging_ad(0x2034,ad,4));
 ${frames}
 assert(bw_int_frame_words==3);assert(!bw_paging_store(0xcffa,0xcffa,2,ad,3,24,0x7003,0,24,0x7005));
 uint8_t gate[8]={0x10,0x70,24,0,0,0x86,0,0},frame[6]={5,0x70,24,0,2,0};assert(bw_paging_read(0x3180,0x3180,8,1,24,0x7003,0,24,0x7005));assert(!bw_paging_read(0x3180,0x3180,8,1,24,0x7003,0,24,0x7010));assert(!bw_paging_read(0x3180,0x3180,8,1,24,0x7013,0,24,0x7014));assert(!bw_paging_read(0x3180,0x3180,0,1,24,0x7003,0,24,0x7005));assert(bw_paging_observed(0x3180,gate,8,24,0x7003,0));gate[5]=0x8e;assert(!bw_paging_observed(0x3180,gate,8,24,0x7003,0));assert(bw_paging_observed(0xcffa,frame,6,24,0x7013,0));frame[0]=6;assert(!bw_paging_observed(0xcffa,frame,6,24,0x7013,0));
 assert(bw_paging_read(0xcffe,0xcffe,2,1,24,0x7013,0,24,0x7014));assert(!bw_paging_read(0xdffe,0xdffe,2,1,24,0x7013,0,24,0x7014));assert(!bw_paging_read(0xcffe,0xcffe,2,1,24,0x7003,0,24,0x7005));assert(bw_int_shadow(0xf000,${afterSs},true,true));assert(!bw_int_shadow(0xf000,${afterSs},false,false));assert(!bw_int_shadow(24,0x7003,true,false));assert(bw_paging_reset_phase(24,0x7010,0xfffffff1,0x1000));assert(!bw_paging_reset_phase(24,0x7010,0x7ffffff1,0x1000));assert(bw_paging_physical(24,0,0x7010)==0xa010);
 const uint8_t program[20]={${ramProgram}};for(unsigned i=0;i<4096;++i){assert(bw_protected_ram_byte(i,5)==(i<20?program[i]:0));}assert(bw_cold_fetch_page(true,0xa000,0xa000,0,0,1,0xa000,0xa000,0xb8,0,5,5,0));assert(!bw_cold_fetch_page(true,0x7000,0x7000,0,0,1,0x7000,0x7000,0xb8,0,5,5,0));assert(!bw_cold_fetch_page(true,0xa000,0xa000,0,0,1,0xa000,0xa000,1,4095,5,5,0));return 0;}`;
 const dir=mkdtempSync(join(tmpdir(),'int-native-policy-'));try{writeFileSync(join(dir,'fixture.cc'),code);execFileSync('g++',['-std=c++17','-O0','-Wall','-Wextra','-Werror','-Wno-unused-function',join(dir,'fixture.cc'),'-o',join(dir,'fixture')],{timeout:10000});execFileSync(join(dir,'fixture'),[],{timeout:5000});}finally{rmSync(dir,{recursive:true,force:true});}
});
test('private provider exercises real host callbacks/generations and ten pages without any CPU steps',async()=>{
 await assert.rejects(createOwnedPagedIntIretProvider({}));const p=await createOwnedPagedIntIretProvider();try{p.callbacks.clockTransfer(new Uint32Array(),1);p.begin();p.callbacks.clockTransfer(new Uint32Array(),2);assert.throws(()=>p.callbacks.admitExecutePage(0xa000));for(const e of bootStores)p.callbacks.writePhysical(e.raw,Uint8Array.from(e.bytes));assert.throws(()=>p.callbacks.admitExecutePage(0x7000));const page=p.callbacks.admitExecutePage(0xa000);assert.equal(page.generation,5);assert.deepEqual(page.bytes,expectedRamPage());
 const updates=[];for(const [raw,after]of nativeAd){const before=(p.callbacks.readPhysical(raw,4).bytes.reduce((n,b,i)=>n+b*2**(8*i),0))>>>0;p.callbacks.writePhysical(raw,dword(after));updates.push({raw,before,after});}for(const e of nativeFrameStores)p.callbacks.writePhysical(e.raw,Uint8Array.from(e.bytes));assert.deepEqual([...p.callbacks.readPhysical(0xcffe,2).bytes],[2,0]);assert.deepEqual([...p.callbacks.readPhysical(0xcffc,2).bytes],[24,0]);assert.deepEqual([...p.callbacks.readPhysical(0xcffa,2).bytes],[5,0x70]);assert.throws(()=>p.callbacks.writePhysical(0xcffa,Uint8Array.of(5,0x70)));assert.throws(()=>p.callbacks.writePhysical(0x201c,dword(0xa063)));assert.throws(()=>p.callbacks.readPhysical(0xdffa,2));p.end();const s=p.checkpoint();assert.equal(s.nativeTicks,0);assert.equal(s.successfulQuanta,0);assert.equal(s.ram.bootStores,20);assert.equal(s.ram.frameWords,3);assert.equal(s.ram.admitted,true);assert.deepEqual(Object.fromEntries(Object.entries(s.ram.pages).map(([k,b])=>[k,Uint8Array.from(b)])),expectedPages([...bootStores,...nativeFrameStores],updates));assert.deepEqual(p.records(),[]);
 }finally{p.close();}
});
