import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {derivePagedPageFaultRuntime,transformPagedPageFaultRuntime,runtimeParentSha256} from '../scripts/bochs-cpu3-native-paged-pagefault/runtime.mjs';
import {derivePagedPageFaultProvider,transformPagedPageFaultProvider,providerParentSha256} from '../scripts/bochs-cpu3-native-paged-pagefault/provider-derivation.mjs';
import {deriveDriverProvider} from '../scripts/bochs-cpu3-native-paged-pagefault/driver-provider.mjs';
import {nativeWalkOwner,nativeWalkAllowed,validatePageFaultWrite,nativeFrameStores,entries,nativeAdUpdate} from '../scripts/bochs-cpu3-native-paged-pagefault/provider-profile.mjs';
import {validateBuildBinding,requireReadyBuild,driverSourceIdentity} from '../scripts/bochs-cpu3-native-paged-pagefault/driver-auth.mjs';
import {validateInput,derivePageFaultLifecycle,verifyHeldLifecycle,finalizeAuthentication} from '../scripts/bochs-cpu3-native-paged-pagefault/runner.mjs';
import {pageFaultProgress,stepReferenceForReturn,compareBoundary,inspectFields,startOrAdvanceFaultLedger,validateDescriptorRows,validateNativeEffects,validateMemoryTape} from '../scripts/bochs-cpu3-native-paged-pagefault/parity.mjs';
import {bootStores,frameStores,adTransitions,expectedPages,layout,selector,dataSelector,codeCache,dataCache,repairStore,retryStore} from '../scripts/bochs-cpu3-native-paged-pagefault/profile.mjs';
import {sha256} from '../scripts/bochs-cpu3-native-owned-clock/derive.mjs';
const clone=structuredClone;
const pending=JSON.parse(readFileSync(new URL('../scripts/bochs-cpu3-native-paged-pagefault/driver-build-binding.json',import.meta.url)));
let derivedProviderForSourceControls;
// All native/board/JS snapshots in this file are manufactured. No provider/oracle factory or CPU is called.
function fixture(fault=false){
 const q=49,N=q+Number(fault),cpu={eax:0x80001234,ecx:0,edx:0,ebx:0,esp:fault?0xdff8:0xe000,ebp:0,esi:0,edi:0,eip:fault?0x7020:0x7003,eflags:2,cr0:0xfffffff1,cr2:fault?0x8000:0,cr3:0x1000,cr4:0,cs:selector,ds:dataSelector,ss:dataSelector,es:0,fs:0,gs:0,gdtr:{base:0x600,limit:31},idtr:{base:0x3000,limit:0x77},debugRegisters:Array(8).fill(0),halted:false,shutdown:false,interruptShadow:0,nmiShadow:0,debugShadow:0,pc:fault?0x7020:0x7003};
 cpu.segmentCaches=[dataCache,codeCache,dataCache,dataCache,dataCache,dataCache].map(c=>({...c}));cpu.ldtr={selector:0,base:0,limit:0,present:false,type:0};cpu.tr={...cpu.ldtr};
 const n={state:['eax','ecx','edx','ebx','esp','ebp','esi','edi','eip','eflags','cr0','cr2','cr3','cs','ds','ss'].map(k=>cpu[k]).concat([0x600,31,0x3000,0x77]),extra:Array(20).fill(0),segments:[],system:Array(30).fill(0),debug:Array(6).fill(0),nativeTicks:String(N),successfulQuanta:String(q),mappingEpoch:0,boardA20:1};
 for(const [i,k]of ['es','cs','ss','ds','fs','gs'].entries()){const s=cpu[k],c=cpu.segmentCaches[i],valid=(i===2||i===3)&&fault?7:1;n.segments.push(i,s,s>>>3,0,0,valid,Number(c.present),0,1,i===1?11:3,c.base>>>0,c.limit>>>0,0,Number(c.default32),0);}
 n.extra.splice(2,6,cpu.es,cpu.fs,cpu.gs,...n.segments.slice(17,20));n.extra[9]=1;n.extra[13]=0;n.extra[14]=65535;n.extra[16]=0;n.system[0]=6;n.system[15]=7;
 n.execution=Object.fromEntries(['attempts','completed','repIterations','repPartial','faults','portCommits','irqDeliveries','haltIdleCuts'].map(k=>[k,String(k==='attempts'?N:k==='completed'?q:k==='faults'?Number(fault):0)]));n.fallback=Object.fromEntries(['bochsRamReads','bochsRamWrites','bochsDirectPointers','bochsPio','bochsTimer'].map(k=>[k,'0']));n.callbacks=Object.fromEntries(['physicalReads','physicalWrites','executePages','nativeTickCallbacks','quantumCallbacks'].map(k=>[k,'0']));n.clockTransfers={transfers:'0',commits:'0',words:'0'};
 const stores=[...bootStores,...(fault?frameStores:[])].map(w=>({...w,bytes:[...w.bytes]})),updates=adTransitions.slice(0,fault?7:4),pages=expectedPages(stores,updates),js={q,attemptOrdinal:N,faultSerial:Number(fault),cpu,board:{cycles:298,a20Enabled:true},pages,stores,updates,deliveries:fault?[{vector:14,returnEip:0x7003,errorCode:2,fault:true,cr2:0x8000,cs:selector,eip:0x7020,esp:0xdff8,eflags:2,q:49,attemptOrdinal:50}]:[]};
 const ads=Object.values(entries).filter(e=>e.raw!==entries.data.raw&&(![entries.idt.raw,entries.table.raw,entries.stack.raw].includes(e.raw)||fault&&e.raw!==entries.table.raw)).map(e=>({kind:'ad',raw:e.raw,before:e.value,after:e.value|(e.raw===entries.stack.raw?0x60:0x20),bytes:[]}));for(const e of ads)e.bytes=[e.after&255,e.after>>>8&255,e.after>>>16&255,e.after>>>24];
 const writes=[...bootStores.map(w=>({kind:'boot',raw:w.raw,bytes:[...w.bytes]})),...ads,...(fault?nativeFrameStores.map(w=>({kind:'frame',raw:w.raw,bytes:[...w.bytes]})):[])],board={nativeTicks:N,successfulQuanta:q,board:clone(js.board),ram:{writes,reads:[],bootStores:31,frameWords:fault?4:0,storeCount:writes.length,repaired:false,dataWritten:false,admitted:true}};
 return {n,js,pages,board};
}
function returned(n,reason=1,dn=1,dq=1){n=clone(n);Object.assign(n,{reason,activityState:0,chargedNativeTicks:dn,chargedQuanta:dq,sliceBytes:new Uint8Array(160)});const v=new DataView(n.sliceBytes.buffer),u=(o,x)=>v.setUint32(o,x,true);for(const [o,x]of [[0,reason],[4,1],[8,1],[12,dn],[16,1],[20,dq]])u(o,x);for(const [i,k]of ['nativeTicks','successfulQuanta',...Object.keys(n.execution)].entries())v.setBigUint64(24+8*i,BigInt(i<2?n[k]:n.execution[k]),true);v.setUint16(104,n.state[13],true);u(108,n.state[8]);if(reason===2)for(const [o,x]of [[112,1],[116,14],[120,2],[124,0x8000]])u(o,x);return n;}
test('pending distinct PF build refuses before input getters factories or old addon authority',()=>{
 assert.equal(validateBuildBinding(pending),pending);assert.throws(requireReadyBuild,/pending/);assert.throws(()=>validateInput(new Proxy({},{get(){throw Error('input getter reached');}})),/pending/);
 for(const change of [b=>b.status='ROOT_REVIEWED_PF_BUILD',b=>b.addonSha256='92a5121df194c6675303913ebd527e7d0253e29e686b2cbd8dd91fb579489b6f',b=>b.abiVersion=5,b=>b.compiledFiles['fake']='0'.repeat(64)]){const b=clone(pending);change(b);assert.throws(()=>validateBuildBinding(b));}
});
test('new runtime and provider preserve exact held derivatives and unknown source refuses',()=>{
 const r=derivePagedPageFaultRuntime(),p=derivePagedPageFaultProvider(),a=deriveDriverProvider(p.bytes);derivedProviderForSourceControls=p.bytes;assert.equal(r.baseSha256,runtimeParentSha256);assert.equal(p.baseSha256,providerParentSha256);assert.equal(a.parentSha256,sha256(p.bytes));
 for(const [bytes,transform]of [[Buffer.from('unknown runtime'),transformPagedPageFaultRuntime],[Buffer.from('unknown provider'),transformPagedPageFaultProvider],[Buffer.from('unknown adapter'),deriveDriverProvider]])assert.throws(()=>transform(bytes));
 const source=r.bytes.toString();assert.ok(source.indexOf('static void bw_pf_observe_tlb(void);')<source.indexOf('void bw_slice_note_tlb_flush(void)'));assert.ok(source.indexOf('static bool bw_pf_fault_allowed(')<source.indexOf('void bw_slice_note_fault('));assert.match(source,/fault-delivery-clock/);assert.match(source,/fixed-PF-delivered-frame-state/);assert.match(source,/PF-completed-owner-phase/);assert.ok(!source.includes('bw_slice_fail("cold-BIOS-no-fault")'));
 const held=readFileSync(new URL('../scripts/bochs-cpu3-native-paged-int-iret/runner.mjs',import.meta.url));assert.ok(derivePageFaultLifecycle(held).toString().includes('stepReferenceForReturn(oracle,next)'));verifyHeldLifecycle();
});
test('delivery and failed operand owners cannot be confused with generic prefetch',()=>{
 assert.equal(nativeWalkOwner(24,0x7003,24,0x7003,1).phase,'fault-delivery');assert.equal(nativeWalkOwner(24,0x7006,24,0x7003,0).phase,'fault-or-retry-write');assert.equal(nativeWalkOwner(24,0x7029,24,0x7020,0).phase,'handler-PTE-repair');
 assert.ok(nativeWalkAllowed(2,entries.idt.raw,4,24,0x7003,24,0x7003,1));assert.equal(nativeWalkAllowed(2,entries.code.raw,4,24,0x7003,24,0x7003,1),false);assert.equal(nativeWalkAllowed(2,entries.data.raw,4,24,0x7006,24,0x7000,0),false);assert.equal(nativeWalkAllowed(2,entries.code.raw,4,24,0x7006,24,0x7003,0),false);assert.equal(nativeWalkAllowed(2,entries.idt.raw,3,24,0x7003,24,0x7003,1),false);assert.equal(nativeWalkAllowed(2,entries.idt.raw,4,24,0x7003,24,0x7000,1),false);
 const state={boot:31,admitted:true,frameWords:0,repaired:false,dataWritten:false,tableValues:{[entries.stack.raw]:0xc063,[entries.table.raw]:0x2063,[entries.data.raw]:0}};for(const e of nativeFrameStores){assert.equal(validatePageFaultWrite(e.raw,Uint8Array.from(e.bytes),state).kind,'frame');state.frameWords++;}assert.throws(()=>validatePageFaultWrite(nativeFrameStores[0].raw,Uint8Array.from(nativeFrameStores[0].bytes),state));assert.throws(()=>validatePageFaultWrite(retryStore.raw,Uint8Array.from(retryStore.bytes),state));assert.equal(validatePageFaultWrite(repairStore.raw,Uint8Array.from(repairStore.bytes),state).kind,'repair');assert.throws(()=>nativeAdUpdate(entries.data.raw,0,0x60));
});
test('FAULT N1 Q0 steps the genuine-reference interface exactly once while prefetch does not',()=>{
 const f=fixture(true),r=returned(f.n,2,1,0),p=pageFaultProgress({n:49,q:49,faults:0},r);assert.deepEqual([p.classification,p.n,p.q,p.attemptOrdinal],['EXACT_SINGLE_FAULT_DELIVERY',50,49,50]);let calls=0;const oracle={step(){calls++;return {attemptOrdinal:50,q:49,completed:0,faultDelivered:true};}};stepReferenceForReturn(oracle,p);assert.equal(calls,1);
 stepReferenceForReturn(oracle,{classification:'PREFETCH_RAW_UNMATCHED'});assert.equal(calls,1);assert.throws(()=>stepReferenceForReturn({step(){return {attemptOrdinal:50,q:50,completed:1,faultDelivered:false};}},p));assert.throws(()=>pageFaultProgress({n:50,q:49,faults:1},r));const bad=clone(r);new DataView(bad.sliceBytes.buffer).setUint32(120,0,true);assert.throws(()=>pageFaultProgress({n:49,q:49,faults:0},bad));
 const b=fixture(false),prefetch=returned(b.n,1,0,0);assert.equal(pageFaultProgress({n:49,q:49,faults:0},prefetch).classification,'PREFETCH_RAW_UNMATCHED');assert.equal(startOrAdvanceFaultLedger(null,b.n,r,b.pages,f.pages).faultSerial,1);const pages=clone(f.pages);pages.data[0]=0x34;assert.throws(()=>startOrAdvanceFaultLedger(null,b.n,r,b.pages,pages));
 // Actual production bodies, extracted from authenticated generated source, run on a manufactured clock-only board.
 // No SourcePagedPageFaultBoard constructor, actual machine/provider factory or CPU is used.
 const source=(derivedProviderForSourceControls??derivePagedPageFaultProvider().bytes).toString(),stateStart=source.indexOf(' const state=()=>'),stateEnd=source.indexOf(' const callback=',stateStart),clockStart=source.indexOf('  clockTransfer(words,reason){'),clockEnd=source.indexOf('\n });\n return Object.freeze',clockStart);assert.ok(stateStart>=0&&stateEnd>stateStart&&clockStart>=0&&clockEnd>clockStart);
 const tick=source.match(/^ nativeTick\(\)\{.*\}$/m),quantum=source.match(/^ quantum\(kind\)\{.*\}$/m);assert.ok(tick&&quantum);assert.equal(source.split(tick[0]).length-1,1);assert.equal(source.split(quantum[0]).length-1,1);
 const machine={cycles:4+6*49,_chipDebt:6*49,_chipDeadline:6000,_a20Enabled:true},board={nativeTicks:49,successfulQuanta:49,mappingEpoch:0,machine,_call(k,args,fn){return fn();}};
 Object.assign(board,Function('assert','coldBoardProfile','return ({'+tick[0]+','+quantum[0]+'});')(assert,{maxNativeTicks:512,maxQuanta:512}));
 const call=(k,args=[])=>Reflect.apply(board[k],board,args),clock=Function('assert','board','call','coldBoardProfile',`let lease=true,closed=false,initialized=true,entry=false,postPio=false,mappingPending=false,active=false,n=0,q=0;${source.slice(stateStart,stateEnd)}return ({${source.slice(clockStart,clockEnd)}}).clockTransfer;`)(assert,board,call,{maxNativeTicks:512,maxQuanta:512});
 assert.deepEqual([...clock(Uint32Array.of(1),8)],[50,49,298,294,6000,0,1],'N-only fault leaves Q/device clock unchanged');
 for(let i=0;i<7;i++){const state=clock(Uint32Array.of(1,2),4);assert.deepEqual([...state],[51+i,50+i,4+6*(50+i),6*(50+i),6000,0,1],'following instructions preserve exactly one permanent N-Q offset');}
 const prior=clone({n:board.nativeTicks,q:board.successfulQuanta,cycles:machine.cycles,debt:machine._chipDebt});assert.throws(()=>clock(Uint32Array.of(1,9),4));assert.deepEqual({n:board.nativeTicks,q:board.successfulQuanta,cycles:machine.cycles,debt:machine._chipDebt},prior,'whole tape preflight rejects before any effect');
});
test('comparable wholeboards ten pages and native cache rows remain strict with unmatched prefetch raw',()=>{
 const f=fixture(true),n=returned(f.n,2,1,0);assert.equal(compareBoundary(n,f.board,f.js,f.pages,'resume','EXACT_SINGLE_FAULT_DELIVERY').status,'COMPARABLE_PARITY_PASS');
 for(const change of [x=>x.pages.code[4095]=1,x=>x.board.board.cycles++,x=>x.n.segments[35]=1,x=>x.n.segments[50]=3,x=>x.n.state[0]^=1]){const x=clone(f);change(x);assert.throws(()=>compareBoundary(x.n,x.board,x.js,x.pages,'resume','EXACT_SINGLE_FAULT_DELIVERY'));}
 const p=clone(f.pages);p.table[4095]=1;const b=clone(f.board);b.board.cycles++;assert.equal(compareBoundary(f.n,b,f.js,p,'resume','PREFETCH_RAW_UNMATCHED').status,'UNMATCHED_PHASE');assert.throws(()=>validateDescriptorRows({...f.n,segments:f.n.segments.map((v,i)=>i===20?3:v)},f.js,f.board));
});
test('native frame and A D tapes are independent yet cannot smuggle extra writes or lost callbacks',()=>{
 const f=fixture(true);assert.equal(validateNativeEffects(f.board,f.js).frameWrites,4);const reversed=clone(f.board);reversed.ram.writes=reversed.ram.writes.map(w=>w.kind==='frame'?{...w,bytes:[...w.bytes]}:w);const frames=reversed.ram.writes.filter(w=>w.kind==='frame');[frames[0].raw,frames[3].raw]=[frames[3].raw,frames[0].raw];assert.throws(()=>validateNativeEffects(reversed,f.js));
 const unknown=clone(f.board);unknown.ram.writes.push({kind:'unknown',raw:0,bytes:[1]});assert.throws(()=>validateNativeEffects(unknown,f.js));const events=f.board.ram.writes.map((w,i)=>({...w,direction:'write',ordinal:i,generation:i,nativeTicks:49,successfulQuanta:49})),board=clone(f.board);board.ram.writes=events.map(({direction,ordinal,...w})=>w);assert.equal(validateMemoryTape(events,board).events,events.length);assert.throws(()=>validateMemoryTape(events.slice(1),board));
});
test('all-outcome authentication retains primary failure independently of missing or changed guards',()=>{
 const before=Object.fromEntries(['input','driver','compiled','build','configuration','node'].map(k=>[k,k])),receipt={status:'PASS'},primary=Error('first divergence');assert.equal(finalizeAuthentication(receipt,primary,before,{...before,input:'changed'}),primary);assert.equal(receipt.status,'FAIL');assert.match(receipt.finalAuthenticationError,/final input/);const missing={...before};delete missing.configuration;assert.ok(finalizeAuthentication({status:'PASS'},null,before,missing));assert.equal(finalizeAuthentication({status:'PASS'},null,before,{...before}),null);
});
test('frozen source identity includes real fault policy and held multiline checkpoint import',()=>{
 const identity=driverSourceIdentity();assert.ok(identity.hashes['scripts/bochs-cpu3-native-paged-pagefault/runtime.mjs']);assert.ok(identity.hashes['scripts/bochs-cpu3-native-paged-pagefault/native-fault-policy.mjs']);assert.ok(identity.hashes['src/machine-checkpoint.js']);assert.ok(identity.hashes['scripts/bochs-cpu3-native-paged-int-iret/evidence.mjs']);assert.ok(identity.hashes['src/experimental/i80386.js']);
});
