import test from 'node:test';
import assert from 'node:assert/strict';
import {writeFileSync,readFileSync,realpathSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {createColdBiosJavascriptOracle,captureColdReference,coldCheckpointReached,validateColdProgress,validateRepRecord,validateColdReference,referenceSourceIdentity,coldReferenceSchema,coldCutNames} from '../scripts/bochs-cpu3-native-cold-bios/reference.mjs';
import {coldBoardConfig} from '../scripts/bochs-cpu3-native-cold-bios/board-profile.mjs';
import {repSites,biosSha256} from '../scripts/bochs-cpu3-native-cold-bios/rep-policy.mjs';
const clone=v=>JSON.parse(JSON.stringify(v));
// Synthetic structural/protocol fixtures only. They are never baseline evidence.
const cpu=(q,eip,site=null,exit=false)=>({cs:0xf000,eip,cycles:q,ecx:site?(exit?0:site.count):0,edi:site?site.destination+(exit?site.count*site.width:0):0,eax:site?.value??0,es:0,cr0:0,eflags:2,halted:false,shutdown:false,segmentCaches:{0:{base:0,default32:false},1:{base:0xf0000,default32:false}}});
const cut=(name,q,eip,site=null,exit=false)=>({name,q,cpu:cpu(q,eip,site,exit),board:{cycles:4+6*q,debt:0,a20Enabled:true}});
function repRecord(site,q=1){return {siteEip:site.eip,width:site.width,count:site.count,entry:{q,cpu:cpu(q,site.eip,site)},elements:Array.from({length:site.count},(_,i)=>({q:q+i+1,cx:site.count-i-1,di:site.destination+(i+1)*site.width,eip:i+1===site.count?site.eip+site.bytes.length:site.eip,address:site.destination+i*site.width,beforeBytes:Array(site.width).fill(0),afterBytes:Array.from({length:site.width},(_,k)=>(site.value>>>(8*k))&255)})),exit:{q:q+site.count,cpu:cpu(q+site.count,site.eip+site.bytes.length,site,true)}};}
function report(){let q=0;const cuts=[cut('reset',q,0xfff0)],reps=[],ports=[];for(const s of repSites){const r=repRecord(s,++q);reps.push(r);cuts.push({...cut('rep-entry-'+s.eip.toString(16),q,s.eip),cpu:clone(r.entry.cpu)});q=r.exit.q;cuts.push({...cut('rep-exit-'+s.eip.toString(16),q,s.eip+s.bytes.length),cpu:clone(r.exit.cpu)});}cuts.push(cut('before-AA-routine',++q,0xcd0));for(const [i,[dir,port,value]]of [['out',100,170],['in',96,85],['out',100,171],['in',96,0]].entries()){q+=10;ports.push({ordinal:i+1,q,cycles:4+6*(q-1),width:8,dir,port,value});cuts.push(cut(coldCutNames[10+i],q,0x540));}const finalCut=cut('before-F000-E16',++q,0xe16);cuts.push(finalCut);return {schema:coldReferenceSchema,romSha256:biosSha256,configuration:clone(coldBoardConfig),q,cuts,reps,ports,codePages:[{raw:0xf0000,decoded:0xf0000}],final:{...clone(finalCut),ramSha256:'0'.repeat(64)},coverage:{namedSnapshots:true,perStepSnapshotArray:false,nativeCounters:false}};}
test('fixed ordinary oracle rejects all caller config/hooks before construction',()=>{for(const v of [null,{},()=>{},coldBoardConfig])assert.throws(()=>createColdBiosJavascriptOracle(v),/no caller/);assert.throws(()=>captureColdReference({}),/visitor/);});
test('Q cap and conditional zero/one progress domains refuse malformed alignment',()=>{const good={q:1,done:false,chargedQuanta:1,portStart:0,portCount:0};assert.equal(validateColdProgress(good),good);assert.equal(validateColdProgress({...good,done:true,chargedQuanta:0}).chargedQuanta,0);for(const patch of [{q:400001},{q:-1},{q:1.5},{chargedQuanta:2},{chargedQuanta:0},{done:true},{portStart:-1},{portCount:20001}])assert.throws(()=>validateColdProgress({...good,...patch}));});
test('ordinary terminal requires exact CS E16 rather than halt or nearby address',()=>{assert.equal(coldCheckpointReached({cs:0xf000,eip:0xe16}),true);for(const s of [{cs:0,eip:0xe16},{cs:0xf000,eip:0xe15},{cs:0xf000,eip:0xe17}])assert.equal(coldCheckpointReached(s),false);const good=report();assert.equal(validateColdReference(good),good);for(const patch of [{q:400001},{schema:'wrong'},{romSha256:'0'.repeat(64)}])assert.throws(()=>validateColdReference({...good,...patch}));for(const key of ['eip','halted','shutdown']){const bad=clone(good);bad.final.cpu[key]=key==='eip'?0xe17:true;assert.throws(()=>validateColdReference(bad));}});
test('all four REP entry and every element metadata/effect mutations refuse',()=>{for(const site of repSites){const r=repRecord(site);assert.equal(validateRepRecord(r),r);for(const mutate of [x=>x.entry.cpu.ecx--,x=>x.entry.cpu.edi++,x=>x.entry.cpu.eax=(x.entry.cpu.eax^1)>>>0,x=>x.entry.cpu.eflags|=0x400,x=>x.entry.cpu.cr0=1,x=>x.entry.cpu.segmentCaches[0].base=1,x=>x.width=1,x=>x.elements.pop(),x=>x.exit.q++,x=>x.entry.q=-1,x=>x.entry.q=0.5,x=>x.exit.q=400001,x=>x.exit.cpu.ecx=1]){const bad=clone(r);mutate(bad);assert.throws(()=>validateRepRecord(bad));}for(let i=0;i<site.count;i++){for(const key of ['q','cx','di','eip','address']){const bad=clone(r);bad.elements[i][key]++;assert.throws(()=>validateRepRecord(bad));}const bad=clone(r);bad.elements[i].afterBytes[0]^=1;assert.throws(()=>validateRepRecord(bad));}}});
test('named cuts bind ordered names Q CPU and REP records, never orphan snapshots',()=>{const good=report();for(const mutate of [x=>x.cuts.splice(2,1),x=>x.cuts[1].name='orphan',x=>x.cuts[1].q++,x=>x.cuts[2].cpu.edi++,x=>x.cuts[3].q=0,x=>x.cuts[9].cpu.eip++,x=>x.cuts[10].q++]){const bad=clone(good);mutate(bad);assert.throws(()=>validateColdReference(bad));}});
test('complete AA55AB00 chronology and every PIO ownership/domain mutation refuse',()=>{const good=report();const swapped=clone(good);[swapped.ports[1],swapped.ports[2]]=[swapped.ports[2],swapped.ports[1]];swapped.ports.forEach((p,i)=>{p.ordinal=i+1;p.q=good.ports[i].q;p.cycles=good.ports[i].cycles;});assert.throws(()=>validateColdReference(swapped));for(let i=0;i<good.ports.length;i++)for(const key of ['ordinal','q','cycles','width','port','value']){const bad=clone(good);bad.ports[i][key]++;assert.throws(()=>validateColdReference(bad));}const missing=clone(good);missing.ports.pop();assert.throws(()=>validateColdReference(missing));});
test('raw RAM digest page metadata and explicit named-only coverage refuse malformed claims',()=>{const good=report();for(const mutate of [x=>x.final.ramSha256='invalid',x=>x.final.board.debt=1,x=>x.codePages[0].raw++,x=>x.codePages[0].decoded=0x7000,x=>x.coverage.perStepSnapshotArray=true,x=>x.coverage.nativeCounters=true]){const bad=clone(good);mutate(bad);assert.throws(()=>validateColdReference(bad));}});
// Root-reviewed external bounded harness must explicitly request this ONE full
// ordinary JS capture. Normal source tests do not repeat the cold guest.
test('explicit authenticated ordinary cold baseline capture',{skip:!process.env.BW_COLD_REFERENCE_OUTPUT},()=>{
 const output=process.env.BW_COLD_REFERENCE_OUTPUT;assert.ok(output.startsWith('/')&&!/[\0\r\n]/.test(output));assert.deepEqual(process.execArgv,['--max-old-space-size=128']);for(const k of ['NODE_OPTIONS','NODE_PATH','LD_PRELOAD','LD_AUDIT','BW_HOT_NAPI_PROFILE','NODE_V8_COVERAGE'])assert.ok(!process.env[k]);
 const node=realpathSync(process.execPath),nodeSha=()=>createHash('sha256').update(readFileSync(node)).digest('hex');let receipt={schema:'bw.js-cold-bios.authenticated-baseline.v1',status:'FAIL',node,nodeSha256Before:nodeSha(),scope:'One ordinary JS baseline and pure source controls; no native addon/build/performance'};
 try{receipt.sourceBefore=referenceSourceIdentity();let lastFrame=null;receipt.reference=captureColdReference(frame=>{lastFrame=frame;});receipt.lastFrame=lastFrame;receipt.status='PASS';}catch(error){receipt.error=String(error);throw error;}finally{try{receipt.sourceAfter=referenceSourceIdentity();receipt.nodeSha256After=nodeSha();assert.deepEqual(receipt.sourceAfter,receipt.sourceBefore);assert.equal(receipt.nodeSha256After,receipt.nodeSha256Before);}catch(error){receipt.status='FAIL';receipt.afterError=String(error);writeFileSync(output,JSON.stringify(receipt)+'\n',{flag:'wx'});throw error;}writeFileSync(output,JSON.stringify(receipt)+'\n',{flag:'wx'});}
});
