import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {createOwnedIn8Provider as baseline} from '../scripts/bochs-cpu3-native-owned-in8/provider.mjs';
import {createOwnedDispatchProvider as candidate} from '../scripts/bochs-cpu3-native-owned-dispatch/provider.mjs';
const tape=(...v)=>Uint32Array.from(v),hash=s=>createHash('sha256').update(s).digest('hex');
function pair(sink=false){const events=[[],[]];const owners=[baseline,candidate].map((factory,i)=>factory(sink?{compactSink:e=>events[i].push(e)}:{}));return {owners,events};}
function both(p,fn){const results=p.owners.map(fn);assert.deepEqual(results[1],results[0]);return results[0];}
function init(p){both(p,o=>o.callbacks.clockTransfer(tape(),1));both(p,o=>o.begin());return both(p,o=>Array.from(o.callbacks.clockTransfer(tape(),2)));}
function finish(p){both(p,o=>o.end());both(p,o=>o.checkpoint());assert.deepEqual(p.events[1],p.events[0]);both(p,o=>o.close());}
test('exact source inverse and guard seams',()=>{const d=JSON.parse(readFileSync(new URL('../scripts/bochs-cpu3-native-owned-dispatch/derivation.json',import.meta.url)));let s=readFileSync(new URL('../scripts/bochs-cpu3-native-owned-dispatch/provider.mjs',import.meta.url),'utf8');assert.equal(hash(s),d.derivedSha256);for(const x of d.seams.toReversed()){assert.equal(s.split(x.after).length,2);s=s.replace(x.after,x.before);}assert.equal(hash(s),d.baseSha256);assert.equal(s,readFileSync(new URL('../scripts/bochs-cpu3-native-owned-in8/provider.mjs',import.meta.url),'utf8'));});
for(const capture of [false,true])test(`ordinary REP and fault-N ordering capture=${capture}`,()=>{const p=pair(capture);init(p);both(p,o=>Array.from(o.callbacks.clockTransfer(tape(2,1,3,1,1,2,1),3)));finish(p);if(capture)assert.deepEqual(p.events[0].filter(e=>['nativeTick','quantum'].includes(e.operation)).map(e=>[e.operation,e.args]),[['quantum',[0]],['nativeTick',[]],['quantum',[1]],['nativeTick',[]],['nativeTick',[]],['quantum',[0]],['nativeTick',[]]]);});
for(const bad of [[1,2,99],Array(601).fill(1),Array(301).fill(2)])test(`full preflight denial ${bad.length}/${bad.at(-1)}`,()=>{const p=pair();init(p);both(p,o=>{assert.throws(()=>o.callbacks.clockTransfer(Uint32Array.from(bad),3));return Array.from(o.callbacks.clockTransfer(tape(1,2),3));});finish(p);});
test('query phases and paused lifecycle denial preserve subsequent work',()=>{const p=pair();init(p);both(p,o=>{assert.throws(()=>o.callbacks.clockTransfer(tape(),2));assert.throws(()=>o.checkpoint());assert.throws(()=>o.close());assert.throws(()=>o.begin());return Array.from(o.callbacks.clockTransfer(tape(2,1),3));});finish(p);});
test('foreign callback receiver cannot replace factory receiver',()=>{const p=pair();init(p);both(p,o=>Array.from(o.callbacks.clockTransfer.call({nativeTicks:999},tape(1,3),3)));finish(p);});
test('PIT write/read catchup and query replies match',()=>{const p=pair();init(p);for(const [port,value]of [[0x43,0x34],[0x40,0x34],[0x40,0x12],[0x43,0]]){both(p,o=>Array.from(o.callbacks.packedScalar(3,port,1,value)));both(p,o=>Array.from(o.callbacks.clockTransfer(tape(),6)));}both(p,o=>Array.from(o.callbacks.clockTransfer(tape(2,1),3)));for(let i=0;i<2;i++){both(p,o=>Array.from(o.callbacks.packedScalar(5,0x40,1,0)));both(p,o=>Array.from(o.callbacks.clockTransfer(tape(),6)));}finish(p);});
test('mapping publication refuses N/REP and admits only ordinary Q',()=>{const p=pair();init(p);for(const [port,value]of [[0x64,0xd1],[0x60,1]]){both(p,o=>Array.from(o.callbacks.packedScalar(3,port,1,value)));both(p,o=>Array.from(o.callbacks.clockTransfer(tape(),6)));}both(p,o=>{assert.throws(()=>o.callbacks.clockTransfer(tape(1),3));assert.throws(()=>o.callbacks.clockTransfer(tape(3),3));return Array.from(o.callbacks.clockTransfer(tape(2,1),3));});finish(p);});
test('sink exception and nested callback denial retain exact partial effect/finally',()=>{const states=[baseline,candidate].map(factory=>{let owner,once=true;owner=factory({compactSink:e=>{if(e.operation==='nativeTick'&&once){once=false;assert.throws(()=>owner.callbacks.clockTransfer(tape(1),3));throw Error('sink-stop');}}});owner.callbacks.clockTransfer(tape(),1);owner.begin();owner.callbacks.clockTransfer(tape(),2);assert.throws(()=>owner.callbacks.clockTransfer(tape(1,2),3),/sink-stop/);const s=Array.from(owner.callbacks.clockTransfer(tape(2),3));owner.end();const state=owner.checkpoint();owner.close();return {s,state};});assert.deepEqual(states[1],states[0]);});
test('900-word exact independent caps and 901 refusal',()=>{const p=pair();init(p);const words=tape(...Array(600).fill(1),...Array(300).fill(2));both(p,o=>Array.from(o.callbacks.clockTransfer(words,3)));both(p,o=>{assert.throws(()=>o.callbacks.clockTransfer(tape(1),3));assert.throws(()=>o.callbacks.clockTransfer(tape(2),3));assert.throws(()=>o.callbacks.clockTransfer(new Uint32Array(901),3));return null;});finish(p);});
test('due last Q allowed and subsequent Q denied without effects',()=>{const p=pair();init(p);for(const [port,value]of [[0x43,0x34],[0x40,12],[0x40,0]]){both(p,o=>Array.from(o.callbacks.packedScalar(3,port,1,value)));both(p,o=>Array.from(o.callbacks.clockTransfer(tape(),6)));}const state=both(p,o=>Array.from(o.callbacks.clockTransfer(tape(1),3)));const count=Math.ceil((state[4]-state[3])/6);assert.ok(count>0&&count<=300);both(p,o=>Array.from(o.callbacks.clockTransfer(Uint32Array.from(Array(count).fill(2)),3)));both(p,o=>{assert.throws(()=>o.callbacks.clockTransfer(tape(2),3),/Q after due/);return Array.from(o.callbacks.clockTransfer(tape(1),3));});finish(p);});
test('post-factory mutable bind/apply cannot redirect hot dispatch',()=>{const p=pair();init(p);const oldBind=Function.prototype.bind,oldApply=Reflect.apply;let result;try{Function.prototype.bind=function(){throw Error('unexpected bind lookup');};Reflect.apply=function(){throw Error('unexpected apply lookup');};result=p.owners.map(o=>Array.from(o.callbacks.clockTransfer(tape(1,2,3),3)));}finally{Function.prototype.bind=oldBind;Reflect.apply=oldApply;}assert.deepEqual(result[1],result[0]);finish(p);});
