import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from 'node:fs';import {createOwnedProvider}from '../scripts/bochs-cpu3-native-owned-clock-alloc/provider.mjs';import {createOwnedProvider as baselineProvider}from '../scripts/bochs-cpu3-native-owned-clock/provider.mjs';
const setup=()=>{const p=createOwnedProvider();assert.deepEqual([...p.callbacks.clockTransfer(new Uint32Array(),1)],[0,0,4,0,6000,0,1]);return p;};
const begin=p=>{p.stage();p.begin();p.callbacks.clockTransfer(new Uint32Array(),2);};
test('fault N without Q and independent REP Q expansion',()=>{const seen=[],p=createOwnedProvider({compactSink:e=>seen.push([e.operation,e.args,e.nativeTicks,e.successfulQuanta,e.boardCycles,e.debt])});p.callbacks.clockTransfer(new Uint32Array(),1);begin(p);assert.deepEqual([...p.callbacks.clockTransfer(Uint32Array.of(1,3,3,1,2,1),11)],[3,3,22,18,6000,0,1]);assert.deepEqual(seen.map(e=>e[0]),['nativeTick','quantum','quantum','nativeTick','quantum','nativeTick']);assert.deepEqual(seen.map(e=>e.slice(2)),[[1,0,4,0],[1,1,10,6],[1,2,16,12],[2,2,16,12],[2,3,22,18],[3,3,22,18]]);p.end();p.close();});
for(const [label,word] of [['zero',0],['unknown',4],['large',0xffffffff]])test('whole tape malformed '+label+' denies before earlier effects',()=>{const p=setup();begin(p);assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(1,2,word),11));assert.deepEqual([...p.callbacks.clockTransfer(Uint32Array.of(1),11)].slice(0,3),[1,0,4]);p.end();p.close();});
for(const reason of [2,6,11])test('reset wrong query phase '+reason,()=>{const p=createOwnedProvider();assert.throws(()=>p.callbacks.clockTransfer(new Uint32Array(),reason));});
for(const reason of [1,2,6,11])test('active wrong or repeated query '+reason,()=>{const p=setup();begin(p);assert.throws(()=>p.callbacks.clockTransfer(new Uint32Array(),reason));p.end();p.close();});
test('independent N cap without Q and failed tape leaves counters unchanged',()=>{const p=setup();begin(p);p.callbacks.clockTransfer(new Uint32Array(600).fill(1),11);assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(1),11));p.end();p.close();});
test('independent Q cap without N and failed tape leaves counters unchanged',()=>{const p=setup();begin(p);p.callbacks.clockTransfer(new Uint32Array(300).fill(3),11);assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(3),11));p.end();p.close();});
test('offset backing refuses before effects',()=>{const p=setup();begin(p);assert.throws(()=>p.callbacks.clockTransfer(new Uint32Array(new ArrayBuffer(8),4,1),11));p.end();p.close();});
test('shared backing refuses before effects',()=>{const p=setup();begin(p);assert.throws(()=>p.callbacks.clockTransfer(new Uint32Array(new SharedArrayBuffer(4)),11));p.end();p.close();});
test('capture off still ordered logical state/caps',()=>{const p=setup();begin(p);assert.deepEqual([...p.callbacks.clockTransfer(Uint32Array.of(1,2),11)],[1,1,10,6,6000,0,1]);p.end();assert.equal(p.checkpoint().nativeTicks,1);p.close();});
test('PIO actual catchup and one post-query with unchanged cumulative clocks',()=>{const p=setup();begin(p);p.callbacks.clockTransfer(Uint32Array.of(1,2),5);assert.deepEqual([...p.callbacks.packedScalar(3,0x43,1,0x34)],[0,0,1]);const s=[...p.callbacks.clockTransfer(new Uint32Array(),6)];assert.deepEqual(s.slice(0,4),[1,1,10,0]);assert.throws(()=>p.callbacks.clockTransfer(new Uint32Array(),6));p.callbacks.clockTransfer(Uint32Array.of(1,2),11);p.end();p.close();});
test('pending PIO query denies clocks and second PIO',()=>{const p=setup();begin(p);p.callbacks.packedScalar(3,0x43,1,0x34);assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(1),11));assert.throws(()=>p.callbacks.packedScalar(3,0x43,1,0x34));p.callbacks.clockTransfer(new Uint32Array(),6);p.end();p.close();});
test('lease denies inspect/end-before-entry and callback after end',()=>{const p=setup();p.stage();p.begin();assert.throws(()=>p.end());assert.throws(()=>p.checkpoint());p.callbacks.clockTransfer(new Uint32Array(),2);p.end();assert.throws(()=>p.callbacks.readPhysical(0x500,1));p.close();});
test('compact sink cannot reenter private transfer',()=>{let p,rejected=false;p=createOwnedProvider({compactSink:()=>{assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(1),11));rejected=true;}});p.callbacks.clockTransfer(new Uint32Array(),1);begin(p);p.callbacks.clockTransfer(Uint32Array.of(1),11);assert.ok(rejected);p.end();p.close();});
test('A20 pending mapping permits only ordinary Q before more work',()=>{const p=setup();begin(p);p.callbacks.packedScalar(3,0x64,1,0xd1);p.callbacks.clockTransfer(new Uint32Array(),6);p.callbacks.packedScalar(3,0x60,1,1);const s=[...p.callbacks.clockTransfer(new Uint32Array(),6)];assert.deepEqual(s.slice(5),[1,0]);assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(1),11));assert.throws(()=>p.callbacks.clockTransfer(Uint32Array.of(3),11));assert.throws(()=>p.callbacks.readPhysical(0x500,1));assert.throws(()=>p.callbacks.admitExecutePage(0xf0000));assert.throws(()=>p.callbacks.packedScalar(4,0,0,0));p.callbacks.clockTransfer(Uint32Array.of(2,1),11);p.end();p.close();});

import {HotDirectBoardFacade}from '../scripts/bochs-cpu3-native-hot-direct/board.mjs';import {hotNativeProfile as clockProfile}from '../scripts/bochs-cpu3-native-hot-direct/profile.mjs';
const candidateSource=readFileSync(new URL('../scripts/bochs-cpu3-native-owned-clock-alloc/provider.mjs',import.meta.url),'utf8'),classBody=candidateSource.slice(candidateSource.indexOf(' const clockCheck='),candidateSource.indexOf(' const board=new AllocationOwnedBoard'));
const PrivateTestBoard=new Function('HotDirectBoardFacade','clockProfile',classBody+';return AllocationOwnedBoard;')(HotDirectBoardFacade,clockProfile);
function pair(sinkFactory=()=>null){const p=setup(),rom=p.rom;p.close();return [HotDirectBoardFacade,PrivateTestBoard].map(C=>new C(rom,{compactSink:sinkFactory()}));}
const ledger=b=>({n:b.nativeTicks,q:b.successfulQuanta,cycles:b.machine.cycles,debt:b.machine._chipDebt,active:b.active,ordinal:b.compactCount});
test('exact provider inverse and unchanged dispatch/preflight',()=>{let s=candidateSource;s=s.split('\n').filter(line=>!line.startsWith('import {hotNativeProfile as clockProfile}')).join('\n');const start=s.indexOf(' // Private class/receiver'),end=s.indexOf(' const methods=');s=s.slice(0,start)+' const board=new HotDirectBoardFacade(rom,{compactSink});\n'+s.slice(end);assert.equal(s,readFileSync(new URL('../scripts/bochs-cpu3-native-owned-clock/provider.mjs',import.meta.url),'utf8'));});
test('CAPOFF direct private N/fault/QREP effects match generic',()=>{const boards=pair();for(const b of boards){b.beginRun();for(const word of [1,3,3,1,2,1])word===1?b.nativeTick():b.quantum(word===3?1:0);}assert.deepEqual(ledger(boards[0]),ledger(boards[1]));for(const b of boards){b.endRun();b.close();}});
for(const op of ['nativeTick','quantum'])test('lifecycle/caps/kind denial order '+op,()=>{const boards=pair();for(const b of boards){assert.throws(()=>op==='nativeTick'?b.nativeTick():b.quantum(99),/callback lifecycle before effect/);b.beginRun();b.nativeTicks=160000;b.successfulQuanta=150000;const before=ledger(b);if(op==='nativeTick')assert.throws(()=>b.nativeTick(),/total N before effect/);else{assert.throws(()=>b.quantum(99),/work kind before effect/);assert.throws(()=>b.quantum(0),/total Q before effect/);}assert.deepEqual(ledger(b),before);b.active=true;assert.throws(()=>op==='nativeTick'?b.nativeTick():b.quantum(0),/callback lifecycle/);b.active=false;b.endRun();b.close();}});
for(const op of ['nativeTick','quantum'])test('capture sink throws after exact event/effect and finally active clear '+op,()=>{const events=[[],[]];const p=setup(),rom=p.rom;p.close();const boards=[HotDirectBoardFacade,PrivateTestBoard].map((C,i)=>new C(rom,{compactSink:e=>{events[i].push(e);assert.throws(()=>op==='nativeTick'?boards[i].nativeTick():boards[i].quantum(0),/callback lifecycle/);throw Error('sink fails');}}));for(const b of boards){b.beginRun();assert.throws(()=>op==='nativeTick'?b.nativeTick():b.quantum(1),/sink fails/);assert.equal(b.active,false);b.endRun();}assert.deepEqual(events[0],events[1]);assert.deepEqual(ledger(boards[0]),ledger(boards[1]));for(const b of boards)b.close();});
test('capture event cap before effects unchanged',()=>{for(const b of pair(()=>()=>{})){b.beginRun();b.compactCount=500000;const before=ledger(b);assert.throws(()=>b.quantum(99),/compact event bound before effect/);assert.deepEqual(ledger(b),before);b.endRun();b.close();}});
test('partial exceptional CAPOFF Q effect clears active exactly',()=>{for(const b of pair()){b.beginRun();Object.defineProperty(b.machine,'cycles',{get(){return 4;},set(){throw Error('synthetic field failure');},configurable:true});assert.throws(()=>b.quantum(0),/synthetic field failure/);assert.equal(b.successfulQuanta,1);assert.equal(b.active,false);Object.defineProperty(b.machine,'cycles',{value:4,writable:true,configurable:true});b.endRun();b.close();}});
test('actual historical439 request/return ledger scheduler and6cuts with mocks only',()=>{
 const entry=new URL(import.meta.url);const source=readFileSync(new URL('../scripts/run-i80386-native-owned-clock-alloc.mjs',entry),'utf8'),f=JSON.parse(readFileSync(new URL('./fixtures/i80386-owned-main-scheduler.json',entry),'utf8'));assert.equal(f.entries.length,439);assert.equal(f.returns.length,439);
 const handleSource=source.slice(source.indexOf('const handle={'),source.indexOf('const checkpoints=[];'));
 const loop=source.slice(source.indexOf(' for(let i=0;i<160001;i++){'),source.indexOf(' const executionNs='));
 let ordinal=0,snapshots=0;const events=[],provider={stage(){events.push('stage');return {changed:false};},begin(){events.push('begin');},end(){events.push('end');},checkpoint(){events.push('checkpoint');return {};}};
 function resume(n,q,d){events.push('resume');assert.deepEqual([n,q],f.entries[ordinal]);assert.equal(d,0xffffffffffffffffn);const [N,Q,reason,chargedNativeTicks,chargedQuanta]=f.returns[ordinal++],state=Array(20).fill(0),cut=f.cuts.find(x=>x[0]===Q);if(cut){state[8]=cut[1];state[13]=cut[2];}snapshots++;return {nativeTicks:BigInt(N),successfulQuanta:BigInt(Q),reason,chargedNativeTicks,chargedQuanta,state};}
 const run=new Function('assert','provider','resume','setIRQ','targets',`let closed=false,terminalLocal=false;${handleSource}const checkpoints=[];let target=0,final,resumes=0,terminal=false;${loop}return {checkpoints,target,resumes,terminal};`);
 const result=run(assert,provider,resume,()=>assert.fail('unexpected IRQ inmock'),f.cuts.map(([q,eip,cs],i)=>({q,name:String(i),cpu:{eip,cs}})));assert.equal(result.resumes,439);assert.equal(snapshots,439);assert.equal(result.target,6);assert.equal(result.terminal,true);assert.equal(result.checkpoints.length,6);assert.equal(events.filter(x=>x==='checkpoint').length,6);const nativeEvents=events.filter(x=>x!=='checkpoint');for(let i=0;i<439;i++)assert.deepEqual(nativeEvents.slice(i*4,i*4+4),['stage','begin','resume','end']);
});


test('CAPOFF skips _call and CAPON keeps dynamic generic dispatch',()=>{for(const capture of [false,true]){const p=setup(),rom=p.rom;p.close();for(const [C,expected]of [[HotDirectBoardFacade,2],[PrivateTestBoard,capture?2:0]]){const b=new C(rom,{compactSink:capture?()=>{}:null});let calls=0;b._call=function(...args){calls++;return HotDirectBoardFacade.prototype._call.apply(this,args);};b.beginRun();b.nativeTick();b.quantum(0);assert.equal(calls,expected);b.endRun();b.close();}}});
test('CAPON exact ordered full event objects match original provider',()=>{const runs=[baselineProvider,createOwnedProvider].map(factory=>{const seen=[],p=factory({compactSink:e=>seen.push(e)});p.callbacks.clockTransfer(new Uint32Array(),1);begin(p);p.callbacks.clockTransfer(Uint32Array.of(1,3,3,1,2,1),5);p.callbacks.readPhysical(0x500,1);p.callbacks.packedScalar(3,0x43,1,0x34);p.callbacks.clockTransfer(new Uint32Array(),6);p.end();const state=p.checkpoint();p.close();return {seen,state};});assert.deepEqual(runs[0],runs[1]);});
test('new CLI inverse changes only provider and runtime identity imports',()=>{const prefix='fr'+'om ';const s=readFileSync(new URL('../scripts/run-i80386-native-owned-clock-alloc.mjs',import.meta.url),'utf8').replace(prefix+"'./bochs-cpu3-native-owned-clock-alloc/provider.mjs'",prefix+"'./bochs-cpu3-native-owned-clock/provider.mjs'").replace(prefix+"'./bochs-cpu3-native-owned-clock-alloc/identity.mjs'",prefix+"'./bochs-cpu3-native-owned-main/identity.mjs'");assert.equal(s,readFileSync(new URL('../scripts/run-i80386-native-owned-main.mjs',import.meta.url),'utf8'));});
