/**
 * THE LED ORACLES NOTHING WAS READING.
 *
 * test/golden/ngspice_oracles.json has carried three real LED measurements --
 * led_red_220, led_red_1000, led_blue_470 -- and until this file NO TEST
 * CONSUMED THEM. Every LED accuracy claim in the repo was scored against
 * test/golden/oracles.json, which is generated by compute_oracles.py with an
 * `rd` field and whose expected current for led_blue_470 is exactly
 * (5.0 - 3.2)/(470 + 10 + 25): that file IS the piecewise model written down.
 * Its header note "computed independently from bw-board solver" is true of the
 * SOLVER and false of the MODEL, so the only LED oracle in the tree could never
 * disagree with the piecewise path no matter how wrong that path was.
 *
 * An unread oracle is indistinguishable from an absent one, and worse, because
 * its presence is cited as coverage.
 *
 * WHAT THIS FILE SEPARATES. Two different questions were being conflated:
 *
 *   SOLVER   -- given the SAME device, does our MNA find the same operating
 *               point ngspice does? Answered by injecting is/n/rs from the
 *               recorded netlist. This is a numerical claim and it is tight.
 *
 *   CALIBRATION -- given a user who types `vf`, do we build the right device?
 *               That depends on n and rs, which vf alone cannot determine, so
 *               it is a modelling choice and is tracked as a ratchet, not an
 *               equality.
 *
 * The first was never in doubt and turns out to be excellent. The second is
 * where the error lives.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {BoardImpl} from '../src/board.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CORPUS = JSON.parse(
    fs.readFileSync(path.join(ROOT, 'test/golden/ngspice_oracles.json'), 'utf8'));

/** Pull the device and bias out of a recorded deck. Null when it is not an LED circuit. */
export const ledCase = entry => {
    const nl = entry.netlist;
    if (!nl || !/\.model\s+\w+\s+D\(/i.test(nl)) return null;
    const v = nl.match(/^V1\s+\w+\s+\w+\s+([\d.]+)/mi);
    const r = nl.match(/^R1\s+\w+\s+\w+\s+([\d.]+)/mi);
    const m = nl.match(/IS\s*=\s*([\d.eE+-]+)\s+N\s*=\s*([\d.]+)\s+RS\s*=\s*([\d.]+)/i);
    if (!v || !r || !m) return null;
    return {
        name: entry.name,
        vcc: Number(v[1]), r: Number(r[1]),
        is: Number(m[1]), n: Number(m[2]), rs: Number(m[3]),
        truthI: Math.abs(entry.measured['v1#branch'])
    };
};

const solve = (vcc, r, params) => {
    const parts = [
        {id: 'VCC', kind: 'vcc', params: {}, terminals: ['vcc']},
        {id: 'GND', kind: 'gnd', params: {}, terminals: ['gnd']},
        {id: 'R1', kind: 'resistor', params: {ohms: r}, terminals: ['a', 'b']},
        {id: 'LED1', kind: 'led', params, terminals: ['anode', 'cathode']}];
    const nets = [
        {id: 'nv', terminals: [{part: 'VCC', terminal: 'vcc'}, {part: 'R1', terminal: 'a'}]},
        {id: 'na', terminals: [{part: 'R1', terminal: 'b'}, {part: 'LED1', terminal: 'anode'}]},
        {id: 'ng', terminals: [{part: 'GND', terminal: 'gnd'}, {part: 'LED1', terminal: 'cathode'}]}];
    const b = new BoardImpl(vcc);
    b.setNetlist(parts, nets);
    return Math.abs(b.branchCurrent('LED1', 'anode'));
};

const LED_CASES = CORPUS.results.map(ledCase).filter(Boolean);

test('every recorded oracle names the device it measured', () => {
    const naked = CORPUS.results.filter(r => !r.netlist && !r.error).map(r => r.name);
    assert.deepEqual(naked, [],
        'these readings record a NUMBER but not the CIRCUIT that produced it, so nothing can '
        + 'check them without rerunning the generator -- which is exactly how a silently '
        + 'clamped IS survived in led_blue_470: ' + JSON.stringify(naked));
});

test('the LED oracles are actually reachable from here', () => {
    // ANTI-VACUITY. Every assertion below loops over LED_CASES, so an empty or
    // half-parsed set would make this whole file pass while checking nothing --
    // the precise failure it exists to end.
    assert.ok(LED_CASES.length >= 3,
        `only ${LED_CASES.length} LED oracle(s) parsed out of ${CORPUS.results.length} entries; `
        + 'the netlist shape changed and this suite has gone vacuous');
    for (const c of LED_CASES) {
        assert.ok(c.truthI > 1e-6, `${c.name}: recorded current ${c.truthI} is not a driven reading`);
    }
});

test('SOLVER: with the identical device, our MNA finds ngspice\'s operating point', () => {
    for (const c of LED_CASES) {
        const i = solve(c.vcc, c.r, {vf: 2.0, model: 'shockley', is: c.is, n: c.n, rs: c.rs});
        const err = Math.abs(i - c.truthI) / c.truthI;
        assert.ok(err < 0.005,
            `${c.name}: ours ${(i * 1e3).toFixed(5)} mA vs ngspice ${(c.truthI * 1e3).toFixed(5)} mA `
            + `= ${(err * 100).toFixed(2)}% (need <0.5%). The DEVICE is identical here, so this is a `
            + 'numerical claim about the solver, not a modelling choice.');
    }
});

// CALIBRATION RATCHET, MEASURED 2026-09-12 against the ngspice devices above.
// A user types `vf`; we must build the device. `vf` alone cannot determine n
// and rs, so this is a modelling choice and the number may only FALL.
//
//   piecewise, as it stands   14.39 %   <- vf is treated as the KNEE, so the
//                                          total drop at 20 mA is vf + 0.020*rd
//   piecewise, knee corrected  4.14 %
//   shockley rs=2              6.38 %
//   shockley rs=10             0.09 %   <- rs == LED_RD, i.e. one device
//
// Do NOT lower this by choosing rs to fit: a sweep over the reference devices
// elects whatever RS they were built with (a 0.04 % diagonal at RS = 5, 10, 25
// and 40), so fitting rs to this corpus is a tautology. Move it by making the
// two junction paths describe the SAME device.
const CALIBRATION_WORST = 0.1439;

test('CALIBRATION: what a user gets by typing vf, as a ratchet', () => {
    let worst = 0, worstName = '';
    for (const c of LED_CASES) {
        // the datasheet vf of the recorded device: total drop at its rated 20 mA
        const nVt = c.n * 0.02585;
        const vf = nVt * Math.log(0.020 / c.is + 1) + 0.020 * c.rs;
        const i = solve(c.vcc, c.r, {vf});           // default path, no device hints
        const err = Math.abs(i - c.truthI) / c.truthI;
        if (err > worst) { worst = err; worstName = c.name; }
    }
    assert.ok(worst <= CALIBRATION_WORST + 1e-4,
        `worst calibration error ${(worst * 100).toFixed(2)}% (${worstName}) exceeds the recorded `
        + `ratchet ${(CALIBRATION_WORST * 100).toFixed(2)}%. This number may only fall.`);
    // And it must not be silently vacuous if the default path ever stops being reached.
    assert.ok(worst > 0, 'the calibration path produced an exact match, which is not credible -- '
        + 'check that the default (non-injected) device is actually being built');
});
