/* Synchronous Node bridge. Native owns persistent execute pages; JS spans are copied. */
#include <node_api.h>
#include <cstring>
#include <string>
#include <thread>
#include "../bochs-cpu3-native-direct-board/abi.h"
namespace {
napi_env env; napi_ref board; bool initialized=false,closed=false,busy=false;
std::thread::id owner;
bool ok(napi_status s){return s==napi_ok;}
napi_value fail(const char *s){napi_throw_error(env,nullptr,s);return nullptr;}
napi_value number(uint32_t n){napi_value v;napi_create_uint32(env,n,&v);return v;}
bool get(napi_value o,const char *k,napi_value *v){return ok(napi_get_named_property(env,o,k,v));}
bool u32(napi_value v,uint32_t *n){double d;if(!ok(napi_get_value_double(env,v,&d))||d<0||d>4294967295.0||d!=(uint32_t)d)return false;*n=(uint32_t)d;return true;}
bool field(napi_value o,const char *k,uint32_t *n){napi_value v;return get(o,k,&v)&&u32(v,n);}
bool bytes(napi_value v,uint8_t **p,size_t *n){napi_typedarray_type t;napi_value ab;size_t off;void *data;if(!ok(napi_get_typedarray_info(env,v,&t,n,&data,&ab,&off))||t!=napi_uint8_array)return false;*p=(uint8_t*)data;return true;}
napi_value copied(const uint8_t *p,size_t n){napi_value ab,v;void *dst;if(!ok(napi_create_arraybuffer(env,n,&dst,&ab)))return nullptr;memcpy(dst,p,n);if(!ok(napi_create_typedarray(env,napi_uint8_array,n,ab,0,&v)))return nullptr;return v;}
bool call(const char *name,size_t argc,napi_value *argv,napi_value *result){napi_value self,fn;return ok(napi_get_reference_value(env,board,&self))&&get(self,name,&fn)&&ok(napi_call_function(env,self,fn,argc,argv,result));}
bool metadata(napi_value r,bw_direct_metadata *m){return field(r,"decoded",&m->decoded)&&field(r,"kind",&m->kind)&&field(r,"effect",&m->effect)&&field(r,"generation",&m->generation)&&field(r,"mappingEpoch",&m->mapping_epoch)&&field(r,"boardA20",&m->board_a20);}
int memory(void*,uint32_t raw,uint32_t len,const uint8_t *operand,uint8_t *observed,bw_direct_metadata *m){if(len==0||len>16)return 0;napi_handle_scope scope;if(!ok(napi_open_handle_scope(env,&scope)))return 0;napi_value args[2]={number(raw),operand?copied(operand,len):number(len)},r;uint8_t *p;size_t n;bool success=call(operand?"writePhysical":"readPhysical",2,args,&r);napi_value value;if(success)success=get(r,"bytes",&value)&&bytes(value,&p,&n)&&n==len&&metadata(r,m);if(success)memcpy(observed,p,len);napi_close_handle_scope(env,scope);return success;}
int page(void*,uint32_t raw,uint8_t *dst,bw_direct_page_metadata *m){napi_handle_scope scope;if(!ok(napi_open_handle_scope(env,&scope)))return 0;napi_value arg=number(raw),r,v;uint8_t *p;size_t n;bool success=call("admitExecutePage",1,&arg,&r)&&get(r,"bytes",&v)&&bytes(v,&p,&n)&&n==4096&&field(r,"decoded",&m->decoded)&&field(r,"kind",&m->kind)&&field(r,"generation",&m->generation)&&field(r,"mappingEpoch",&m->mapping_epoch)&&field(r,"boardA20",&m->board_a20);size_t size=0;if(success)success=get(r,"sha256",&v)&&ok(napi_get_value_string_utf8(env,v,m->sha256,65,&size))&&size==64;if(success){for(size_t i=0;i<64;i++)if(!((m->sha256[i]>='0'&&m->sha256[i]<='9')||(m->sha256[i]>='a'&&m->sha256[i]<='f')))success=false;}if(success)memcpy(dst,p,4096);napi_close_handle_scope(env,scope);return success;}
int scalar(void*,uint32_t op,uint32_t a,uint32_t b,uint32_t c,uint32_t *value,uint32_t *a20,uint32_t *epoch){napi_handle_scope scope;if(!ok(napi_open_handle_scope(env,&scope)))return 0;napi_value args[3]={number(a),number(b),number(c)},r,state;const char *name=op==1?"nativeTick":op==2?"quantum":op==3?"outPort":op==4?"acknowledgeIrq":nullptr;bool success=name&&call(name,op==3?3:op==2?1:0,args,&r);if(success)success=op==3?field(r,"value",value):u32(r,value);if(success){if(op==3){success=field(r,"mappingEpoch",epoch)&&field(r,"boardA20",a20);}else{success=call("mappingState",0,nullptr,&state)&&field(state,"mappingEpoch",epoch)&&field(state,"boardA20",a20);}}napi_close_handle_scope(env,scope);return success;}
bw_direct_callbacks callbacks={nullptr,memory,page,scalar};
bool allowed(){return initialized&&!closed&&!busy&&std::this_thread::get_id()==owner;}
napi_value array(const uint32_t *p,size_t n){napi_value out;napi_create_array_with_length(env,n,&out);for(size_t i=0;i<n;i++)napi_set_element(env,out,i,number(p[i]));return out;}
napi_value snapshot(){bw_direct_snapshot s={};if(!bw_direct_inspect(&s))return fail("native inspect rejected");napi_value out;napi_create_object(env,&out);napi_set_named_property(env,out,"state",array(s.state,20));napi_set_named_property(env,out,"extra",array(s.extra,20));napi_set_named_property(env,out,"segments",array(&s.segments[0][0],90));napi_set_named_property(env,out,"system",array(&s.system[0][0],30));napi_set_named_property(env,out,"debug",array(s.debug,6));napi_value n,q;napi_create_bigint_uint64(env,s.native_ticks,&n);napi_create_bigint_uint64(env,s.successful_quanta,&q);napi_set_named_property(env,out,"nativeTicks",n);napi_set_named_property(env,out,"successfulQuanta",q);napi_set_named_property(env,out,"mappingEpoch",number(s.mapping_epoch));napi_set_named_property(env,out,"boardA20",number(s.board_a20));return out;}
napi_value invoke(napi_env e,napi_callback_info info){env=e;size_t argc=5;napi_value argv[5];void *data;napi_get_cb_info(env,info,&argc,argv,nullptr,&data);const char *op=(const char*)data;if(strcmp(op,"create")==0){if(initialized||argc!=4)return fail("one create lifetime requires config, ROM, board, capture");uint8_t *rom;size_t len;size_t size;bool capture;if(!bytes(argv[1],&rom,&len)||len!=65536||!ok(napi_get_value_string_utf8(env,argv[0],nullptr,0,&size))||size>16384||!ok(napi_get_value_bool(env,argv[3],&capture)))return fail("invalid create arguments");std::string config(size+1,'\0');napi_get_value_string_utf8(env,argv[0],config.data(),config.size(),&size);if(config.find('\0')!=size)return fail("configuration contains NUL");napi_create_reference(env,argv[2],1,&board);initialized=true;owner=std::this_thread::get_id();busy=true;int result=bw_direct_initialize(config.c_str(),rom,len,&callbacks,capture);busy=false;if(!result)return fail("native initialize rejected");return snapshot();}if(!allowed())return fail("direct lifecycle, thread or reentry rejected");if(strcmp(op,"inspect")==0)return snapshot();if(strcmp(op,"setIRQ")==0){bool asserted;if(argc!=1||!ok(napi_get_value_bool(env,argv[0],&asserted)))return fail("IRQ requires boolean");if(!bw_direct_set_irq_line(asserted))return fail("native IRQ rejected");return snapshot();}if(strcmp(op,"close")==0){if(!bw_direct_close())return fail("native close rejected");closed=true;napi_delete_reference(env,board);board=nullptr;napi_value v;napi_get_undefined(env,&v);return v;}uint32_t n,q;uint64_t deadline;bool lossless;if(argc!=3||!u32(argv[0],&n)||!u32(argv[1],&q)||n==0||q==0||n>600||q>300||!ok(napi_get_value_bigint_uint64(env,argv[2],&deadline,&lossless))||!lossless)return fail("invalid bounded resume");bw_cpu3_combined_paging_ram_slice_result result={};busy=true;int success=bw_direct_resume(n,q,deadline,&result);busy=false;if(!success)return fail("native resume rejected");napi_value out=snapshot();if(!out)return nullptr;napi_set_named_property(env,out,"sliceBytes",copied((uint8_t*)&result,sizeof result));napi_set_named_property(env,out,"reason",number(result.reason));napi_set_named_property(env,out,"activityState",number(result.activity_state));napi_set_named_property(env,out,"chargedNativeTicks",number(result.charged_native_ticks));napi_set_named_property(env,out,"chargedQuanta",number(result.charged_quanta));return out;}
napi_value init(napi_env e,napi_value exports){env=e;for(const char *name:{"create","resume","setIRQ","inspect","close"}){napi_value fn;napi_create_function(env,name,NAPI_AUTO_LENGTH,invoke,(void*)name,&fn);napi_set_named_property(env,exports,name,fn);}return exports;}
}
NAPI_MODULE(NODE_GYP_MODULE_NAME,init)
