from pathlib import Path
import json,hashlib,subprocess
P=Path(__file__).resolve().parent;T=Path('/mnt/volume1/tmp-astra/native-owned-dispatch-runtime-prepared-20261002');W=Path('/tmp/bw-board-386-owned-dispatch-runtime-20261002');j=lambda p:json.loads(p.read_bytes());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();digest=lambda b:hashlib.sha256(b).hexdigest();checks=0
def ck(v):
 global checks
 assert v;checks+=1
A=j(P/'binding-draft.json');ck(sha(P/'binding-draft.json')=='9a2ade3a06cb974ffd451f6ac80dcc9e8d11e6078553b2ef47a88066326b1e5c');ck(A['revision']=='2c688e69cae516b9749d70a126a3b474707d5cb7');ck(len(A['sourceHashes'])==112 and len(A['compiledSourceHashes'])==103 and len(A['artifactHashes'])==223)
for root,rev,mapping in [(W,A['revision'],A['sourceHashes']),(Path(A['compiledWorktree']),A['compiledRevision'],A['compiledSourceHashes'])]:
 ck(subprocess.check_output(['git','rev-parse','HEAD'],cwd=root,text=True).strip()==rev);ck(not subprocess.check_output(['git','status','--porcelain'],cwd=root).strip())
 for n,h in mapping.items():ck(sha(root/n)==h==digest(subprocess.check_output(['git','show',rev+':'+n],cwd=root)))
for n,h in A['compiledSourceHashes'].items():ck(A['sourceHashes'][n]==h)
for n,h in A['artifactHashes'].items():ck(sha(Path(n))==h)
for n,h in A['helperHashes'].items():ck(sha(P/n)==h)
for n in ['driver','baselineNativeCapture','baselineNativeTrace','baselineNativeJournal','baseline','configuration']:ck(A[n]in A['artifactHashes'])
stat=j(T/'static-admission/stdout');ck(stat['source']=={'revision':A['revision'],'hashes':A['sourceHashes']});ck(stat['provenance']==A['expectedProvenance']);ck(stat['input']==A['buildInput']);ck(stat['provenance']['compiled']['revision']==A['compiledRevision'] and stat['provenance']['compiled']['hashes']==A['compiledSourceHashes']);ck(stat['provenance']['compiled']['proof']==j(Path('/mnt/volume1/tmp-astra/native-owned-in8-r3-ci-restored-20261002/source-admission.stdout'))['provenance']);ck(stat['provenance']['runtime']==stat['source']);ck(T.joinpath('static-admission/before.json').read_bytes()==T.joinpath('static-admission/after.json').read_bytes());ex=j(T/'static-admission/exit.json');ck(ex['returncode']==0 and not ex['timedOut']);ck(sha(T/'static-admission/stdout')==ex['stdoutSha256']);ck(sha(T/'static-admission/stderr')==ex['stderrSha256']);ck(sha(T/'source-freeze.json')=='231deecf053fe09e81961e991850c714b61ecd9ba4b358287b9e33f6af697aab')
plan=j(P/'plan.json');ck([(x['label'],x['nativeTrace'],x['hostJournal'])for x in plan['cells']]==[('smoke-off',False,False),('fulltrace-on',True,True),('trace-fast',True,False)]);ck(not any((P/n).exists()for n in ['smoke-off','fulltrace-on','trace-fast']))
out={'status':'PASS_DISPATCH_FINAL112_RUNTIME103_COMPILED_THREE_CELL_STATIC_READINESS','checks':checks,'bindingDraftSha256':sha(P/'binding-draft.json'),'runtimeRevision':A['revision'],'runtimeInputs':112,'frozenDispatchInputs':106,'compiledRevision':A['compiledRevision'],'compiledInputs':103,'artifactPins':223,'helperHashes':A['helperHashes'],'scope':'Actual clean currentGit112/compiled103/maps, all223artifact pins, complete actual static-admission proof/origin/buildInput and helper pins authenticated. Three exact bounded fresh cells OFF/ON/nullsink trace-fast preserve qualified fixture full166/reference RAM/physical state, every canonical row and entire ON journal. Native guards/default unchanged; root-only execution approval still required; no guest/addon executed by auditor.'};q=P/'independent-final-readiness-audit.json';assert not q.exists();q.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out))
