/** Closed fixed paged INT/IRET differential driver; build authority pending. No execution on import. */
import assert from 'node:assert/strict';
import {mkdirSync,lstatSync,realpathSync} from 'node:fs';
import {persistEvidence} from './evidence.mjs';
import {resolve,isAbsolute} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {createPagedIntIretOracle} from './reference.mjs';
import {nativeCr0Source as cr0WriteSource} from '../bochs-cpu3-native-protected-ram/cpu-profile.mjs';
import {resetSource} from '../bochs-cpu3-native-ram-bootstrap/reference.mjs';
import {createDriverIntIretProvider,profileProviderSha256,deriveDriverProvider} from './driver-provider.mjs';
import {nativeIntIretProfile} from './provider-profile.mjs';
import {namedCuts,layout} from './profile.mjs';
import {compareBoundary,intIretProgress,validateMilestones,intIretParityPolicy,intIretNativeSources,wholeNativeWords,validateFinalPages,validateMemoryTape,validateNativeEffects} from './parity.mjs';
import {compiledRevision,driverSourceIdentity,authenticateIntIretCompiled,regularBytes,sha,requireReadyBuild} from './driver-auth.mjs';
const ramRomSha256=nativeIntIretProfile.romSha256;
// Logical JSON serialization is retained by the transport helper.
export function validateInput(v){
 const ready=requireReadyBuild();const names=['compiledRoot','compiledRevision','driverRevision','driverSourceSha256','addon','sha256','configuration','preparedManifest','preparedManifestSha256','buildReceipt','buildReceiptSha256','output','nativeTrace'];assert.deepEqual(Object.keys(v).sort(),names.sort());
 assert.equal(v.compiledRevision,compiledRevision);assert.equal(v.sha256,ready.addonSha256);assert.equal(v.preparedManifestSha256,ready.staticAuthority.preparedManifestSha256);assert.equal(v.buildReceiptSha256,ready.staticAuthority.buildReceiptSha256);assert.equal(v.nativeTrace,false,'first fixed trace-OFF correctness child');assert.match(v.driverRevision,/^[a-f0-9]{40}$/);
 for(const key of names.filter(k=>!['compiledRevision','driverRevision','nativeTrace'].includes(k))){assert.equal(typeof v[key],'string');if(key.endsWith('Sha256')||key==='sha256')assert.match(v[key],/^[a-f0-9]{64}$/);else assert.ok(isAbsolute(v[key])&&resolve(v[key])===v[key]&&v[key].length<=4096&&!/[\0\r\n]/.test(v[key]));}return v;
}
export function finalizeAuthentication(receipt,primary,before,after,readFailure=null){
 try{if(readFailure)throw readFailure;const keys=['input','driver','compiled','build','configuration','node'];assert.deepEqual(Object.keys(before).sort(),keys.sort());assert.deepEqual(Object.keys(after).sort(),keys.sort());for(const key of keys){assert.notEqual(before[key],undefined,'available initial '+key);assert.notEqual(after[key],undefined,'available final '+key);assert.deepEqual(after[key],before[key],'final '+key);}}
 catch(e){receipt.finalAuthenticationError=String(e);receipt.status='FAIL';return primary??e;}return primary;
}
async function run(input,inputPath){
 validateInput(input);verifyHeldLifecycle();assert.equal(realpathSync(process.argv[1]),realpathSync(fileURLToPath(import.meta.url)));assert.equal(process.version,'v22.23.3');assert.deepEqual(process.execArgv,['--max-old-space-size=128']);for(const key of ['NODE_OPTIONS','NODE_PATH','LD_PRELOAD','LD_AUDIT','BW_HOT_NAPI_PROFILE','NODE_V8_COVERAGE'])assert.ok(!process.env[key]);
 const parent=resolve(input.output,'..');assert.ok(lstatSync(parent).isDirectory());assert.equal(realpathSync(parent),parent);mkdirSync(input.output,{recursive:false});
 const receipt={schema:'bw.paged-int-iret.native-js-correctness.v1',status:'FAIL',input,buildRun:requireReadyBuild().buildRun,policy:intIretParityPolicy,resetSource,cr0WriteSource,intIretNativeSources,providerAdapter:{parentSha256:profileProviderSha256,sha256:sha(deriveDriverProvider().bytes)},boundaries:[],cuts:[],cleanup:{}};receipt.inputSha256Before=sha(regularBytes(inputPath,16384));assert.deepEqual(JSON.parse(regularBytes(inputPath,16384)),input);
 // Small outcome is written before capped lossless full evidence; storage never replaces primary.
 const write=()=>persistEvidence(receipt,input.output,primary);
 let provider,oracle,api,identity,compiled,primary=null,native,progress={n:0,q:0},resumes=0,zeroQ=0;
 const compare=(kind,dq=0)=>{const board=provider.checkpoint(),js=oracle.checkpoint(),pages=provider.ramPages();receipt.lastComparison={kind,native,board,javascript:js,nativeHostPages:pages};const comparison=compareBoundary(native,board,js,pages,kind,dq);receipt.lastComparison.comparison=comparison;receipt.boundaries.push(receipt.lastComparison);const name=oracle.milestone();if(name&&!receipt.cuts.some(c=>c.name===name)){assert.equal(name,namedCuts[receipt.cuts.length]?.name,'ordered actual cuts');receipt.cuts.push({name,q:js.q,native,board,javascript:js,pages,comparison});}};
 try{
  receipt.driverBefore=driverSourceIdentity();assert.equal(receipt.driverBefore.revision,input.driverRevision);assert.equal(sha(Buffer.from(JSON.stringify(receipt.driverBefore))),input.driverSourceSha256);receipt.node=realpathSync(process.execPath);receipt.nodeBefore=sha(regularBytes(receipt.node,128<<20));
  const b=regularBytes(input.preparedManifest,2<<20);assert.equal(sha(b),input.preparedManifestSha256);const manifest=JSON.parse(b);receipt.compiledBefore=authenticateIntIretCompiled(input.compiledRoot,manifest);
  identity=await import(pathToFileURL(resolve(input.compiledRoot,'scripts/bochs-cpu3-native-paged-int-iret/build-identity.mjs')).href);compiled=identity.sourceIdentity();assert.deepEqual(compiled,receipt.compiledBefore);
  receipt.build=identity.authenticateBuild(input,compiled);receipt.configuration=identity.authenticateConfiguration(input.configuration,manifest);assert.equal(sha(regularBytes(input.addon)),requireReadyBuild().addonSha256);assert.equal(sha(regularBytes(resolve(manifest.preparedTree,resetSource.path))),resetSource.sha256,'attested Bochs reset initialization source');assert.equal(sha(regularBytes(resolve(manifest.preparedTree,cr0WriteSource.path))),cr0WriteSource.sha256,'attested Bochs CPU3 CR0 assignment source');
  for(const source of intIretNativeSources)assert.equal(sha(regularBytes(resolve(manifest.preparedTree,source.path))),source.sha256,'attested protected descriptor source '+source.path);
  assert.equal(manifest.actualPreparedHashes['bochs/owned-paged-int-iret-provider.mjs'],profileProviderSha256);assert.equal(manifest.actualPreparedHashes['bochs/owned-paged-int-iret-ROM.bin'],ramRomSha256);
  provider=await createDriverIntIretProvider();oracle=await createPagedIntIretOracle();assert.equal(sha(provider.rom),ramRomSha256);api=createRequire(import.meta.url)(input.addon);assert.equal(api.abiVersion,4);for(const name of ['create','resume','setIRQ','inspect','close'])assert.equal(typeof api[name],'function');
  native=api.create(input.configuration,provider.rom,provider.callbacks,false);assert.equal(Number(native.nativeTicks),0);assert.equal(Number(native.successfulQuanta),0);wholeNativeWords(native);compare('reset');
  while(oracle.milestone()!=='returned-from-IRET-before-HLT'){
   assert.ok(resumes<1024&&zeroQ<512,'bounded actual resume protocol');const stage=provider.stage();assert.deepEqual(stage,oracle.stage(),'actual PIC line');assert.equal(stage.asserted,false,'fixture IRQ outside scope');if(stage.changed){native=api.setIRQ(stage.asserted);compare('line');}
   // Preserve both phase records; staged pages must not be hidden by a board hash.
   receipt.stages??=[];receipt.stages.push({q:progress.q,native:provider.checkpoint(),javascript:oracle.checkpoint(),comparison:'UNMATCHED_STAGE_RECORD'});provider.begin();let resumeError=null;
   try{native=api.resume(1,1,0xffffffffffffffffn);}catch(e){resumeError=e;receipt.resumeError=String(e);throw e;}finally{try{provider.end();}catch(e){receipt.endError=String(e);if(!resumeError)throw e;}}
   resumes++;const next=intIretProgress(progress,native);if(next.dq)assert.equal(oracle.step().q,next.q);else zeroQ++;progress=next;compare('resume',next.dq);
  }
  receipt.lastReturnedNative=native;assert.equal(native.activityState,0);native=api.inspect();assert.deepEqual(wholeNativeWords(native),wholeNativeWords(receipt.lastReturnedNative),'paused inspect unchanged166');assert.equal(Number(native.nativeTicks),progress.n);assert.equal(Number(native.successfulQuanta),progress.q);receipt.finalNative=native;compare('final-inspect');receipt.milestones=validateMilestones(receipt.cuts);receipt.progress={...progress,resumes,zeroQ};
  receipt.nativeFinal=provider.settleCheckpoint();receipt.javascriptFinal=oracle.settle();receipt.nativeFinal.pages=provider.ramPages();assert.deepEqual(receipt.nativeFinal.state.board,receipt.javascriptFinal.board,'full settled board');validateFinalPages(receipt.nativeFinal.pages);for(const key of Object.keys(layout))assert.deepEqual(receipt.nativeFinal.pages[key],receipt.javascriptFinal.pages[key],'whole direct final '+key+' page');assert.equal(receipt.nativeFinal.ramSha256,receipt.javascriptFinal.ramSha256,'whole raw physical RAM hash');receipt.nativeOwnedEffects=validateNativeEffects(receipt.nativeFinal.state,receipt.javascriptFinal,true);receipt.nativeMemoryEvents=provider.memoryEvents();receipt.nativeMemoryEvidence=validateMemoryTape(receipt.nativeMemoryEvents,receipt.nativeFinal.state);receipt.javascriptDeliveries=receipt.javascriptFinal.deliveries;assert.equal(receipt.javascriptDeliveries.length,1);receipt.javascriptMemoryEffects={stores:receipt.javascriptFinal.stores,updates:receipt.javascriptFinal.updates,accesses:receipt.javascriptFinal.accesses};assert.deepEqual(provider.records(),[],'no PIO');receipt.status='PASS';
 }catch(e){primary=e;receipt.error=String(e);receipt.progress={...progress,resumes,zeroQ};if(native)receipt.lastSuccessfullyReturnedNative=native;for(const [key,fn]of [['partialProvider',()=>({state:provider.checkpoint(),pages:provider.ramPages(),ports:provider.records(),memoryEvents:provider.memoryEvents()})],['partialJavascript',()=>oracle.checkpoint()]])try{receipt[key]=fn();}catch(partial){receipt[key+'Unavailable']=String(partial);}}
 finally{
  // Cleanup and post-authentication never replace the first divergence.
  for(const [key,object]of [['native',api],['provider',provider],['javascript',oracle]])if(object)try{object.close();receipt.cleanup[key]='closed';}catch(e){receipt.cleanup[key+'Error']=String(e);if(!primary)primary=e;}
  let readFailure=null;receipt.finalReadErrors={};const probe=(key,fn)=>{try{receipt[key]=fn();}catch(e){receipt.finalReadErrors[key]=String(e);readFailure??=e;}};
  probe('inputSha256After',()=>sha(regularBytes(inputPath,16384)));probe('driverAfter',driverSourceIdentity);probe('nodeAfter',()=>sha(regularBytes(receipt.node,128<<20)));
  if(identity){probe('compiledAfter',()=>identity.sourceIdentity());probe('buildAfter',()=>identity.authenticateBuild(input,compiled??receipt.compiledAfter));probe('configurationAfter',()=>identity.authenticateConfiguration(input.configuration,identity.boundedJson(input.preparedManifest,input.preparedManifestSha256)));}
  primary=finalizeAuthentication(receipt,primary,{input:receipt.inputSha256Before,driver:receipt.driverBefore,compiled:receipt.compiledBefore,build:receipt.build,configuration:receipt.configuration,node:receipt.nodeBefore},{input:receipt.inputSha256After,driver:receipt.driverAfter,compiled:receipt.compiledAfter,build:receipt.buildAfter,configuration:receipt.configurationAfter,node:receipt.nodeAfter},readFailure);
  if(primary)receipt.status='FAIL';const persistence=await write();primary=persistence.primary;
 }
 if(primary)throw primary;return receipt;
}
// Closed CLI entry follows initialized source-verification declarations.

// CHECKED_HELD_LIFECYCLE_DERIVATIVE
import {readFileSync} from 'node:fs';
export const lifecycleParentSha256="032896bab9ecfadfcdbb63298eaf059cdf352dbfad0d1da27b1d6139b08d6006";
export const lifecycleEdits=Object.freeze([{"old":"createNonidentityPagingOracle","next":"createPagedIntIretOracle","count":2},{"old":"createDriverPagingProvider","next":"createDriverIntIretProvider","count":2},{"old":"nativePagingProfile","next":"nativeIntIretProfile","count":2},{"old":"pagingProgress","next":"intIretProgress","count":2},{"old":"pagingParityPolicy","next":"intIretParityPolicy","count":2},{"old":"pagingNativeSources","next":"intIretNativeSources","count":3},{"old":"authenticatePagingCompiled","next":"authenticateIntIretCompiled","count":2},{"old":"nonidentity-paging","next":"paged-int-iret","count":4},{"old":"nonidentity paging","next":"paged INT/IRET","count":1},{"old":"!=='before-HLT'","next":"!=='returned-from-IRET-before-HLT'","count":1},{"old":"regularBytes(input.preparedManifest,1<<20)","next":"regularBytes(input.preparedManifest,2<<20)","count":1},{"old":"validateInput(input);assert.equal","next":"validateInput(input);verifyHeldLifecycle();assert.equal","count":1},{"old":"wholeNativeWords,validateFinalPages,validateMemoryTape}","next":"wholeNativeWords,validateFinalPages,validateMemoryTape,validateNativeEffects}","count":1},{"old":"receipt.nativeMemoryEvents=provider.memoryEvents();","next":"receipt.nativeOwnedEffects=validateNativeEffects(receipt.nativeFinal.state,receipt.javascriptFinal,true);receipt.nativeMemoryEvents=provider.memoryEvents();","count":1},{"old":"receipt.javascriptMemoryEffects={stores:","next":"receipt.javascriptDeliveries=receipt.javascriptFinal.deliveries;assert.equal(receipt.javascriptDeliveries.length,1);receipt.javascriptMemoryEffects={stores:","count":1},{"old":"if(process.argv[1]&&realpathSync(process.argv[1])===realpathSync(fileURLToPath(import.meta.url))){assert.equal(process.argv.length,3);await run(JSON.parse(regularBytes(process.argv[2],16384)),process.argv[2]);}\n","next":"// Closed CLI entry follows initialized source-verification declarations.\n","count":1},{"old":"import {mkdirSync,writeFileSync,lstatSync,realpathSync} from 'node:fs';","next":"import {mkdirSync,lstatSync,realpathSync} from 'node:fs';\nimport {persistEvidence} from './evidence.mjs';","count":1},{"old":" const write=()=>{const bytes=serialize(receipt)+'\\n';assert.ok(Buffer.byteLength(bytes)<=16<<20);writeFileSync(resolve(input.output,receipt.status==='PASS'?'capture.json':'first-divergence.json'),bytes,{flag:'wx'});};","next":" // Small outcome is written before capped lossless full evidence; storage never replaces primary.\n const write=()=>persistEvidence(receipt,input.output,primary);","count":1},{"old":"  if(primary)receipt.status='FAIL';write();","next":"  if(primary)receipt.status='FAIL';const persistence=await write();primary=persistence.primary;","count":1},{"old":"const serialize=v=>JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():ArrayBuffer.isView(x)?Array.from(x):x);\n","next":"// Logical JSON serialization is retained by the transport helper.\n","count":1}].map(Object.freeze));
export function deriveIntIretLifecycle(bytes){assert.equal(sha(bytes),lifecycleParentSha256,'held paging lifecycle source');let s=bytes.toString();for(const e of lifecycleEdits){assert.equal(s.split(e.old).length-1,e.count,'exact lifecycle replacement count');s=s.split(e.old).join(e.next);}let inverse=s;for(const e of [...lifecycleEdits].reverse()){assert.equal(inverse.split(e.next).length-1,e.count,'exact inverse count');inverse=inverse.split(e.next).join(e.old);}assert.equal(inverse,bytes.toString(),'byte-exact held lifecycle inverse');return Buffer.from(s);}
export function verifyHeldLifecycle(){const held=readFileSync(new URL('../bochs-cpu3-native-nonidentity-paging/runner.mjs',import.meta.url));assert.equal(readFileSync(fileURLToPath(import.meta.url)).toString().split("\n// CHECKED_HELD_LIFECYCLE_DERIVATIVE\n")[0],deriveIntIretLifecycle(held).toString(),'executing reviewed lifecycle derivative');}
if(process.argv[1]&&realpathSync(process.argv[1])===realpathSync(fileURLToPath(import.meta.url))){assert.equal(process.argv.length,3);await run(JSON.parse(regularBytes(process.argv[2],16384)),process.argv[2]);}
