from pathlib import Path
import json,hashlib,math
P=Path(__file__).parent;A=P/'artifact';C=A/'_temp/owned-span-cpu';R=C/'gate/results';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();checks=0
def check(x,label):
 global checks
 assert x,label;checks+=1
load=lambda p:json.loads(p.read_bytes())
s=load(R/'summary.json');approved=load(C/'gate/approved-bindings.json');plan=load(C/'gate/plan.json');ref=load(Path('/mnt/volume1/tmp-astra/native-owned-in8-parity-r3-ci-20261002/fulltrace-on/guest/capture.json'))
check(sha(C/'gate/plan.json')==s['planSha256'],'planSHA');check(len(s['records'])==18,'18children');check(load(R/'auth-before.json')==load(R/'auth-after.json'),'fullauthbeforeafter');check(approved['candidateSource']['revision']=='bbf2a73e3d9090e73fe7037f4b8dbd4f6248aaa1'and len(approved['candidateSource']['hashes'])==116,'runtime116');check(approved['baselineSource']['revision']=='fe1eff2039520536350922a2164c8bbe29404c68'and len(approved['baselineSource']['hashes'])==103,'compiled103')
for i,rec in enumerate(s['records']):
 pair=i//2;order=plan['samples']['pairOrder'][pair].split(',');arm=order[i%2];stem=R/(str(pair)+'-'+arm);c=load(stem/'guest/capture.json');inp=R/(str(pair)+'-'+arm+'.input.json');exit=load(stem/'child.exit.json');command=load(stem/'invocation.json')
 check(rec['pair']==pair and rec['arm']==arm and rec['warmup']==(pair<2),'schedule');check(rec['captureSha256']==sha(stem/'guest/capture.json')and rec['inputSha256']==sha(inp),'hashes');check(c['source']==approved['baselineSource'if arm=='BASE'else'candidateSource'],'source');check(c['provenance']==approved['currentCompiledProof'if arm=='BASE'else'currentCandidateProvenance'],'completeprovenance')
 for field in ['reset','final','checkpoints','settled','ramSha256','resetWitness','ramCanonicalSha256','in8Witness','resumes','terminal','closed']:check(c[field]==ref[field],field)
 check(c['resumes']==445 and len(c['checkpoints'])==6,'scheduler');check(c['journal']['rows']==0 and (stem/'guest/callbacks.jsonl').stat().st_size==0,'captureoff');check(exit==rec['exit'],'exitexact');check(exit['returncode']==0 and exit['signal']is None and not exit['timedOut']and not exit['fileLimitReached']and exit['error']is None,'exitPASS');check(exit['RLIMIT_CPU']==120 and exit['RLIMIT_FSIZE']==256<<20 and exit['heapMiB']==512 and exit['niceIncrement']==10,'bounds');check(len(exit['blankEnvironment'])==6 and all(v==''for v in exit['blankEnvironment'].values()),'blankhooks');check(sha(stem/'child.stderr')==exit['stderrSha256'],'stderr');check(c['timing']['executionCPU']['total']==rec['executionCpuTotalUs']==c['timing']['executionCPU']['user']+c['timing']['executionCPU']['system'],'CPU');check(c['timing']['executionNs']==rec['executionNs'],'window')
series={arm:[r['executionCpuTotalUs']for r in s['records']if r['arm']==arm and not r['warmup']]for arm in ['BASE','SPAN']};check(series==s['samplesUs'],'14series');means={a:sum(v)/7 for a,v in series.items()};check(means==s['meansUs'],'means');reduction=100*(1-means['SPAN']/means['BASE']);check(reduction==s['meanReductionPercent'],'reduction');fav=[x<y for x,y in zip(series['SPAN'],series['BASE'])];check(fav==s['favorablePairs'],'pairs');passed=reduction>=10 and all(fav);check(not passed and not s['gatePassed']and s['status']=='ACTUAL_SPAN_PROCESS_CPU_GATE_FAIL_KEEP_FE1','failedgate');check(s['noCumulativeSpeedupClaim'],'scope')
result={'status':'CODER_ACTUAL18_FULL_SEMANTIC_PROVENANCE_RESOURCE_AND_CPU_MATH_PASS','checks':checks,'runId':37061280177,'artifactId':11250412021,'head':'d48ba37f4b38784757275b28f26da71bb9113c11','summarySha256':sha(R/'summary.json'),'gateStatus':s['status'],'meansUs':means,'meanReductionPercent':reduction,'favorablePairs':fav,'scope':'Actual retained18cells audited; no rerun/native execution; negativegate remainsFAILKEEPFE1.'};(P/'coder-actual-audit.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result))
