/** Runtime/tool source and a6 compiled source are distinct authenticated identities. */
import assert from 'node:assert/strict';import {readFileSync,statSync}from 'node:fs';import {execFileSync}from 'node:child_process';import {resolve}from 'node:path';import {fileURLToPath}from 'node:url';
import {sourceIdentity as fixtureIdentity}from '../bochs-cpu3-native-owned-pic-imr/identity.mjs';
import {deriveOwnedPicImrRuntime as deriveOwnedRuntime}from '../bochs-cpu3-native-owned-pic-imr/runtime.mjs';
import {deriveOwnedIn8Napi as deriveOwnedNapi}from '../bochs-cpu3-native-owned-in8/napi.mjs';
import {sha256}from '../bochs-cpu3-native-owned-clock/derive.mjs';
const root=resolve(fileURLToPath(new URL('../../',import.meta.url))),compiledRevision='a6f605280f778b2bc409ef97ac3b40e15874530c';
export const supportAssets=['scripts/prepare-bochs-cpu3-native-owned-pic-imr.mjs', 'scripts/ci-build-i80386-native-owned-pic-imr.py', '.github/workflows/i80386-native-owned-pic-imr-build.yml', 'scripts/run-i80386-native-owned-pic-imr.mjs', 'scripts/bochs-cpu3-native-owned-pic-imr-profile/admission.mjs', 'scripts/bochs-cpu3-native-owned-pic-imr-profile/identity.mjs', 'scripts/bochs-cpu3-native-owned-pic-imr-profile/reset-witness.mjs', 'scripts/bochs-cpu3-native-owned-pic-imr-profile/contract.md', 'test/i80386-native-owned-pic-imr-profile.test.mjs','test/fixtures/i80386-owned-pic-imr-js-reference.json','test/fixtures/i80386-owned-pic-imr-canonical-proof.json'];
export function sourceIdentity(){const source=fixtureIdentity();for(const [p,h]of Object.entries(source.hashes))assert.equal(sha256(execFileSync('git',['show',compiledRevision+':'+p],{cwd:root,maxBuffer:32<<20})),h,'unchanged frozen111 '+p);for(const p of supportAssets){const b=readFileSync(resolve(root,p));assert.equal(sha256(b),sha256(execFileSync('git',['show',source.revision+':'+p],{cwd:root,maxBuffer:32<<20})));source.hashes[p]=sha256(b);}assert.equal(Object.keys(source.hashes).length,122);return source;}
export function authenticateBuild(input,runtime){assert.deepEqual(runtime,sourceIdentity());const original=fixtureIdentity(),compiled={revision:compiledRevision,hashes:original.hashes};assert.equal(Object.keys(compiled.hashes).length,111);assert.notEqual(input.sha256,'8d9c83fcc3c42c2c94d17782ae42c152c52fcb2e833c31decc4bfee2af5aa841','known old PIT addon is not PIC initialization');const manifest=boundedJson(input.preparedManifest,input.preparedManifestSha256);assert.equal(manifest.profile?.romSha256,'8a7380f01bbc40985d377fe9764667749c36b05d45ee602b28c7e68556bd509f');assert.equal(manifest.profile.sourceCount,111);assert.equal(manifest.profile.sourceRevision,compiledRevision);assert.equal(manifest.profile.kind,'PIC_IMR_FIXED_FREE_ROM');assert.deepEqual(manifest.profile.expectedPicWitness,[255,255]);const receipt=boundedJson(input.buildReceipt,input.buildReceiptSha256);assert.deepEqual(receipt.tooling,manifest.tooling);assert.deepEqual(receipt.profile,manifest.profile);assert.deepEqual(Object.keys(manifest.tooling.hashes).sort(),supportAssets.slice(0,3).sort());assert.equal(Object.keys(manifest.sourceHashes).length,111);for(const [p,h]of Object.entries(manifest.tooling.hashes)){assert.equal(runtime.hashes[p],h);assert.equal(sha256(execFileSync('git',['show',manifest.tooling.revision+':'+p],{cwd:root,maxBuffer:32<<20})),h);}assert.equal(Object.keys(manifest.tooling.hashes).length,3);assert.equal(manifest.ownedClock?.runtimeSha256,sha256(deriveOwnedRuntime().bytes),'PIC initializer runtime');assert.equal(manifest.originalIn8Provenance?.ownedClock?.runtimeSha256,deriveOwnedRuntime().baseSha256,'retained IN8 intermediate runtime');assert.equal(Object.keys(manifest.originalIn8Provenance.sourceHashes).length,103);const proof=authenticateCompiled(input,compiled);return {compiled:{...compiled,proof,tooling:manifest.tooling},runtime,scope:'a6 frozen111 compiled PIC source; independent runtime/tool122. No raw reset equality or general AT admission.'};}
export function boundedJson(path,expectedSha){assert.equal(typeof path,'string');assert.match(expectedSha,/^[a-f0-9]{64}$/);const st=statSync(path);assert.ok(st.isFile()&&st.size<=16*1024*1024);const b=readFileSync(path);assert.equal(sha256(b),expectedSha);return JSON.parse(b);}
function authenticateCompiled(input,source){
 const manifest=boundedJson(input.preparedManifest,input.preparedManifestSha256),receipt=boundedJson(input.buildReceipt,input.buildReceiptSha256);
 assert.equal(manifest.boardRevision,source.revision);assert.equal(manifest.ownedClock.abiVersion,4);
 for(const [p,h] of Object.entries(source.hashes))assert.equal(manifest.sourceHashes[p],h,'prepared source binding '+p);
 for(const [p,h] of Object.entries(manifest.sourceHashes)){assert.equal(sha256(readFileSync(resolve(root,p))),h,'all manifest current inputs '+p);assert.equal(sha256(execFileSync('git',['show',source.revision+':'+p],{cwd:root,maxBuffer:32<<20})),h,'all manifest git inputs '+p);}
 assert.equal(manifest.ownedClock.abiSha256,sha256(readFileSync(new URL('../bochs-cpu3-native-owned-in8/abi.h',import.meta.url))));
 assert.equal(manifest.ownedClock.runtimeSha256,sha256(deriveOwnedRuntime().bytes));assert.equal(manifest.ownedClock.napiSha256,sha256(deriveOwnedNapi().bytes));
 const expected={'bochs/cpu/bw_slice_runtime.inc':manifest.ownedClock.runtimeSha256,'bochs/cpu/bw_slice_abi.h':manifest.ownedClock.abiSha256,'bochs/bochs-cpu3-native-direct-board/abi.h':manifest.ownedClock.abiSha256,'bochs/bochs-cpu3-native-direct-board-adapter/napi.cc':manifest.ownedClock.napiSha256};
 for(const [p,h] of Object.entries(manifest.patchedHashes))assert.equal(sha256(readFileSync(resolve(manifest.preparedTree,p))),h,'actual patched CPU '+p);
 for(const [src,dst] of [['scripts/bochs-cpu3-native-direct-board/runtime.h','bochs/cpu/bw_slice_runtime.h'],['scripts/bochs-cpu3-native-direct-board/addon.mk','bochs/bw_direct_addon.mk']])assert.equal(sha256(readFileSync(resolve(manifest.preparedTree,dst))),source.hashes[src],'actual unchanged copied '+dst);
 assert.deepEqual(manifest.actualPreparedHashes,expected);for(const [p,h] of Object.entries(expected))assert.equal(sha256(readFileSync(resolve(manifest.preparedTree,p))),h,'actual prepared '+p);
 assert.equal(receipt.schema,'bw.owned-clock-build-receipt.v1');assert.equal(receipt.status,'BUILD_AND_STATIC_PREFLIGHT_PASS_NO_ADDON_LOAD_OR_GUEST');assert.equal(receipt.preparedTree,manifest.preparedTree);assert.equal(receipt.preparedManifestPath,input.preparedManifest);
 const requiredFeatures={BX_CPU_LEVEL:3,BX_SUPPORT_SMP:0,BX_DEBUGGER:0,BX_USE_IDLE_HACK:0,BX_SUPPORT_REPEAT_SPEEDUPS:0,BX_SUPPORT_HANDLERS_CHAINING_SPEEDUPS:0,BX_SUPPORT_FPU:1,BX_PLUGINS:0};
 const config=readFileSync(resolve(manifest.preparedTree,'bochs/config.h'),'utf8');for(const [name,value] of Object.entries(requiredFeatures)){const m=[...config.matchAll(new RegExp('^#define\\s+'+name+'\\s+(\\d+)\\s*$','gm'))];assert.equal(m.length,1,'one actual config macro '+name);assert.equal(Number(m[0][1]),value,'actual config feature '+name);}
 assert.deepEqual(receipt.requiredFeatures,requiredFeatures);assert.deepEqual(receipt.requiredExports,['bw_direct_initialize','bw_direct_resume','bw_direct_set_irq_line','bw_direct_inspect','bw_direct_close','napi_register_module_v1']);assert.equal(receipt.preparedManifestSha256,input.preparedManifestSha256);assert.equal(receipt.sourceRevision,source.revision);assert.deepEqual(receipt.sourceHashes,source.hashes);assert.deepEqual(receipt.preparedHashes,expected);assert.equal(receipt.addonSha256,input.sha256);assert.equal(receipt.addonPath,input.addon);assert.equal(sha256(readFileSync(input.addon)),input.sha256);assert.equal(sha256(readFileSync(resolve(manifest.preparedTree,'bochs/config.h'))),receipt.configSha256);
 return {preparedManifestSha256:input.preparedManifestSha256,buildReceiptSha256:input.buildReceiptSha256,configSha256:receipt.configSha256,preparedHashes:expected};
}
