import pathlib,json,hashlib,difflib
P=pathlib.Path(__file__).parent;a=(P/'h4-generated.cc').read_text();b=(P/'h5-generated.cc').read_text();sha=lambda s:hashlib.sha256(s.encode()).hexdigest();checks=0
def check(x,label):
 global checks
 assert x,label;checks+=1
check(sha(a)=='b57a3cea1f5f5eea2092401f8dba3041eb0bc0d19551bf4273e66ad7372c60cb','H4 exact baseline')
header='/* H5 conditional scalar arguments only; H4 host protocol unchanged. */\n';check(b.startswith(header),'new provenance comment');r=b[len(header):]
old='napi_value args[4]={number(op),number(a),number(b),number(c)},r,ab;';new='napi_value args[4]={number(op),nullptr,nullptr,nullptr},r,ab;size_t argc=1;\n if(op==2){args[1]=number(a);argc=2;}else if(op==3){args[1]=number(a);args[2]=number(b);args[3]=number(c);argc=4;}'
check(r.count(new)==1,'one argument declaration');r=r.replace(new,old)
check(r.count('call("packedScalar",argc,args,&r)')==1,'one call argc');r=r.replace('call("packedScalar",argc,args,&r)','call("packedScalar",4,args,&r)')
check(r==a,'all other generated bytes unchanged')
(P/'generated.diff').write_text(''.join(difflib.unified_diff(a.splitlines(True),b.splitlines(True),fromfile='authenticated-H4',tofile='H5')))
(P/'source-differential-audit.json').write_text(json.dumps({'status':'H5_EXACT_TWO_REPLACEMENT_DIFFERENTIAL_PASS_NO_RUNTIME_CLAIM','checks':checks,'h4GeneratedNapiSha256':sha(a),'h5GeneratedNapiSha256':sha(b),'delta':'conditional scalar numeric handles and internal argc only, plus provenance comment','preserved':'all other generated NAPI bytes including lifecycle, dynamic lookup, typed ownership, native outputs, memory/PAGE','sourceDerivedFixedGuestExpectedNumericHandles':{'H4':805572,'H5':302153,'omitted':503419,'scope':'arithmetic from earlier H4 observed operation counts, not measured H5 execution or speed'}},indent=2)+'\n');print('PASS',checks)
