import {gunzipSync} from 'node:zlib';
import {readFileSync} from 'node:fs';

const REGS=['cr0','cr3','eax','ebx','ecx','edx','esi','edi','ebp','esp','cs','ds','es','fs','gs','ss','eip','eflags','dr6','dr7'];
const u32=(b,o)=>b.readUInt32LE(o);
function chunks(b,start,end){const out=[];for(let p=start;p<end;){if(p+8>end)throw new Error('truncated MOO chunk header');const tag=b.toString('ascii',p,p+4),length=u32(b,p+4),data=p+8,next=data+length;if(next>end)throw new Error(`truncated ${tag} chunk`);out.push({tag,length,data,end:next});p=next;}return out;}
function registers(b,c){if(c.length<4)throw new Error(`${c.tag} is too short`);const present=u32(b,c.data),values={},end=c.end;let p=c.data+4;for(let i=0;i<REGS.length;i++)if(present&(1<<i)){if(p+4>end)throw new Error(`truncated ${c.tag} register`);values[REGS[i]]=u32(b,p);p+=4;}if(p!==end)throw new Error(`${c.tag} has trailing bytes`);return values;}
function ram(b,c){if(c.length<4)throw new Error('RAM chunk is too short');const count=u32(b,c.data),out=[];let p=c.data+4;if(p+count*5!==c.end)throw new Error('RAM count does not match chunk length');for(let i=0;i<count;i++,p+=5)out.push([u32(b,p),b[p+4]]);return out;}
function state(b,c){const out={regs:{},masks:{},ram:[]};for(const s of chunks(b,c.data,c.end)){if(s.tag==='RG32')out.regs=registers(b,s);else if(s.tag==='RM32')out.masks=registers(b,s);else if(s.tag==='RAM ')out.ram=ram(b,s);}return out;}
function testChunk(b,c){if(c.length<4)throw new Error('TEST is too short');const out={index:u32(b,c.data)};for(const s of chunks(b,c.data+4,c.end)){if(s.tag==='BYTS'){const n=u32(b,s.data);if(n+4!==s.length)throw new Error('BYTS count mismatch');out.bytes=[...b.subarray(s.data+4,s.end)];}else if(s.tag==='INIT')out.initial=state(b,s);else if(s.tag==='FINA')out.final=state(b,s);else if(s.tag==='HASH')out.hash=b.subarray(s.data,s.end).toString('hex');}if(!out.initial||!out.final||!out.bytes||!out.hash)throw new Error(`TEST ${out.index} lacks required chunks`);return out;}
export function readMoo386(path){const compressed=readFileSync(path),b=gunzipSync(compressed);if(b.toString('ascii',0,4)!=='MOO ')throw new Error('not a MOO file');const hlen=u32(b,4),hs=8;if(hlen<12||hs+hlen>b.length)throw new Error('invalid MOO header');const major=b[hs],minor=b[hs+1],count=u32(b,hs+4),cpu=b.toString('ascii',hs+8,hs+12);if(major!==1||minor!==1||cpu!=='386E')throw new Error(`unsupported MOO ${major}.${minor} ${cpu}`);let masks={},tests=[];for(const c of chunks(b,hs+hlen,b.length)){if(c.tag==='RM32')masks={...masks,...registers(b,c)};else if(c.tag==='TEST')tests.push(testChunk(b,c));}if(tests.length!==count)throw new Error(`header count ${count} != parsed ${tests.length}`);return{compressed,major,minor,cpu,masks,tests};}
export {REGS};
