# PREPARED ONLY. One actual18child gate requires root approved bindings and grant.
from pathlib import Path
import json,hashlib,subprocess,resource,time,os
P=Path(__file__).resolve().parent;R=P/'results';B=Path('/mnt/volume1/tmp-astra/native-owned-clock-build-20261002');W={'MAIN':Path('/tmp/bw-board-386-native-owned-main-20261002'),'ALLOC':Path('/tmp/bw-board-386-native-owned-clock-alloc-20261002')};NODE='/tmp/node-v22.23.3-linux-x64/bin/node';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
raw=(P/'approved-bindings.json').read_bytes();approved=json.loads(raw);plan=json.loads((P/'plan.json').read_bytes());receipt=json.loads((B/'build-static-preflight.json').read_bytes());sources={'MAIN':approved['baselineSource'],'ALLOC':approved['candidateSource']};assert sources['MAIN']['revision']==plan['baselineSource']and len(sources['MAIN']['hashes'])==95;assert sources['ALLOC']['revision']==plan['candidateSource']and len(sources['ALLOC']['hashes'])==100;assert receipt['sourceRevision']==plan['compiledSource']and len(receipt['sourceHashes'])==86
for label in ['smoke-off','fulltrace-on']:
 proof=json.loads(Path('/mnt/volume1/tmp-astra/native-owned-clock-alloc-parity-20261002',label,'parity.json').read_bytes());assert proof['sourceRevision']==plan['candidateSource'];assert proof['status']==('ALLOC_FULL_PARITY_PASS'if label=='fulltrace-on'else'ALLOC_CAPTURE_OFF_PARITY_PASS_NOT_SPEED_GATE')
fastDirectory=Path('/mnt/volume1/tmp-astra/native-owned-clock-alloc-trace-fast-20261002/actual');fastProof=json.loads((fastDirectory/'parity.json').read_bytes());assert fastProof['status']=='ALLOC_FAST_PATH_FULL_CANONICAL_PARITY_PASS'and fastProof['canonicalRows']==1649067 and fastProof['sourceRevision']==plan['candidateSource'];assert fastProof['fastPathProof']['nativeTrace']is True and fastProof['fastPathProof']['hostJournal']is False and fastProof['fastPathProof']['orderedWords']==201366
fastAuditPath=fastDirectory/'independent-audit.json';fastAudit=json.loads(fastAuditPath.read_bytes());assert 'PASS'in fastAudit['status']and 'FAIL'not in fastAudit['status'];assert str(fastAuditPath)in approved['artifactHashes']and str(fastDirectory/'parity.json')in approved['artifactHashes'];assert sha(fastAuditPath)==approved['artifactHashes'][str(fastAuditPath)]and sha(fastDirectory/'parity.json')==approved['artifactHashes'][str(fastDirectory/'parity.json')]
reference=Path('/mnt/volume1/tmp-astra/native-owned-main-fulltrace-on-20261002/guest/capture.json');assert sha(reference)=='6a396529c6c2d95a69b1897fc60251abaecfe06676e18170920c6b6fa297f65f';baseline=json.loads(reference.read_bytes());assert baseline['source']==sources['MAIN']
def auth():
 assert (P/'approved-bindings.json').read_bytes()==raw;assert {p:sha(P/p)for p in ['run.py','plan.json']}==approved['helperHashes']
 for arm,root in W.items():
  assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=root,text=True).strip()==sources[arm]['revision'];assert not subprocess.check_output(['git','status','--porcelain'],cwd=root).strip()
  for p,h in sources[arm]['hashes'].items():assert sha(root/p)==h==hashlib.sha256(subprocess.check_output(['git','show',sources[arm]['revision']+':'+p],cwd=root)).hexdigest()
  for p,h in receipt['sourceHashes'].items():assert sha(root/p)==h==hashlib.sha256(subprocess.check_output(['git','show',receipt['sourceRevision']+':'+p],cwd=root)).hexdigest()
 for p,h in approved['artifactHashes'].items():assert sha(p)==h
 assert sha(B/'prepare.json')=='7092cf5efdb3d68b65e2b4b8a91f726ae07516e8df0de4712eeb8c92c7369c28';assert sha(B/'build-static-preflight.json')=='acebb536e93e6e74218057f18ae1e5a47d8f436e7aee212c0d82b8658d4e3da8';assert sha(receipt['addonPath'])==plan['addonSha256']
 return {'runtimeSources':sources,'compiledSourceRevision':receipt['sourceRevision'],'compiledSourceHashes':receipt['sourceHashes'],'artifactHashes':approved['artifactHashes'],'helperHashes':approved['helperHashes'],'approvedBindingsSha256':sha(P/'approved-bindings.json')}
before=auth();R.mkdir(exist_ok=False);(R/'auth-before.json').write_text(json.dumps(before,indent=2)+'\n')
def limits():resource.setrlimit(resource.RLIMIT_CORE,(0,0));resource.setrlimit(resource.RLIMIT_FSIZE,(256<<20,256<<20));resource.setrlimit(resource.RLIMIT_CPU,(120,120));os.nice(10)
records=[]
for i,order in enumerate(plan['samples']['pairOrder']):
 for arm in order.split(','):
  stem=R/(str(i)+'-'+arm);input={'addon':receipt['addonPath'],'sha256':plan['addonSha256'],'configuration':str(B/'guest-source.bochsrc'),'baseline':'/mnt/volume1/tmp-astra/js-hot-formal-final-20261001/capture.json','output':str(stem),'hostJournal':False,'nativeTrace':False,'preparedManifest':str(B/'prepare.json'),'preparedManifestSha256':sha(B/'prepare.json'),'buildReceipt':str(B/'build-static-preflight.json'),'buildReceiptSha256':sha(B/'build-static-preflight.json')};ip=R/(str(i)+'-'+arm+'.input.json');ip.write_text(json.dumps(input,indent=2)+'\n');entry=W[arm]/('scripts/run-i80386-native-owned-main.mjs'if arm=='MAIN'else'scripts/run-i80386-native-owned-clock-alloc.mjs');cmd=[NODE,'--max-old-space-size=512',str(entry),str(ip)];timedout=False;start=time.monotonic()
  with Path(str(stem)+'.stdout').open('xb')as out,Path(str(stem)+'.stderr').open('xb')as err:
   try:r=subprocess.run(cmd,cwd=W[arm],stdin=subprocess.DEVNULL,stdout=out,stderr=err,timeout=120,preexec_fn=limits,env={**os.environ,**plan['containment']['blankEnvironment']});code=r.returncode
   except subprocess.TimeoutExpired:code=None;timedout=True
  exit={'command':cmd,'exitCode':code,'timedOut':timedout,'elapsedSeconds':time.monotonic()-start,'limits':plan['containment'],'streams':{k:{'bytes':Path(str(stem)+'.'+k).stat().st_size,'sha256':sha(str(stem)+'.'+k)}for k in ['stdout','stderr']}};Path(str(stem)+'.exit.json').write_text(json.dumps(exit,indent=2)+'\n');assert code==0 and not timedout and all(v['bytes']<256<<20 for v in exit['streams'].values())
  capture=json.loads((stem/'capture.json').read_bytes());assert capture['source']==sources[arm]
  for field in ['reset','final','checkpoints','settled','ramSha256','resumes','terminal','closed']:assert capture[field]==baseline[field],(i,arm,field)
  assert capture['resumes']==439 and len(capture['checkpoints'])==6;assert capture['journal']['rows']==0 and(stem/'callbacks.jsonl').stat().st_size==0;cpu=capture['timing']['executionCPU'];assert cpu['unit']=='microseconds'and all(type(cpu[k])is int and cpu[k]>=0 for k in ['user','system','total']);assert cpu['total']==cpu['user']+cpu['system']and cpu['total']>0
  record={'pair':i,'arm':arm,'warmup':i<2,'executionCpuTotalUs':cpu['total'],'executionNs':capture['timing']['executionNs'],'fullSemanticParity':True,'captureSha256':sha(stem/'capture.json'),'inputSha256':sha(ip),'exit':exit};records.append(record);assert auth()==before;print(json.dumps({k:record[k]for k in ['pair','arm','warmup','executionCpuTotalUs']}),flush=True)
measured=[r for r in records if not r['warmup']];main=[r['executionCpuTotalUs']for r in measured if r['arm']=='MAIN'];alloc=[r['executionCpuTotalUs']for r in measured if r['arm']=='ALLOC'];assert len(main)==len(alloc)==7;mainmean=sum(main)/7;allocmean=sum(alloc)/7;reduction=100*(1-allocmean/mainmean);favorable=[alloc[i]<main[i]for i in range(7)];passed=reduction>=10 and all(favorable);summary={'status':'ACTUAL_ALLOC_PROCESS_CPU_GATE_PASS'if passed else'ACTUAL_ALLOC_PROCESS_CPU_GATE_FAIL_KEEP_MAIN','records':records,'mainSamplesUs':main,'allocSamplesUs':alloc,'mainMeanUs':mainmean,'allocMeanUs':allocmean,'meanReductionPercent':reduction,'favorablePairs':favorable,'allSevenFavorable':all(favorable),'gatePassed':passed,'planSha256':sha(P/'plan.json'),'scope':plan['metric'],'physicalRTxMeasured':False,'broaderGuestQualification':False};(R/'auth-after.json').write_text(json.dumps(auth(),indent=2)+'\n');(R/'summary.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps({k:v for k,v in summary.items()if k!='records'}),flush=True)
