/** Read/hash admission only. Distinct dispatch JS runtime reuses unchanged fe1 compiled source. */
import assert from 'node:assert/strict';
import {readFileSync,statSync}from 'node:fs';
import {execFileSync}from 'node:child_process';
import {resolve}from 'node:path';
import {fileURLToPath}from 'node:url';
import {sha256}from '../bochs-cpu3-native-owned-clock/derive.mjs';
import {sourceIdentity as compiledIdentity,authenticateBuild as authenticateCompiled}from '/tmp/bw-board-386-native-owned-in8-r3-20261002/scripts/bochs-cpu3-native-owned-in8/identity.mjs';
const root=resolve(fileURLToPath(new URL('../../',import.meta.url)));
const frozen=JSON.parse(readFileSync(new URL('./frozen-source.json',import.meta.url)));
export const supportPaths=['identity.mjs','derive.mjs','admission.mjs','frozen-source.json'].map(p=>'scripts/bochs-cpu3-native-owned-dispatch-runtime/'+p).concat(['scripts/run-i80386-native-owned-dispatch.mjs','test/i80386-owned-dispatch-runtime.test.mjs']);
export function validateMaps(runtime,compiled){assert.equal(frozen.runtime.revision,'e7a6a4ab7f2bed32a5f6d0c81e35c04e1d16d759');assert.equal(frozen.compiled.revision,'fe1eff2039520536350922a2164c8bbe29404c68');assert.equal(Object.keys(frozen.runtime.hashes).length,106);assert.equal(Object.keys(frozen.compiled.hashes).length,103);assert.deepEqual(compiled,frozen.compiled);for(const [p,h]of Object.entries(frozen.runtime.hashes))assert.equal(runtime.hashes[p],h,'frozen dispatch input '+p);for(const [p,h]of Object.entries(compiled.hashes))assert.equal(runtime.hashes[p],h,'unchanged compiled input '+p);assert.deepEqual(Object.keys(runtime.hashes).sort(),Object.keys(frozen.runtime.hashes).concat(supportPaths).sort());}
export function sourceIdentity(){const git=a=>execFileSync('git',a,{cwd:root,encoding:'utf8',maxBuffer:32<<20}).trim();assert.equal(git(['status','--porcelain']),'','clean runtime source');const revision=git(['rev-parse','HEAD']),hashes={};for(const p of Object.keys(frozen.runtime.hashes).concat(supportPaths)){const b=readFileSync(resolve(root,p)),h=sha256(b);assert.equal(h,sha256(execFileSync('git',['show',revision+':'+p],{cwd:root,maxBuffer:32<<20})));if(p in frozen.runtime.hashes){assert.equal(h,frozen.runtime.hashes[p]);assert.equal(h,sha256(execFileSync('git',['show',frozen.runtime.revision+':'+p],{cwd:root,maxBuffer:32<<20})));}hashes[p]=h;}const source={revision,hashes:Object.fromEntries(Object.entries(hashes).sort())};validateMaps(source,frozen.compiled);return source;}
export function validateOrigin(receipt,input,compiled){assert.equal(receipt.provenanceKind,'DERIVED_RELOCATED_CI_BUILD');assert.equal(receipt.sourceRevision,compiled.revision);assert.deepEqual(receipt.sourceHashes,compiled.hashes);assert.equal(receipt.relocation.original.sourceRevision,compiled.revision);assert.deepEqual(receipt.relocation.original.sourceHashes,compiled.hashes);assert.equal(receipt.relocation.original.addonSha256,input.sha256);assert.equal(input.sha256,'8d9c83fcc3c42c2c94d17782ae42c152c52fcb2e833c31decc4bfee2af5aa841');}
export function authenticateBuild(input,runtime){assert.deepEqual(runtime,sourceIdentity());const compiled=compiledIdentity();validateMaps(runtime,compiled);const proof=authenticateCompiled(input,compiled);const st=statSync(input.buildReceipt);assert.ok(st.isFile()&&st.size<=16*1024*1024);const b=readFileSync(input.buildReceipt);assert.equal(sha256(b),input.buildReceiptSha256);const receipt=JSON.parse(b);validateOrigin(receipt,input,compiled);assert.deepEqual(compiledIdentity(),compiled);assert.deepEqual(sourceIdentity(),runtime);return {status:'SOURCE_ONLY_REUSED_CI_NATIVE_WITH_DISTINCT_DISPATCH_RUNTIME',compiled:{...compiled,origin:receipt.relocation.original,proof},runtime,frozenDispatchRevision:frozen.runtime.revision,scope:'Compiled fe1/103 unchanged; frozen dispatch106 plus six support inputs. No recompile, native execution or speed claim.'};}
